ARC9.CLASS_PISTOL = 0
ARC9.CLASS_RIFLE = 1
ARC9.CLASS_SHOTGUN = 2
ARC9.CLASS_PDW = 3
ARC9.CLASS_CARBINE = 4
ARC9.CLASS_DMR = 5
ARC9.CLASS_SNIPER = 6
ARC9.CLASS_LAUNCHER = 7
ARC9.CLASS_GRENADE = 8
ARC9.CLASS_DEPLOYABLE = 9
ARC9.CLASS_TOOL = 10
ARC9.CLASS_OTHER = 31 -- 11-30 are reserved

ARC9.HITPROFILE_AR = {
    [HITGROUP_HEAD] = 1.25,
    [HITGROUP_CHEST] = 1,
    [HITGROUP_LEFTARM] = 0.9,
    [HITGROUP_RIGHTARM] = 0.9,
}

ARC9.HITPROFILE_PISTOL = {
    [HITGROUP_HEAD] = 2,
    [HITGROUP_CHEST] = 1,
    [HITGROUP_LEFTARM] = 0.9,
    [HITGROUP_RIGHTARM] = 0.9,
}

ARC9.HITPROFILE_SNIPER = {
    [HITGROUP_HEAD] = 5,
    [HITGROUP_CHEST] = 1.1,
    [HITGROUP_STOMACH] = 1.0,
    [HITGROUP_LEFTARM] = 0.95,
    [HITGROUP_RIGHTARM] = 0.95,
}