L = {}

--L["font"] = "Exo Regular"

L["autostat.damagemax"] = "Урон вблизи"
L["autostat.damagemin"] = "Урон на расстоянии"
L["autostat.damagerand"] = "Разброс урона"
L["autostat.rangemin"] = "Минимальная дальность урона"
L["autostat.rangemax"] = "Максимальная дальность"
L["autostat.distance"] = "Дальность поражения"
L["autostat.num"] = "Кол-во снарядов"
L["autostat.penetration"] = "Пробивная способность"
L["autostat.ricochetanglemax"] = "Угол рикошета"
L["autostat.ricochetchance"] = "Шанс рикошета"
L["autostat.armorpiercing"] = "Бронепробиваемость"
L["autostat.entitymuzzlevelocity"] = "Скорость снаряда"
L["autostat.physbulletmuzzlevelocity"] = "Скорость пули"
L["autostat.physbulletdrag"] = "Баллистика пули"
L["autostat.physbulletgravity"] = "Баллистика пули"
L["autostat.chambersize"] = "Патронник"
L["autostat.clipsize"] = "Емкость магазина"
L["autostat.supplylimit"] = "Лимит магазинов"
L["autostat.secondarysupplylimit"] = "Лимит вторичных патронов"
L["autostat.ammopershot"] = "Патронов за выстрел"
L["autostat.manualactionchamber"] = "Патронов за взведение"
L["autostat.triggerdelay"] = "Задержка курка"
L["autostat.rpm"] = "Скорострельность"
L["autostat.postburstdelay"] = "Задержка после очереди"
L["autostat.pushbackforce"] = "Отталкивание"
L["autostat.recoil"] = "Отдача"
L["autostat.recoilpatterndrift"] = "Непредсказуемость отдачи"
L["autostat.recoilup"] = "Вертикальная отдача"
L["autostat.recoilside"] = "Горизонтальная отдача"
L["autostat.recoilrandomup"] = "Верт. случайная отдачи"
L["autostat.recoilrandomside"] = "Гориз. случайная отдача"
L["autostat.recoildissipationrate"] = "Скорость рассеивания отдачи"
L["autostat.recoilresettime"] = "Время до сброса отдачи"
L["autostat.recoilautocontrol"] = "Автоконтроль отдачи"
L["autostat.recoilkick"] = "Рывки отдачи"
L["autostat.spread"] = "Разброс"
L["autostat.pelletspread"] = "Разброс  дроби"
L["autostat.freeaimradius"] = "Радиус свободного прицела"
L["autostat.sway"] = "Стабильность прицеливания"
L["autostat.aimdownsightstime"] = "Скорость прицеливания"
L["autostat.sprinttofiretime"] = "Возвращение после бега"
L["autostat.reloadtime"] = "Скорость перезарядки"
L["autostat.deploytime"] = "Скорость доставания"
L["autostat.cycletime"] = "Скорость взвода"
L["autostat.fixtime"] = "Скорость починки клина"
L["autostat.overheattime"] = "Скорость перегрева"
L["autostat.speed"] = "Скорость ходьбы"
L["autostat.bashdamage"] = "Урон врукопашную"
L["autostat.bashrange"] = "Дальность рукопашного"
L["autostat.bashlungerange"] = "Дальность выпада рукопашного"
L["autostat.heatcapacity"] = "Теплоемкость"
L["autostat.heatdissipation"] = "Скорость охлаждения"
L["autostat.malfunctionmeanshotstofail"] = "Шанс клина"
L["autostat.shootvolume"] = "Громкость выстрела"
L["autostat.alwaysphysbullet"] = "Физические пули"
L["autostat.neverphysbullet"] = "Нефизические пули"
L["autostat.infiniteammo"] = "Бесконечный боезапас"
L["autostat.bottomlessclip"] = "Безлимитный магазин"
L["autostat.shotgunreload"] = "Перезарядка по одному"
L["autostat.hybridreload"] = "Гибридная перезарядка"
L["autostat.manualaction"] = "Ручной взвод"
L["autostat.canfireunderwater"] = "Подводная стрельба"
L["autostat.autoreload"] = "Автоперезарядка"
L["autostat.autoburst"] = "Автоматические очереди"
L["autostat.runawayburst"] = "Очередь до конца"
L["autostat.shootwhilesprint"] = "Стрельба во время бега"
L["autostat.bash"] = "Рукопашная"
L["autostat.overheat"] = "Перегрев"
L["autostat.malfunction"] = "Клины"
L["autostat.malfunctionwait"] = "Задержка после клина"
L["autostat.bipod"] = "Сошки"
L["autostat.noflash"] = "Без дульной вспышки"
L["autostat.bulletguidance"] = "Автонаведение"
L["autostat.bulletguidanceamount"] = "Сила автонаведения"
L["autostat.heatpershot"] = "Нагрев за выстрел"
L["autostat.explosiondamage"] = "Урон взрывом"
L["autostat.explosionradius"] = "Радиус взрыва"
L["autostat.headshotdamage"] = "Урон в голову"
L["autostat.chestdamage"] = "Урон в грудь"
L["autostat.stomachdamage"] = "Урон в живот"
L["autostat.armdamage"] = "Урон по рукам"
L["autostat.legdamage"] = "Урон по ногам"
L["autostat.visualrecoil"] = "Физическая отдача"
L["autostat.visualrecoilup"] = "Физ. вертикальная отдача"
L["autostat.visualrecoilside"] = "Физ. горизонтальная отдача"
L["autostat.visualrecoilroll"] = "Физ. угловая отдача"
L["autostat.visualrecoilpunch"] = "Физ. толчок отдачи"
L["autostat.breathholdtime"] = "Время задержки дыхания"

L["autostat.secondary.true"] = "при вкл. TrueNames"
L["autostat.secondary.silenced"] = "с глушителем"
L["autostat.secondary.midair"] = "в воздухе"
L["autostat.secondary.crouch"] = "в присяди"
L["autostat.secondary.first"] = "первым выстрелом"
L["autostat.secondary.firstshot"] = "первым выстрелом"
L["autostat.secondary.last"] = "последним выстрелом"
L["autostat.secondary.lastshot"] = "последним выстрелом"
L["autostat.secondary.empty"] = "последним выстрелом"
L["autostat.secondary.evenshot"] = "каждый чётный выстрел"
L["autostat.secondary.oddshot"] = "каждый нечётный выстрел"
L["autostat.secondary.evenreload"] = "каждую чёт. перезарядку"
L["autostat.secondary.oddreload"] = "каждую нечёт. перезарядку"
L["autostat.secondary.sights"] = "в прицеле"
L["autostat.secondary.hipfire"] = "от бедра"
L["autostat.secondary.shooting"] = "пока стреляешь"
L["autostat.secondary.recoil"] = "пока стреляешь" --"With Each Shot"
L["autostat.secondary.move"] = "в движении"
L["autostat.secondary.blindfire"] = "при слепой стрельбе"
L["autostat.secondary.ubgl"] = "у подствольника"

L["unit.second"] = "с"
L["unit.meter"] = "м"
L["unit.millimeter"] = "мм"
L["unit.meterpersecond"] = "м/с"
L["unit.hammerunit"] = "HU"
L["unit.decibel"] = "дБ"
L["unit.rpm"] = "RPM"
L["unit.moa"] = "MOA"
L["unit.dmg"] = "DMG"
L["unit.projectiles"] = "PROJ"

L["hud.firemode.single"] = "ОДИНОЧ."
L["hud.firemode.burst"] = "ОЧЕРЕДЬ"
L["hud.firemode.auto"] = "АВТОМАТ."
L["hud.firemode.safe"] = "ПРЕДОХР."

L["hud.version"] = "ARCTIC SYSTEMS HUD v"
L["hud.jammed"] = "КЛИН!"
L["hud.therm_deco"] = "ТЕМП. СТВОЛА"

L["hud.hint.ubgl"] = "ПЕРЕКЛ. НА"
L["hud.hint.zoom"] = "СМЕНА КРАТНОСТИ"
L["hud.hint.breath"] = "ЗАДЕРЖАТЬ ДЫХАНИЕ"
L["hud.hint.bash"] = "УДАР"
L["hud.hint.inspect"] = "ОСМОТР"
L["hud.hint.switchsights"] = "СМЕНИТЬ ПРИЦЕЛ"
L["hud.hint.firemode"] = "СМЕНА РЕЖИМА ОГНЯ"
L["hud.hint.cycle"] = "ВЗВОД ЗАТВОРА"
L["hud.hint.toggleatts"] = "ПЕРЕКЛ. МОДУЛЬ"
L["hud.hint.peek"] = "ВЫГЛЯНУТЬ"
L["hud.hint.customize"] = "КАСТОМИЗАЦИЯ"
L["hud.hint.safe"] = "ПРЕДОХРАНИТЕЛЬ"
L["hud.hint.lean"] = "НАКЛОН"

L["autostat.enable.pre"] = "Вкл."
L["autostat.disable.pre"] = "Выкл."
L["autostat.enable.post"] = ""
L["autostat.disable.post"] = ""

L["ammo.pistol"] = "Пистолет. патрон"
L["ammo.357"] = "Магнум патроны"
L["ammo.smg1"] = "Карабин. патроны"
L["ammo.ar2"] = "Винтов. патроны"
L["ammo.buckshot"] = "Дробов. патроны"
L["ammo.sniperpenetratedround"] = "Снайп. патроны"
L["ammo.smg1_grenade"] = "Гранаты"

L["customize.panel.customize"] = "КАСТОМИЗАЦИЯ"
L["customize.panel.personalize"] = "КОСМЕТИКА"
L["customize.panel.stats"] = "ХАР-КИ & БАЛЛИСТИКА"
L["customize.panel.trivia"] = "ИНФО"
L["customize.panel.inspect"] = "ОСМОТР"
L["customize.panel.presets"] = "Пресеты"

L["customize.stats.firepower"] = "Огн. мощь"
L["customize.stats.rof"] = "Скорострельность"
L["customize.stats.cyclic"] = "Скорострельность"
L["customize.stats.capacity"] = "Ёмкость"
L["customize.stats.range"] = "Дальность"
L["customize.stats.precision"] = "Точность"
L["customize.stats.muzzlevelocity"] = "Скорости пули"
L["customize.stats.ammo"] = "Тип патрона"
L["customize.stats.penetration"] = "Пробивание"
L["customize.stats.ricochet"] = "Шанс рикошета"
L["customize.stats.armorpiercing"] = "Бронепробиваемость"
L["customize.stats.explosive"] = "Урон взрывом"
L["customize.stats.speed"] = "Скорость движения"
L["customize.stats.aimtime"] = "Скорость прицел."
L["customize.stats.sprinttofire"] = "После бега"
L["customize.stats.firemodes"] = "Режимы"
L["customize.stats.burstdelay"] = "Задержка очереди"
L["customize.stats.triggerdelay"] = "Задержка курка"
L["customize.stats.noise"] = "Громкость"
L["customize.stats.sway"] = "Стабильность"
L["customize.stats.freeaim"] = "Радиус свобод. прицела"
L["customize.stats.supplylimit"] = "Лимит магазинов"

L["customize.hint.controller"] = "Режим контроллера включен."
L["customize.hint.expand"] = "Раскрыть"
L["customize.hint.attach"] = "Установить"
L["customize.hint.unattach"] = "Убрать"
L["customize.hint.recenter"] = "Центрирование"
L["customize.hint.rotate"] = "Поворот"
L["customize.hint.pan"] = "Схватить"
L["customize.hint.zoom"] = "Приблизить"
L["customize.hint.select"] = "Выбрать"
L["customize.hint.deselect"] = "Отм. выделение"
L["customize.hint.cycle"] = "След. слот"
L["customize.hint.last"] = "Посл. слот"
L["customize.hint.cursor"] = "Курсор"
L["customize.hint.recalculate"] = "Пересчитать"
L["customize.hint.nextmode"] = "След. режим"
L["customize.hint.lastmode"] = "Пред. режим"
L["customize.hint.save"] = "Сохранить"
L["customize.hint.quicksave"] = "Быстрое сохранение"
L["customize.hint.import"] = "Импорт"
L["customize.hint.install"] = "Установить"
L["customize.hint.export"] = "Экспорт"
L["customize.hint.delete"] = "Удалить"
L["customize.hint.open"] = "Открыть"

L["customize.trivia.description"] = "Описание"

L["customize.bench.dummy"] = "БАЛЛИСТИЧЕСКАЯ МИШЕНЬ"
L["customize.bench.effect"] = "ЭФФЕКТ НА ДАЛЬНОСТИ"
L["customize.bench.ballistics"] = "ОЦЕНКА БАЛЛИСТИЧЕСКИХ ХАРАКТЕРИСТИК"
L["customize.bench.precision"] = "ИСПЫТАНИЕ ТОЧНОСТИ"

L["settings.title"] = "Настройки ARC9"
L["settings.desc"] = "Описание"

L["settings.tabname.performance"] = "Производительность"
L["settings.tabname.optics"] = "Оптика"
L["settings.tabname.crosshair"] = "Перекрестие"
L["settings.tabname.hud_cust"] = "Персонализация"
L["settings.tabname.hud_game"] = "Игровой HUD"
L["settings.tabname.npc"] = "NPC"
L["settings.tabname.gameplay"] = "Геймплей"
L["settings.tabname.visuals"] = "Визуал"
L["settings.tabname.bullets"] = "Физика пуль"
L["settings.tabname.attachments"] = "Обвесы"
L["settings.tabname.modifiers"] = "Модификаторы"
L["settings.tabname.controller"] = "Контроллер"
L["settings.tabname.developer"] = "Для разработчиков"




L["settings.cheapscopes.title"] = "Производительные прицелы"
L["settings.cheapscopes.desc"] = "Более производельный вариант рендеринга прицелов путём приближения всей камеры, вместо рендеринга второй сцены. Сильно улучшает производительность на больших картах и не только."
L["settings.allflash.title"] = "Фонарики у всех игроков"
L["settings.allflash.desc"] = "Показывать фонарики у всех игроков на сервере.\n\nЗначительно снижает производительность на серверах."
L["settings.tpik.title"] = "Включить TPIK"
L["settings.tpik.desc"] = "TPIK (Инверсивная Кинематика для третьего лица) это система для анимации оружия и рук у игроков от третьего лица.\n\nВы можете настроить эту систему во вкладке Визуал."
L["settings.cust_blur.title"] = "Фон кастомизации"
L["settings.cust_blur.desc"] = "Размывает фон в меню кастомизации."
L["settings.fx_reloadblur.title"] = "Во время перезарядки"
L["settings.fx_reloadblur.desc"] = "Размытие мира во время перезарядки."
L["settings.fx_animblur.title"] = "При первом доставании"
L["settings.fx_animblur.desc"] = "Размытие мира при доставании нового оружия в первый раз."
L["settings.fx_rtblur.title"] = "В оптике"
L["settings.fx_rtblur.desc"] = "Размытие мира при использовании оптических прицелов."
L["settings.fx_adsblur.title"] = "В прицелах"
L["settings.fx_adsblur.desc"] = "Размытие части оружия при использовании любых прицелов."
L["settings.eject_fx.title"] = "Эффект дыма"
L["settings.eject_fx.desc"] = "Производит эффект дыма от только что выпущенных гильз. (если возможно)"
L["settings.eject_time.title"] = "Доп. время"
L["settings.eject_time.desc"] = "Позволяет гильзам существовать дольше. Может снизить производительность."

-- Use this method to localize convars in settings menu:
-- settings.convar.title = "Convar Title"
-- settings.convar.desc = "Convar Description"

L["settings.developer.developer"] = "Настройки разработчика"
L["settings.attachments.inventory"] = "Инвентарь"
L["settings.attachments.customization"] = "Кастомизация"
L["settings.bullets.bullets"] = "Физика пуль"
L["settings.visuals.tpik"] = "TPIK"
L["settings.visuals.viewmodel"] = "Viewmodel"
L["settings.gameplay.mechanics"] = "Игровые механики"
L["settings.gameplay.controls"] = "Управление"
L["settings.npc.weapons"] = "Оружие NPC"
L["settings.hud_game.breath"] = "Задержка дыхания"
L["settings.hud_game.killfeed"] = "Киллфид"
L["settings.hud_game.lcd"] = "LCD Панель"
L["settings.hud_cust.customization"] = "Кастомизация"
L["settings.hud_cust.hud"] = "HUD"
L["settings.crosshair.crosshair"] = "Перекрестие"
L["settings.optics.color"] = "Цвет сетки"
L["settings.optics.control"] = "Управление"
L["settings.performance.important"] = "Важное"
L["settings.performance.blur.title"] = "Размытие"
L["settings.performance.shelleject.title"] = "Гильзы"


L["settings.optics.cheapscopes.title"] = "Производительные прицелы"
L["settings.optics.cheapscopes.desc"] = "Более производельный вариант рендеринга прицелов путём приближения всей камеры, вместо рендеринга второй сцены. Сильно улучшает производительность на больших картах и не только."
L["settings.optics.compensate_sens.title"] = "Компенсировать чувствительность"
L["settings.optics.compensate_sens.desc"] = "Компенсировать чувствительность мыши в оптических прицелах."
L["settings.optics.toggleads.title"] = "Прицеливание по нажатию"
L["settings.optics.toggleads.desc"] = "Вместо удерживания кнопки прицеливания достаточно нажать один раз."
L["settings.optics.reflex.title"] = "Коллиматорных прицелов"
L["settings.optics.reflex.desc"] = "Цвет сетки у коллиматорных/ голографических прицелов.\n\nНе все прицелы поддерживают смену цвета."
L["settings.optics.scope.title"] = "Оптики"
L["settings.optics.scope.desc"] = "Цвет сетки у оптических прицелов.\n\nНе все прицелы поддерживают смену цвета."

L["settings.crosshair.cross_enable.title"] = "Включить перекрестие"
L["settings.crosshair.cross_enable.desc"] = "Включить перекрестие. Заблокировано на некоторых оружиях."
L["settings.crosshair.cross.title"] = "Цвет"
L["settings.crosshair.cross.desc"] = "Цвет перекрестия."
L["settings.crosshair.cross_size_mult.title"] = "Размер"
L["settings.crosshair.cross_size_mult.desc"] = "Множитель размера перекрестия."
L["settings.crosshair.cross_size_dot.title"] = "Размер точки"
L["settings.crosshair.cross_size_dot.desc"] = "Множитель размера точки перекрестия."
L["settings.crosshair.cross_size_prong.title"] = "Размер зубцов"
L["settings.crosshair.cross_size_prong.desc"] = "Множитель размера зубцов у перекрестия."
L["settings.crosshair.crosshair_static.title"] = "Статичный"
L["settings.crosshair.crosshair_static.desc"] = "Включает полностью статичный прицел, который не двигается от стрельбы."
L["settings.crosshair.crosshair_force.title"] = "Принудительно включить"
L["settings.crosshair.crosshair_force.desc"] = "Принудительно включает перекрестие даже не пушках которые не позволяют это.\n\nЭто серверная переменная."

L["settings.hud_cust.hud_scale.title"] = "Масштаб"
L["settings.hud_cust.hud_scale.desc"] = "Множитель размера интерфейса ARC9."
L["settings.hud_cust.hud_color.title"] = "Цвет интерфейса"
L["settings.hud_cust.hud_color.desc"] = "Главный цвет интерфейса, акцент."
L["settings.hud_cust.language_id.title"] = "Язык"
L["settings.hud_cust.language_id.desc"] = "Языковой пакет для использования с ARC9."
L["settings.hud_cust.cust_light.title"] = "Включить подсветку"
L["settings.hud_cust.cust_light.desc"] = "Включает подсветку оружия в меню кастомизации.\n\nТо же самое, что и кнопка рядом с настройками."
L["settings.hud_cust.cust_light_brightness.title"] = "Яркость подсветки"
L["settings.hud_cust.cust_light_brightness.desc"] = "Яркость подсветки оружия.\n\nНе забудьте включить её сперва!"
L["settings.hud_cust.cust_hints.title"] = "Подсказки"
L["settings.hud_cust.cust_hints.desc"] = "Включает подсказки в меню кастомизации."
L["settings.hud_cust.cust_roll_unlock.title"] = "Разблокировать повороты"
L["settings.hud_cust.cust_roll_unlock.desc"] = "Разблокирует дополнительную ось поворота оружия в меню кастомизаци.\n\nМожет выгядеть и управлятся не лучшим образом."
L["settings.hud_cust.cust_exit_reset_sel.title"] = "Сброс слота при выходе"
L["settings.hud_cust.cust_exit_reset_sel.desc"] = "Выход из меню кастомизации будет сбрасывать выбор активного слота."

L["settings.hud_game.hud_arc9.title"] = "Включить HUD"
L["settings.hud_game.hud_arc9.desc"] = "Включает HUD на ARC9 пушках."
L["settings.hud_game.hud_always.title"] = "На всех оружиях"
L["settings.hud_game.hud_always.desc"] = "Включает этот HUD на всех пушках."
L["settings.hud_game.hud_compact.title"] = "Компактный режим"
L["settings.hud_game.hud_compact.desc"] = "Компактный режим для панели HUD."
L["settings.hud_game.hud_keephints.title"] = "Подсказки"
L["settings.hud_game.hud_keephints.desc"] = "Показывать подсказки по управлению оружием ARC9 наверху панели."
L["settings.hud_game.killfeed_enable.title"] = "Иконки в киллфиде"
L["settings.hud_game.killfeed_enable.desc"] = "Включает автогенерацию иконок ARC9 пушек."
L["settings.hud_game.killfeed_dynamic.title"] = "Динамичное обновление"
L["settings.hud_game.killfeed_dynamic.desc"] = "Иконки оружия в киллфиде будет обновлятся после каждого убийства.\n\nВыключи, если хочешь эти самые 0.1 фпс."
L["settings.hud_game.breath_hud.title"] = "Индикатор"
L["settings.hud_game.breath_hud.desc"] = "Показывать, сколько вы можете ещё задерживать дыхание в прицелах в интерфейсе."
L["settings.hud_game.breath_pp.title"] = "Пост-обработка"
L["settings.hud_game.breath_pp.desc"] = "Задержка дыхания будет делать эффекты резкости на экране."
L["settings.hud_game.breath_sfx.title"] = "Озвучка"
L["settings.hud_game.breath_sfx.desc"] = "При задерживании дыхания будут воспроизводится соответствующие звуки."

L["settings.npc.npc_equality.title"] = "Одинаковый урон"
L["settings.npc.npc_equality.desc"] = "NPC будут делать точно такой же урон как и игроки.\n\nЭто серверная переменная."
L["settings.npc.npc_atts.title"] = "Спавнить с обвесами"
L["settings.npc.npc_atts.desc"] = "Заспавненные или выданные ARC9 пушки будут с случайным набором обвесов.\n\nЭто серверная переменная."
L["settings.npc.npc_autoreplace.title"] = "Заменить оружие у NPC"
L["settings.npc.npc_autoreplace.desc"] = "Заменить оружие у NPC случайным ARC9 стволом.\n\nЭто серверная переменная."
L["settings.npc.replace_spawned.title"] = "Заменять оружие на полу"
L["settings.npc.replace_spawned.desc"] = "Заменяет заспавненные картой или вами HL2 оружие случайным ARC9 стволом.\n\nЭто серверная переменная."
L["settings.npc.npc_give_weapons.title"] = "Игроки могут давать оружие"
L["settings.npc.npc_give_weapons.desc"] = "Игроки могут нажать Е на NPC чтобы дать им своё оружие.\n\nЭто серверная переменная."

L["settings.gameplay.toggleads.title"] = "Прицеливание по нажатию"
L["settings.gameplay.toggleads.desc"] = "Вместо удерживания кнопки прицеливания достаточно нажать один раз."
L["settings.gameplay.autolean.title"] = "Автонаклоны"
L["settings.gameplay.autolean.desc"] = "Прицеливония возле угла стены будет автоматически наклонять игрока если возможно."
L["settings.gameplay.autoreload.title"] = "Автоперезарядка"
L["settings.gameplay.autoreload.desc"] = "Пустое оружие ARC9 будет перезаряжатся автоматически."
L["settings.gameplay.infinite_ammo.title"] = "Бесконечные патроны"
L["settings.gameplay.infinite_ammo.desc"] = "Оружие будет иметь неограниченный боезапас.\n\nЭто серверная переменная."
L["settings.gameplay.realrecoil.title"] = "Физическая отдача"
L["settings.gameplay.realrecoil.desc"] = "Некоторое настроенное оружие будет иметь (полностью) физическую отдачу и всё с этим связанное, вместо обыкновенной отдачи. Очень важно для баланса некоторых оружейных паков.\n\nЭто серверная переменная."
L["settings.gameplay.lean.title"] = "Наклоны"
L["settings.gameplay.lean.desc"] = "Игрок сможет наклонять тело через бинды +alt1 и +alt2, а также автоматически (если включено).\n\nЭто серверная переменная."
L["settings.gameplay.mod_sway.title"] = "Качение оружия"
L["settings.gameplay.mod_sway.desc"] = "Некоторые настроенные пушки будут качаться и быть нестабильными в прицелах (и без прицелов тоже).\n\nЭто серверная переменная."
L["settings.gameplay.mod_freeaim.title"] = "Свободный прицел"
L["settings.gameplay.mod_freeaim.desc"] = "Пушки будет иметь свободный прицел, вместо фиксирования в центр экрана (Free aim).\n\nЭто серверная переменная."
L["settings.gameplay.mod_bodydamagecancel.title"] = "Выкл. множитель урона по игрокам"
L["settings.gameplay.mod_bodydamagecancel.desc"] = "Выключает стандартный множитель урона по игрокам. Выключайте только если у вас есть аддон изменяющий множители урона в разные части тела.\n\nЭто серверная переменная."
L["settings.gameplay.breath_slowmo.title"] = "Слоу-мо в задержке дыхания"
L["settings.gameplay.breath_slowmo.desc"] = "Задерживание дыхания будет замедлять течение времени.\n\nТолько в одиночной игре."
L["settings.gameplay.manualbolt.title"] = "Ручные болтовки"
L["settings.gameplay.manualbolt.desc"] = "Вместо автоматического взвода затвора после отпускания кнопки стрельбы, болтовые оружия будет требовать нажатия R. \n\nПрямо как в FA:S 2.0"
L["settings.gameplay.nearwall.title"] = "Рядом со стеной"
L["settings.gameplay.nearwall.desc"] = "Не позволяет стрелять стоя вплотную к стенке или к другому препятствию перед тобой."

L["settings.visuals.vm_bobstyle.title"] = "Тип качения"
L["settings.visuals.vm_bobstyle.desc"] = "Выберете стиль качения оружия созднный разными разработчиками ARC9 (и valve!), от самого нового стиля до старого."
L["settings.visuals.fov.title"] = "FOV"
L["settings.visuals.fov.desc"] = "Меняет поле зрения вьюмодели. Делает её больше или меньше. Используйте ответственно."
L["settings.visuals.vm_addx.title"] = "Смещение по X"
L["settings.visuals.vm_addx.desc"] = "Сместить вьюмодель налево или направо."
L["settings.visuals.vm_addy.title"] = "Смещение по Y"
L["settings.visuals.vm_addy.desc"] = "Сместить вьюмодель вперед или назад."
L["settings.visuals.vm_addz.title"] = "Смещение по Z"
L["settings.visuals.vm_addz.desc"] = "Сместить вьюмодель вверх или вниз."
L["settings.visuals.tpik.title"] = "Включить TPIK"
L["settings.visuals.tpik.desc"] = "TPIK (Инверсивная Кинематика для третьего лица) это система для анимации оружия и рук у игроков от третьего лица."
L["settings.visuals.tpik_others.title"] = "TPIK всех игроков"
L["settings.visuals.tpik_others.desc"] = "Включить эту систему на игроках помимо вас. Понижает производительность."
L["settings.visuals.tpik_framerate.title"] = "Частота TPIK"
L["settings.visuals.tpik_framerate.desc"] = "Максимальная частота на которой TPIK работает. Ставь на 0 для снятия ограничения."

L["settings.bullets.bullet_physics.title"] = "Физические пули"
L["settings.bullets.bullet_physics.desc"] = "Физические пули имеют физику. Падение на расстоянии, требуется некоторое время до приземления и всё в этом роде. Некоторое оружие может не поддерживать такое.\n\nЭто серверная переменная."
L["settings.bullets.bullet_gravity.title"] = "Гравитация"
L["settings.bullets.bullet_gravity.desc"] = "Множитель гравитации пуль.\n\nЭто серверная переменная."
L["settings.bullets.bullet_drag.title"] = "Сопротивлен. воздуха"
L["settings.bullets.bullet_drag.desc"] = "Множитель сопротивления воздуха у пуль.\n\nЭто серверная переменная."
L["settings.bullets.ricochet.title"] = "Рикошеты"
L["settings.bullets.ricochet.desc"] = "Некоторые пули смогут отскакивать от поверхностей и наносить урон.\n\nЭто серверная переменная."
L["settings.bullets.mod_penetration.title"] = "Пробивание"
L["settings.bullets.mod_penetration.desc"] = "Некоторые пули смогут пробивать различные поверхности и наносить урон всему, что стоит за этой поверхностью.\n\nЭто серверная переменная."
L["settings.bullets.bullet_lifetime.title"] = "Время жизни"
L["settings.bullets.bullet_lifetime.desc"] = "Сколько пуля сможет просуществовать в свободном полете.\n\nЭто серверная переменная."
L["settings.bullets.bullet_imaginary.title"] = "Воображаемые пули"
L["settings.bullets.bullet_imaginary.desc"] = "Пули будут смогут преодолевать границы карты и \"существовать\" в скайбоксе."

L["settings.attachments.atts_nocustomize.title"] = "Отключить кастомизацию"
L["settings.attachments.atts_nocustomize.desc"] = "Отключить всю кастомизацию через меню.\n\nЭто серверная переменная."
L["settings.attachments.atts_max.title"] = "Макс. обвесов"
L["settings.attachments.atts_max.desc"] = "Максимальное число обвесов на одном оружии, включая косметические обвесы.\n\nЭто серверная переменная."
L["settings.attachments.autosave.title"] = "Автосохранение"
L["settings.attachments.autosave.desc"] = "Ваше последняя конфигурация оружия будет сохранена и автоматически установлена при следующем доставании."
L["settings.attachments.free_atts.title"] = "Бесплатные обвесы"
L["settings.attachments.free_atts.desc"] = "Обвесы можно использовать на оружии без подбирания их.\n\nЭто серверная переменная."
L["settings.attachments.atts_lock.title"] = "Один для всего"
L["settings.attachments.atts_lock.desc"] = "Подбирание одного обвеса позволить использовать его неограниченное количество раз на любом оружии.\n\nЭто серверная переменная."
L["settings.attachments.atts_loseondie.title"] = "Терять после смерти"
L["settings.attachments.atts_loseondie.desc"] = "Все подобранные обвесы удалятся после вашей смерти.\n\nЭто серверная переменная."
L["settings.attachments.atts_generateentities.title"] = "Генерировать энтити"
L["settings.attachments.atts_generateentities.desc"] = "Генерировать энтити обвесов для их спавна и последующего использования (если бесплатные обвесы выключены).\n\nВозможно увеличит время запуска в игру.\n\nЭто серверная переменная."


L["settings.modifiers.quick.title"] = "Быстрые модификаторы характеристик"
-- wawa
L["settings.modifiers.quick.desc"] = "Простите, но мы не успели доделать их к релизу. Можете использовать продвинутые модификаторы в спавнменю > Options > ARC9 > Modifiers пока что."


L["settings.controller.misc"] = "Прочее"
L["settings.controller.misc.desc"] = "Здесь должна быть кнопка для вызова панели для продвинутой конфигурации контроллеров, но пока что она в спавнменю > Options > ARC9 > Controller."
L["settings.controller.controller.title"] = "Символы контроллера"
L["settings.controller.controller.desc"] = "Включает отображение символов для контроллеров, показывая кнопки контроллера вместо обычных клавиатурных кнопок."
L["settings.controller.controller_rumble.title"] = "Вибрация"
L["settings.controller.controller_rumble.desc"] = "Включает вибрацию контроллера, если установлен специальный DLL мод от Fesiug.\n\ngithub.com/Fesiug/\ngmod-sinput"
L["settings.controller.controller_config.title"] = "Продвинутый конфиг"
L["settings.controller.controller_config.content"] = "Открыть панель"
L["settings.controller.controller_config.desc"] = "Открывает панель для продвинутой конфигурации контроллеров."

L["settings.developer.dev_always_ready.title"] = "Всегда Ready"
L["settings.developer.dev_always_ready.desc"] = "Всегда проигрывать анимацию \"ready\" при доставании оружия.\n\nЭто серверная переменная."
L["settings.developer.dev_benchgun.title"] = "Benchgun"
L["settings.developer.dev_benchgun.desc"] = "Оставить вьюмодель оружия там же, где оно и находится прямо сейчас."
L["settings.developer.dev_show_shield.title"] = "Показывать щиты"
L["settings.developer.dev_show_shield.desc"] = "Показывать модель щитов у игроков."

L["settings.developer.print"] = "В консоль"
L["settings.developer.reload"] = "Перезагрузить"

L["settings.developer.reloadatts.title"] = "Обвесы"
L["settings.developer.reloadlangs.title"] = "Языки"
L["settings.developer.dev_listanims.title"] = "Список анимаций"
L["settings.developer.dev_listbones.title"] = "Список костей"
L["settings.developer.dev_listbgs.title"] = "Список бодигрупп"
L["settings.developer.dev_listatts.title"] = "Список QCAttachaments"
L["settings.developer.dev_export.title"] = "Код экспорта"
L["settings.developer.dev_getjson.title"] = "JSON оружия"


L["incompatible.title"] = "ARC9: НЕСОВМЕСТИМЫЕ АДДОНЫ"
L["incompatible.line1"] = "У вас включены аддоны которые точно не будут работать с ARC9."
L["incompatible.line2"] = "Отключите их, иначе что-то может пойти не так!"
L["incompatible.confirm"] = "Ознакомлен"
L["incompatible.wait"] = "Подождите {time}с"
L["incompatible.never"] = "Не предупреждайте меня"
L["incompatible.never.hover"] = "Уверен? Надеюсь, ты понимаешь последствия своего решения."
L["incompatible.never.confirm"] = "Ты решил отказаться от предупреждений несовместимостых аддонов. Если что-то окажется сломано - это на твоей совести, мы не будем тебе помогать."


L["customize.presets.default"] = "Стандартный"
L["customize.presets.default.long"] = "Стандартный пресет"
L["customize.presets.random"] = "Случайный"
L["customize.presets.atts"] = " обвесов"
L["customize.presets.save"] = "Сохранить"
L["customize.presets.import"] = "Импорт"
L["customize.presets.new"] = "Название нового пресета"
L["customize.presets.code"] = "Код пресета (Скопирован в буфер обмена)"
L["customize.presets.paste"] = "Вставьте код пресета"
L["customize.presets.back"] = "Назад"
L["customize.presets.cancel"] = "Отмена"
L["customize.presets.dumb"] = "Ты ебнутый?"
L["customize.presets.invalid"] = "Неправильная строка!"

L["settings.gameplay.togglelean.title"] = "Наклон по нажатию"
L["settings.gameplay.togglelean.desc"] = "Вместо удерживания кнопки наклона достаточно нажать один раз."

L["settings.gameplay.togglepeek.title"] = "Выглядывание по нажатию"
L["settings.gameplay.togglepeek.desc"] = "Вместо удерживания кнопки выглядывания достаточно нажать один раз."

L["settings.npc.npc_spread.title"] = "Разброс у NPC"
L["settings.npc.npc_spread.desc"] = "Множитель неточности выстрелов ARC9 пушек у NPC."


-- Added 03-JAN-2023
L["settings.gameplay.togglelean.desc"] = "Вместо удерживания кнопки наклона достаточно нажать один раз.\n\nРаботает плохо со включенным автонаклоном. Если вы используете наклон по нажатию, отключите автонаклон."

L["settings.developer.presets_clear.title"] = "Очистить данные"
L["settings.developer.presets_clear.desc"] = "Удалить все пресеты, иконки и дефолтный пресет для оружия, что вы сейчас держете в руках.\n\nВнимание: если у вас сейчас нет ARC9 пушки в руках, это удалит всю данные всех пушек!"
L["settings.developer.clear"] = "Очистить"

L["atts.favourites"] = "Избранное"
L["atts.filter"] = "Фильтр"
L["customize.hint.favorite"] = "Добавить в избранное"
L["customize.hint.unfavorite"] = "Убрать из избранного"

L["folder.favourites"] = "Избранное"
L["customize.presets.unnamed"] = "Без названия"

-- Added 04-JAN-2023

L["settings.gameplay.never_ready.title"] = "Отключить Ready анимации"
L["settings.gameplay.never_ready.desc"] = "Никогда не проигрывать \"ready\" анимации при доставании любого оружия.\n\nЭто серверная переменная."

L["settings.performance.fx.title"] = "Эффекты"

L["settings.muzzle_light.title"] = "Динам. свет от выстрелов"
L["settings.muzzle_light.desc"] = "Включает динамический свет от вспышек выстрелов."

L["settings.muzzle_others.title"] = "Эффекты от выстрелов у игроков"
L["settings.muzzle_others.desc"] = "Включает эффекты от выстрелов от пушек у других игроков на сервере."

-- Added 07-JAN-2023
L["settings.mod_damage.title"] = "Урон"
L["settings.mod_spread.title"] = "Разброс"
L["settings.mod_recoil.title"] = "Отдача"
L["settings.mod_visualrecoil.title"] = "Физ. отдача"
L["settings.mod_adstime.title"] = "Скорость прицеливания"
L["settings.mod_sprinttime.title"] = "Возвращение после бега"
L["settings.mod_damagerand.title"] = "Вариация урона"
L["settings.mod_muzzlevelocity.title"] = "Дульная скорость"
L["settings.mod_rpm.title"] = "Скорострельность"
L["settings.mod_headshotdamage.title"] = "Урон в голову"

-- Added 08-JAN-2023
L["settings.developer.dev_greenscreen.title"] = "Зеленый экран в кастомизации"
L["settings.developer.dev_greenscreen.desc"] = "Показывает зеленый экран вместо фона в меню кастомизации для скриншотов.\n\nЕсли вы используете HDR, не забудьте поставить mat_bloom_scalefactor_scalar на 0!"

-- 10 jan
L["autostat.triggerdelay"] = "Задержка спуска курка"
L["autostat.triggerdelaytime"] = "Время задержки спуска курка"
L["settings.hud_cust.hud_darkmode.title"] = "Темная тема"
L["settings.hud_cust.hud_darkmode.desc"] = "Включает темные цвета интерфейса вместо серого и отключает виньетку у фона."
L["autostat.penetrationdelta"] = "Урон после пробития"

-- Added 29-JAN-2023

L["settings.hud_game.hud_nohints.title"] = "Отключить подсказки"
L["settings.hud_game.hud_nohints.desc"] = "Отключить подсказки вообще. Их не будет ни в 3D интерфейсе, ни в 2D."

L["settings.visuals.cambob"] = "Тряска камеры"
L["settings.visuals.vm_cambob.title"] = "Тряска при беге"
L["settings.visuals.vm_cambob.desc"] = "При беге у камеры будет тряска."
L["settings.visuals.vm_cambobwalk.title"] = "Тряска при ходьбе"
L["settings.visuals.vm_cambobwalk.desc"] = "При обычный ходьбе у камеры тоже будет тряска (требует включенной тряски при беге)"
L["settings.visuals.vm_cambobintensity.title"] = "Интенсивность"
L["settings.visuals.vm_cambobintensity.desc"] = "Насколько сильная будет тряска"