L = {}

/////////////////////////////////////// Font
////////////////////// See "font_en" file

/////////////////////////////////////// General
////////////////////// Units of measurement
L["unit.second"] = "s"
L["unit.meter"] = "m"
L["unit.millimeter"] = "mm"
L["unit.meterpersecond"] = "m/s"
L["unit.hammerunit"] = "HU"
L["unit.decibel"] = "dB"
L["unit.rpm"] = "SPM"
L["unit.moa"] = "MOA"
L["unit.dmg"] = "DMG"
L["unit.projectiles"] = "PROJ"

L["unit.inch"] = "in"
L["unit.foot"] = "ft"
L["unit.footpersecond"] = "ft/s"
L["unit.yard"] = "yd"

////////////////////// Ammo types
L["ammo.pistol"] = "Pistolen-Munition"
L["ammo.357"] = "Magnum-Munition"
L["ammo.smg1"] = "Carbine-Munition"
L["ammo.ar2"] = "Gewehr-Munition"
L["ammo.buckshot"] = "Shotgun-Munition"
L["ammo.sniperpenetratedround"] = "Sniper-Munition"
L["ammo.smg1_grenade"] = "Rifle-Granaten"
-- L["ammo.xbowbolt"] = "Crossbow Bolts"
-- L["ammo.rpg_round"] = "Rockets"
-- L["ammo.grenade"] = "Grenades"
-- L["ammo.slam"] = "SLAM"
-- L["ammo.alyxgun"] = "Alyx's Gun Ammo"

/////////////////////////////////////// HUD
L["hud.version"] = "ARCTIC SYSTEME UI v"
L["hud.jammed"] = "EINGEKLEMMT!"
L["hud.therm_deco"] = "LAUF-TEMP"

L["hud.firemode.single"] = "EINZEL"
L["hud.firemode.burst"] = "BURST"
L["hud.firemode.auto"] = "AUTO"
L["hud.firemode.safe"] = "SICHER"

L["hud.hint.bash"] = "Schlagen"
-- L["hud.hint.bipod"] = "Toggle Bipod"
L["hud.hint.breath"] = "Atem anhalten"
L["hud.hint.customize"] = "Anpassen"
L["hud.hint.cycle"] = "Repetieren"
L["hud.hint.firemode"] = "Feuermodus ändern"
L["hud.hint.inspect"] = "Inspizieren"
L["hud.hint.lean"] = "Lehnen"
L["hud.hint.peek"] = "Spähen"
L["hud.hint.reload"] = "Nachladen"
L["hud.hint.safe"] = "Sicherung"
L["hud.hint.switchsights"] = "Visierung umschalten"
L["hud.hint.toggleatts"] = "Aufsätze umschalten"
L["hud.hint.ubgl"] = "Umschalten"
-- L["hud.hint.unjam"] = "Unjam"
L["hud.hint.zoom"] = "Zoom ändern"
-- L["hud.hint.quicknade"] = "Quickthrow "

-- L["hud.hint.lowammo"] = "Low Ammo"
-- L["hud.hint.noammo"] = "No Ammo"

-- L["hud.error.missingbind"] = "No button bound to %s"
-- L["hud.error.missingbind_zoom"] = "Bind \"Suit Zoom\" in settings!"
-- L["hud.error.missingbind_context"] = "Bind \"Open Context Menu\" in settings!"

/////////////////////////////////////// Customization menu
L["customize.panel.customize"] = "ANPASSEN"
L["customize.panel.personalize"] = "PERSONALISIEREN"
L["customize.panel.stats"] = "STATS & BALLISTIK"
L["customize.panel.trivia"] = "TRIVIA"
L["customize.panel.inspect"] = "INSPIZIEREN"
L["customize.panel.presets"] = "Presets"

L["customize.stats.aimtime"] = "Zielvorrichtungs-Zeit"
L["customize.stats.ammo"] = "Munitionstyp"
L["customize.stats.armorpiercing"] = "Schutzdurchdringen"
L["customize.stats.burstdelay"] = "Burst-Verzögerung"
L["customize.stats.capacity"] = "Kapazität"
L["customize.stats.cyclic"] = "Zyklische Feuerrate"
L["customize.stats.explosive"] = "Explosivschaden"
L["customize.stats.firemodes"] = "Feuermodi"
L["customize.stats.firepower"] = "Feuerkraft"
L["customize.stats.freeaim"] = "Freiziel-Radius"
L["customize.stats.muzzlevelocity"] = "Mündungsgeschwindigkeit"
L["customize.stats.noise"] = "Schwanken-Noise"
L["customize.stats.penetration"] = "Penetration"
L["customize.stats.precision"] = "Präzision"
L["customize.stats.range"] = "Reichweite"
L["customize.stats.ricochet"] = "Abprallchance"
L["customize.stats.rof"] = "Feuerrate"
L["customize.stats.speed"] = "Bewegungsgeschwindigkeit"
L["customize.stats.sprinttofire"] = "Sprint-bis-Feuer-Zeit"
L["customize.stats.supplylimit"] = "Nachschublimit"
L["customize.stats.sway"] = "Schwanken"
L["customize.stats.triggerdelay"] = "Abzugs-Verzögerung"

L["customize.hint.attach"] = "Anhängen"
L["customize.hint.controller"] = "Controller-Modus ist an."
L["customize.hint.cursor"] = "Zeiger"
L["customize.hint.cycle"] = "Nächster Slot"
L["customize.hint.delete"] = "Entfernen"
L["customize.hint.deselect"] = "Deselektieren"
L["customize.hint.expand"] = "Erweitern"
L["customize.hint.export"] = "Exportieren"
L["customize.hint.favorite"] = "Favorisieren"
L["customize.hint.import"] = "Importieren"
L["customize.hint.install"] = "Installieren"
L["customize.hint.last"] = "Letzter Slot"
L["customize.hint.lastmode"] = "Letzter Modus"
L["customize.hint.nextmode"] = "Nächster Modus"
L["customize.hint.open"] = "Öffnen"
L["customize.hint.pan"] = "Verschieben"
L["customize.hint.quicksave"] = "Schnellspeichern"
-- L["customize.hint.randomize"] = "Attach Random"
L["customize.hint.recalculate"] = "Rekalkuliere"
L["customize.hint.recenter"] = "Zentrieren"
L["customize.hint.rotate"] = "Drehen"
L["customize.hint.save"] = "Speichern"
L["customize.hint.select"] = "Auswählen"
L["customize.hint.unattach"] = "Anhang entfernen"
L["customize.hint.unfavorite"] = "Entfavorisieren"
L["customize.hint.zoom"] = "Zoomen"

L["customize.trivia.description"] = "Beschreibung"

-- L["customize.stats.explain.firepower"] = "The damage potential at point-blank range."
-- L["customize.stats.explain.rof"] = "The weapon's rate of fire."
-- L["customize.stats.explain.cyclic"] = "The weapon's cyclic rate of fire. Ignores factors like burst delay or reload requirements."
-- L["customize.stats.explain.capacity"] = "How much ammo the gun can hold in the magazine + chamber."
-- L["customize.stats.explain.range"] = "The range at which the gun deals minimum damage."
-- L["customize.stats.explain.precision"] = "The weapon's accuracy. Measured in Minutes of Accuracy (MOA)."
-- L["customize.stats.explain.muzzlevelocity"] = "The muzzle velocity of bullets fired from this gun."
-- L["customize.stats.explain.ammo"] = "The type of ammo this gun uses."
-- L["customize.stats.explain.penetration"] = "Amount of material this gun can penetrate. Measured in millimeters of wood."
-- L["customize.stats.explain.ricochet"] = "Maximum chance for bullets from this gun to ricochet."
-- L["customize.stats.explain.armorpiercing"] = "Amount of damage from this gun that completely ignores most damage resistances."
-- L["customize.stats.explain.explosive"] = "Amount of explosive damage this gun will do."
-- L["customize.stats.explain.speed"] = "Speed at which you can move while using this gun."
-- L["customize.stats.explain.aimtime"] = "How long it takes to aim down sights from hip fire."
-- L["customize.stats.explain.sprinttofire"] = "How long it takes to exit sprint and begin shooting."
-- L["customize.stats.explain.firemodes"] = "Which fire modes this gun has access to."
-- L["customize.stats.explain.burstdelay"] = "Amount of time after firing a burst before the gun can fire again."
-- L["customize.stats.explain.triggerdelay"] = "Delay between pulling the trigger and firing a shot."
-- L["customize.stats.explain.noise"] = "How loud the gun's gunshots are."
-- L["customize.stats.explain.sway"] = "Amount of sway applied to the gun."
-- L["customize.stats.explain.freeaim"] = "Maximum free aim angle. Lower is better."
-- L["customize.stats.explain.supplylimit"] = "Amount of ammo that the gun can receive from ARC9 ammo sources."

L["customize.bench.dummy"] = "BALLISTIK-ATTRAPPEN-TEST"
L["customize.bench.effect"] = "EFFEKT AUF DISTANZ"
L["customize.bench.ballistics"] = "TERMINAL-BALLISTIK LEISTUNGS-EVALUATION"
L["customize.bench.precision"] = "MECHANISCHER PRÄZISIONSTEST"

L["folder.back"] = "Zurück"
L["folder.deselect"] = "Deselektieren"
L["folder.favorites"] = "Favoriten"
L["folder.select"] = "Auswählen"

////////////////////// Automatic stats
L["autostat.enable.pre"] = "Aktivierungen"
L["autostat.disable.pre"] = "Deaktivierungen"
L["autostat.enable.post"] = ""
L["autostat.disable.post"] = ""

L["autostat.aimdownsightstime"] = "Zielvorrichtungs-Zeit"
L["autostat.alwaysphysbullet"] = "Nutze immer Projketile"
L["autostat.ammopershot"] = "Munitionsverbrauch pro Schuss"
L["autostat.armdamage"] = "Armschaden"
L["autostat.armorpiercing"] = "Schutzdurchdringen"
L["autostat.autoburst"] = "Automatisches Burst-Feuer"
L["autostat.autoreload"] = "Automatisches Nachladen"
L["autostat.bash"] = "Nahkampfattacken"
L["autostat.bashdamage"] = "Nahkampfschaden"
L["autostat.bashlungerange"] = "Nahkampfsturz-Entfernung"
L["autostat.bashrange"] = "Nahkampfentfernung"
L["autostat.bashspeed"] = "Nahkampfgeschwindigkeit"
L["autostat.bipod"] = "Zweibein"
L["autostat.bottomlessclip"] = "Bodenloses Magazin"
L["autostat.breathholdtime"] = "Fokus-Zeit"
L["autostat.bulletguidance"] = "Gesteuerte Projektile"
L["autostat.bulletguidanceamount"] = "Steuerungsfaktor"
L["autostat.canfireunderwater"] = "Schießen unter Wasser"
-- L["autostat.cantpeek"] = "Disables Peeking"
L["autostat.chambersize"] = "Verschlussanzahl"
L["autostat.chestdamage"] = "Brustschaden"
L["autostat.clipsize"] = "Magazinkapazität"
L["autostat.cycletime"] = "Repetier-Zeit"
L["autostat.damagemax"] = "Maximalschaden"
L["autostat.damagemin"] = "Minimalschaden"
L["autostat.damagerand"] = "Damage Variance"
L["autostat.deploytime"] = "Zücke-Zeit"
L["autostat.distance"] = "Projektilentfernung"
L["autostat.entitymuzzlevelocity"] = "Projektil-Mündungsgeschwindigkeit"
L["autostat.explosiondamage"] = "Explosionsschaden"
L["autostat.explosionradius"] = "Explosionsradius"
L["autostat.fixtime"] = "Entklemm-Zeit"
L["autostat.freeaimradius"] = "Freies-Zielen-Radius"
L["autostat.headshotdamage"] = "Kopfschussschaden"
L["autostat.heatcapacity"] = "Hitzekapazität"
L["autostat.heatdissipation"] = "Hitzeverfall"
L["autostat.heatpershot"] = "Hitze pro Schuss"
L["autostat.hybridreload"] = "Hybrides Individuelles Nachladen"
L["autostat.infiniteammo"] = "Unendlich Munition"
L["autostat.legdamage"] = "Beinschaden"
L["autostat.malfunction"] = "Einklemmen"
L["autostat.malfunctionmeanshotstofail"] = "Durchs. Schüsse zwischen Fehlfunktionen"
L["autostat.malfunctionwait"] = "Fehlfunktion-Wartezeit"
L["autostat.manualaction"] = "Manuelle Bedienung"
L["autostat.manualactionchamber"] = "Schussanzahl per Repetition"
L["autostat.neverphysbullet"] = "Nutze nie Projektile"
L["autostat.noflash"] = "Kein Mündungsfeuer"
L["autostat.num"] = "Projektilanzahl"
L["autostat.overheat"] = "Überhitzen"
L["autostat.overheattime"] = "Überhitzungs-Zeit"
L["autostat.pelletspread"] = "Kügelchenstreuung"
L["autostat.penetration"] = "Materialpenetration"
-- L["autostat.penetrationdelta"] = "Damage After Penetration"
L["autostat.physbulletdrag"] = "Projektilverzug"
L["autostat.physbulletgravity"] = "Projektilschwerkraft"
L["autostat.physbulletmuzzlevelocity"] = "Mündungsgeschwindigkeit"
L["autostat.postburstdelay"] = "Burst-Verzögerung"
L["autostat.pushbackforce"] = "Pushback-Kraft"
L["autostat.rangemax"] = "Maximale Reichweite"
L["autostat.rangemin"] = "Minimale Schadenreichweite"
L["autostat.recoil"] = "Rückstoß"
L["autostat.recoilautocontrol"] = "Rückstoßkontrolle"
L["autostat.recoildissipationrate"] = "Rückstoß-Ausschweifungsrate"
L["autostat.recoilkick"] = "Gefühlter Rückstoß"
-- L["autostat.recoilmodifiercap"] = "Maximum Cumulative Recoil"
L["autostat.recoilpatterndrift"] = "Rückstoß-Drift"
-- L["autostat.recoilpershot"] = "Recoil per Shot"
L["autostat.recoilrandomside"] = "Horizontaler Rückstoß-Streuung"
L["autostat.recoilrandomup"] = "Vertikaler Rückstoß-Streuung"
L["autostat.recoilresettime"] = "Rückstoß-Resetzeit"
L["autostat.recoilside"] = "Horizontaler Rückstoß"
L["autostat.recoilup"] = "Vertikaler Rückstoß"
L["autostat.reloadtime"] = "Nachlade-Zeit"
L["autostat.ricochetanglemax"] = "Abprallwinkel"
L["autostat.ricochetchance"] = "Abprallwahrscheinlichkeit"
L["autostat.rpm"] = "Feuerrate"
L["autostat.runawayburst"] = "Runaway-Burst"
L["autostat.secondarysupplylimit"] = "Reserve-Sekundärmunition"
L["autostat.shootvolume"] = "Report-Volumen"
L["autostat.shootwhilesprint"] = "Schießen während Sprint"
L["autostat.shotgunreload"] = "Individuelles Nachladen"
L["autostat.speed"] = "Bewegungsgeschwindigkeit"
L["autostat.spread"] = "Streuung"
L["autostat.sprinttofiretime"] = "Sprint-bis-Feuer-Zeit"
L["autostat.stomachdamage"] = "Bauchschaden"
L["autostat.supplylimit"] = "Reserve-Magazine"
L["autostat.sway"] = "Schwanken"
L["autostat.triggerdelay"] = "Abzugsverzögerung"
-- L["autostat.triggerdelaytime"] = "Trigger Delay Time"
L["autostat.visualrecoil"] = "Visueller Rückstoß"
L["autostat.visualrecoilpunch"] = "Visueller Rückstoß-Schlag"
L["autostat.visualrecoilroll"] = "Visuelle Rückstoß-Drehung"
L["autostat.visualrecoilside"] = "Horizontaler Visueller Rückstoß"
L["autostat.visualrecoilup"] = "Vertikaler Visueller Rückstoß"

L["autostat.secondary._beforephrase"] = false
-- if true, secondary stat phrasing comes before the stat
L["autostat.secondary._divider"] = " "
-- space between the secondary phrase from the stat phrase. set true to use empty string

-- L["autostat.secondary.blindfire"] = "while Blind-Firing"
-- L["autostat.secondary.bipod"] = "on Bipod"
L["autostat.secondary.crouch"] = "während des Kriechen"
L["autostat.secondary.empty"] = "beim letzen Schuss im Magazin"
L["autostat.secondary.evenreload"] = "jeden geraden Reload"
L["autostat.secondary.evenshot"] = "jeden geraden Schuss"
L["autostat.secondary.first"] = "beim letzen Schuss"
L["autostat.secondary.firstshot"] = "beim ersten Schuss"
-- L["autostat.secondary.heated"] = "while Heated"
L["autostat.secondary.hipfire"] = "im Hüftfeuer"
-- L["autostat.secondary.hot"] = "from Heat"
L["autostat.secondary.last"] = "beim letzen Schuss im Magazin"
L["autostat.secondary.lastshot"] = "beim letzen Schuss im Magazin"
L["autostat.secondary.midair"] = "in der Luft"
L["autostat.secondary.move"] = "während Bewegung"
L["autostat.secondary.oddreload"] = "jeden ungeraden Reload"
L["autostat.secondary.oddshot"] = "jeden ungeraden Schuss"
L["autostat.secondary.recoil"] = "vom Rückstoß" --"With Each Shot"
L["autostat.secondary.shooting"] = "während des Schießens"
-- L["autostat.secondary.sighted"] = "while Sighted"
L["autostat.secondary.sights"] = "im Visier"
L["autostat.secondary.silenced"] = "wenn Schallgedämpft"
L["autostat.secondary.sprint"] = "während Sprint"
L["autostat.secondary.true"] = "wenn TrueNames an ist"
L["autostat.secondary.ubgl"] = "im UBGL"

////////////////////// Blacklist menu
-- L["blacklist.title"] = "ARC9 Attachment Blacklist"
-- L["blacklist.desc"] = "Attachments checked here will be blocked from use"
-- L["blacklist.blisted"] = "BLACKLISTED"
-- L["blacklist.all"] = "ALL"
-- L["blacklist.id"] = "ID"
-- L["blacklist.name"] = "NAME"
-- L["blacklist.filter"] = "FILTER"

////////////////////// Incompatible addons
L["incompatible.title"] = "ARC9: INKOMPATIBLE ADDONS"
L["incompatible.line1"] = "Wenn du Add-Ons hast, die mit ARC9 nicht funktionieren, dann"
L["incompatible.line2"] = "deaktiviere sie oder erwarte fehlerhaftes Verhalten!"
L["incompatible.confirm"] = "Bestätige"
L["incompatible.wait"] = "Warte {time}s"
L["incompatible.never"] = "Warne mich nicht erneut"
L["incompatible.never.hover"] = "Bist du dir absolut sicher, dass du die Auswirkungen verstehst?"
L["incompatible.never.confirm"] = "Du hast Inkompatibilitätswarnungen ausgeschaltet; Wenn etwas schiefläuft, ist das deine eigene Schuld."

////////////////////// Presets
L["customize.presets.atts"] = " Aufsätze"
L["customize.presets.back"] = "Zurück"
L["customize.presets.cancel"] = "Abbrechen"
L["customize.presets.code"] = "Preset-Code (In der Zwischenablage)"
L["customize.presets.default"] = "Standard"
L["customize.presets.default.long"] = "Standard-Preset"
L["customize.presets.dumb"] = "Bist du dumm"
L["customize.presets.import"] = "Import"
L["customize.presets.invalid"] = "Ungültiger String!"
L["customize.presets.new"] = "Neuer Preset-Name"
L["customize.presets.paste"] = "Preset-Code hier einfügen"
L["customize.presets.random"] = "Zufall"
L["customize.presets.save"] = "Speichern"
L["customize.presets.unnamed"] = "Unbenannt"
-- L["customize.presets.deldef"] = "Are you sure you want to delete \"{name}\" default preset?"´
-- L["customize.presets.deldef2"] = "You would have to reset weapon in developer settings to return it."
L["customize.presets.yes"] = "Ja"

////////////////////// Tips
-- L["tips.arc-9"] = "It's ARC9, not ARC-9, not Arc9."
-- L["tips.blacklist"] = "You can blacklist attachments! See the ARC9 Workshop description for more information."
-- L["tips.bugs"] = "Report bugs on the official Discord server, or better yet, open a Github issue."
-- L["tips.custombinds"] = "ARC9 key combos can be replaced with custom binds. Start typing +arc9_ to find the available binds!"
-- L["tips.cyberdemon"] = "To kill the terrorist, shoot him until he is dead."
-- L["tips.description"] = "We advise you to read the descriptions of addons before commenting."
-- L["tips.development"] = "Keen to develop ARC9 content? The official Discord server has plenty of resources to help!"
-- L["tips.discord"] = "Join Diamond Doves on Discord! The link is in the ARC9 description and in top of settings."
-- L["tips.external"] = "If using the Github version of ARC9, make sure to update frequently!"
-- L["tips.hints"] = "Keep ARC9's HUD on to see control hints."
-- L["tips.lean"] = "To manually lean, bind keys to +alt1 and +alt2."
-- L["tips.love"] = "Feel free to tell the devs you appreciate their work! It really helps us keep going."
-- L["tips.m9k"] = "Check out M9K guns!."
-- L["tips.official"] = "Only download ARC9 from official sources. Third party uploads may be malicious or outdated!"
-- L["tips.presets"] = "Share your favorite presets with your friends by exporting them!"
-- L["tips.settings"] = "You can turn these tips off, and much more, in the ARC9 settings. Click the button in the top left corner!"
-- L["tips.tacrp"] = "Have you tried Tactical RP base yet?"
-- L["tips.tips"] = "Tips have a fixed order. Keep reading and you'll eventually see them all."
-- L["tips.tolerance"] = "All weapon bases work fine together. There's no need for favoritism."

////////////////////// Other
L["atts.favourites"] = "Favoriten"
L["atts.filter"] = "Filter"

/////////////////////////////////////// Settings menu
-- Use this method to localize convars in settings menu:
-- settings.convar.title = "Convar Title"
-- settings.convar.desc = "Convar Description"

L["settings.title"] = "ARC9 Einstellungen"
L["settings.desc"] = "Beschreibung"

-- L["settings.default_convar"] = "Default value"
-- L["settings.convar_server"] = "Server variable"
-- L["settings.convar_client"] = "Client variable"

////////////////////// General
-- L["settings.tabname.general"] = "General"

-- L["settings.general.client"] = "Client"
L["settings.language_id.title"] = "Sprache"
L["settings.language_id.desc"] = "Sprachpaket für ARC9."
-- L["settings.truenames.title"] = "True Names"
-- L["settings.truenames.desc"] = "Set whether to use weapons' real names or fictional names made by the developers. Not all weapons utilize this."
-- L["settings.resetsettings.cl.title"] = "Reset all CLIENT settings"

-- L["settings.general.server"] = "Server"
-- L["settings.truenames_default.title"] = "Default True Names"
-- L["settings.truenames_default.desc"] = "Set the default true names mode on the server. All players using \"Default\" in preference will use this."
-- L["settings.truenames_enforced.title"] = "Default True Names Enforced"
-- L["settings.truenames_enforced.desc"] = "Set to force all players to use the server setting for true names."

-- L["settings.resetsettings.sv.title"] = "Reset all SERVER settings"

-- L["settings.reset"] = "Reset!"

////////////////////// Performance
L["settings.tabname.performance"] = "Leistung"

L["settings.performance.important"] = "Wichtig"
L["settings.cheapscopes.title"] = "Billige Visiere"
L["settings.cheapscopes.desc"] = "Eine billige Visier-Implementation die deine gesamte Sicht reinzoomt, anstatt die Welt im Visier erneut zu rendern. Verbessert Leistung sehr stark auf großen Maps."
L["settings.tpik.title"] = "TPIK"
L["settings.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) ist ein System, mit dem Waffen die gleichen Nachlade- und Feueranimationen in 3.Person und 1.Person haben können.\n\nKonfiguriere es im Visuals-Reiter."
L["settings.allflash.title"] = "Alle Taschenlampen"
L["settings.allflash.desc"] = "Rendere alle Taschenlampen von anderen Spielern\n\nSehr leistungsintensiv auf Servern."

L["settings.performance.blur.title"] = "Verschwemmen"
L["settings.cust_blur.title"] = "Anpassungs-Hintergrund"
L["settings.cust_blur.desc"] = "Verschwemmt den Anpassungs-Hintergrund."
L["settings.fx_reloadblur.title"] = "Beim Nachladen"
L["settings.fx_reloadblur.desc"] = "Verschwemmt die Welt beim Nachladen."
L["settings.fx_animblur.title"] = "Beim Zücken"
L["settings.fx_animblur.desc"] = "Verschwemmt die Welt beim ersten Einsatz einer Waffe."
L["settings.fx_rtblur.title"] = "In Visieren"
L["settings.fx_rtblur.desc"] = "Verschwemmt die Welt beim Einsatz eines Zielvisiers."
L["settings.fx_adsblur.title"] = "In Zielvorrichtung"
L["settings.fx_adsblur.desc"] = "Verschwemmt die Welt beim Zielen."
-- L["settings.fx_rtvm.title"] = "Render Weapon through RT Scopes"
-- L["settings.fx_rtvm.desc"] = "! EXPERIMENTAL !\nRenders the weapon and its attachments through RT scopes. Requires \"Cheap Scopes\" to be disabled.\nSignificantly reduces performance."

L["settings.performance.shelleject.title"] = "Hülsenauswurf"
L["settings.eject_fx.title"] = "Raucheffekte"
L["settings.eject_fx.desc"] = "Erzeuge Raucheffekte aus ausgeworfenen Patronenhülsen, sofern die Waffe diese Funktion unterstützt."
L["settings.eject_time.title"] = "Mehr Lebenszeit"
L["settings.eject_time.desc"] = "Lass Patronenhülsen länger in der Welt bleiben. Kann Leistungsintensiv werden."

L["settings.performance.fx.title"] = "Effekte"
L["settings.muzzle_light.title"] = "Mündungs-Leuchten"
L["settings.muzzle_light.desc"] = "Aktiviere das Aufleuchten des Mündungsfeuers beim Feuern einer Waffe."
L["settings.muzzle_others.title"] = "Andere Mündungs-Einstellungen"
L["settings.muzzle_others.desc"] = "Aktiviere Mündungs-Effekte für Waffen von anderen Spielern."

////////////////////// Optics
L["settings.tabname.optics"] = "Optiken"

L["settings.optics.control"] = "Steuerung"
-- L["settings.optics.sensmult.title"] = "Multiply ADS Sensitivity"
-- L["settings.optics.sensmult.desc"] = "Multiply the look sensitivity by this amount when aiming.\nThe lower the value, the lower the sensitivity.\nUseful when using controllers, or if the user just wants lower aiming sensitivity."
L["settings.optics.compensate_sens.title"] = "Kompensierungs-Sensitivität"
L["settings.optics.compensate_sens.desc"] = "Kompensierungs-Sensitivität für Vergrößerung."
L["settings.optics.toggleads.title"] = "Zielvorr. umschalten"
L["settings.optics.toggleads.desc"] = "Zielen wird die Visierung umschalten."

-- L["settings.optics.dtap_sights.title"] = "Double-Tap to Switch Sights"
-- L["settings.optics.dtap_sights.desc"] = "Allows double-tapping the USE key to switch sights."

L["settings.optics.color"] = "Farbe"
L["settings.optics.reflex.title"] = "Reflexvisiere"
L["settings.optics.reflex.desc"] = "Farbe für Reflex- oder Holovisiere.\n\nNicht all Visiere unterstützen dieses Feature."
L["settings.optics.scope.title"] = "Visiere"
L["settings.optics.scope.desc"] = "Farbe für Visiere.\n\nNicht all Visiere unterstützen dieses Feature."

////////////////////// Crosshair
L["settings.tabname.crosshair"] = "Fadenkreuz"

L["settings.crosshair.crosshair"] = "Fadenkreuz"
L["settings.crosshair.cross_enable.title"] = "Aktiviere Fadenkreuz"
L["settings.crosshair.cross_enable.desc"] = "Aktiviere Fadenkreuz. Manche Waffen erlauben es nicht, das Fadenkreuz zu aktivieren."
L["settings.crosshair.cross.title"] = "Fadenkreuz-Farbe"
L["settings.crosshair.cross.desc"] = "Die Farbe deines Fadenkreuzes."
L["settings.crosshair.cross_size_mult.title"] = "Fadenkreuz-Größe"
L["settings.crosshair.cross_size_mult.desc"] = "Multiply the size of your crosshair."
L["settings.crosshair.cross_size_dot.title"] = "Punkt-Größe"
L["settings.crosshair.cross_size_dot.desc"] = "Multipliziere die Größe des mittleren Punktes."
L["settings.crosshair.cross_size_prong.title"] = "Zacken-Größe"
L["settings.crosshair.cross_size_prong.desc"] = "Multipliziere die Größe der äußeren Zacken."
L["settings.crosshair.crosshair_static.title"] = "Festes Fadenkreuz"
L["settings.crosshair.crosshair_static.desc"] = "Aktiviert ein festes Fadenkreuz, welches sich nicht beim Feuern bewegt."
L["settings.crosshair.crosshair_force.title"] = "Fadenkreuz erzwingen"
L["settings.crosshair.crosshair_force.desc"] = "Erzwinge das Fadenkreuz auch bei Waffen, die nicht möchten, dass du es siehst.\n\nServereinstellung."
-- L["settings.crosshair.crosshair_target.title"] = "Red Crosshair on Target"
-- L["settings.crosshair.crosshair_target.desc"] = "Make the crosshair red when aiming on a target.\nAlso activates aim assist if it is turned on."
-- L["settings.crosshair.crosshair_peeking.title"] = "Display Crosshair when Peeking"
-- L["settings.crosshair.crosshair_peeking.desc"] = "Displays the crosshair when aiming and using the peek function."

////////////////////// Customization
L["settings.tabname.hud_cust"] = "Anpassung"

L["settings.hud_cust.hud"] = "HUD"
L["settings.hud_cust.hud_scale.title"] = "UI-Skalierung"
L["settings.hud_cust.hud_scale.desc"] = "Skalierungsmultiplikator für die Oberfläche von ARC9."
-- L["settings.hud_cust.hud_deadzonex.title"] = "HUD Width Deadzone"
-- L["settings.hud_cust.hud_deadzonex.desc"] = "Horizontal \"deadzone\" for customization menu and HUD panel.\nUseful for ultrawide monitors."
L["settings.hud_cust.hud_color.title"] = "UI-Farbe"
L["settings.hud_cust.hud_color.desc"] = "Hervorhebungsfarbe für das HUD.\nDie Akzentfarbe."
-- L["settings.hud_cust.hud_holiday.title"] = "Holiday Themes"
-- L["settings.hud_cust.hud_holiday.desc"] = "Themes that activate during certain holidays.\nWill override highlight color"
-- L["settings.hud_cust.hud_darkmode.title"] = "Dark Theme"
-- L["settings.hud_cust.hud_darkmode.desc"] = "Enables dark colors in HUD instead of light gray and disables vignette effect in background."
L["settings.hud_cust.cust_light.title"] = "Licht akt."
L["settings.hud_cust.cust_light.desc"] = "Aktiviert die Waffenbeleuchtung im Anpassungsmenü.\n\nDasselbe wie der Knopf neben dem Einstellungs-Button."
L["settings.hud_cust.cust_light_brightness.title"] = "Helligkeit"
L["settings.hud_cust.cust_light_brightness.desc"] = "Wie hell das Licht im Anpassungsfeld sein wird.\n\nVergiss aber nicht, es zuerst einzuschalten!"

L["settings.hud_cust.customization"] = "Anpassung"
L["settings.hud_cust.cust_hints.title"] = "Hinweise"
L["settings.hud_cust.cust_hints.desc"] = "Aktiviere Hinweise im Anpassungsmenü."
-- L["settings.hud_cust.cust_tips.title"] = "Tips"
-- L["settings.hud_cust.cust_tips.desc"] = "Tips about ARC9 base near hints."
L["settings.hud_cust.cust_exit_reset_sel.title"] = "Verlassen setzt Auswahl zurück"
L["settings.hud_cust.cust_exit_reset_sel.desc"] = "Das Verlassen des Anpassungsmenüs setzt die Auswahl des aktiven Slots zurück."
-- L["settings.hud_cust.imperial.title"] = "Imperial Measurement"
-- L["settings.hud_cust.imperial.desc"] = "Replaces various measurement systems to their Imperial variants.\nOnly affects the \"Stats & Ballistics\" customization screen."

////////////////////// Game HUD
L["settings.tabname.hud_game"] = "Spieloberfläche"

L["settings.hud_game.lcd"] = "LCD-Panel"
L["settings.hud_game.hud_arc9.title"] = "HUD aktivieren"
L["settings.hud_game.hud_arc9.desc"] = "HUD für ARC9-Waffen aktivieren."
L["settings.hud_game.hud_always.title"] = "Auf allen Waffen"
L["settings.hud_game.hud_always.desc"] = "Aktiviere das HUD bei allen Waffen."
L["settings.hud_game.hud_compact.title"] = "Kompaktmodus"
L["settings.hud_game.hud_compact.desc"] = "Kompaktes Erscheinungsbild für das HUD-Panel."
-- L["settings.hud_game.hud_nohints.title"] = "Disable Hints"
-- L["settings.hud_game.hud_nohints.desc"] = "Disable hints completely. They will not show up in the 3D HUD, nor in the 2D HUD."
L["settings.hud_game.hud_keephints.title"] = "Hinweise behalten"
L["settings.hud_game.hud_keephints.desc"] = "Zeige die ARC9-Steuerungshinweise oben auf dem HUD-Panel."
-- L["settings.hud_game.hud_force_disable.title"] = "Force Disable HUD"
-- L["settings.hud_game.hud_force_disable.desc"] = "Disable ARC9 HUD for all players. Does not affect hints."

L["settings.hud_game.killfeed"] = "Killfeed"
L["settings.hud_game.killfeed_enable.title"] = "Killfeed-Symbole"
L["settings.hud_game.killfeed_enable.desc"] = "Automatische Generierung von Killfeed-Symbolen für ARC9-Waffen aktivieren."
L["settings.hud_game.killfeed_dynamic.title"] = "Dynamische Aktualisierung"
L["settings.hud_game.killfeed_dynamic.desc"] = "Killfeed-Symbole werden nach jedem Kill neu generiert.\n\nDeaktiviere dies, wenn du 0,1 FPS mehr haben willst."
-- L["settings.hud_game.killfeed_colour.title"] = "Full Color Icons"
-- L["settings.hud_game.killfeed_colour.desc"] = "Dynamically generated icons are fully colored."

L["settings.hud_game.breath"] = "Atmen"
L["settings.hud_game.breath_hud.title"] = "Atem-HUD"
L["settings.hud_game.breath_hud.desc"] = "Zeige einen Balken, der dir verbleibenden Atem anzeigt, während du deine Waffe im Visier stabilisierst."
L["settings.hud_game.breath_pp.title"] = "Atem-Post-Process"
L["settings.hud_game.breath_pp.desc"] = "Beim Anhalten vom Atem werden Post-Processing-Effekte abgespielt."
L["settings.hud_game.breath_sfx.title"] = "Atem-Effekte"
L["settings.hud_game.breath_sfx.desc"] = "Wenn du den Atem anhälst, werden die zugehörigen Soundeffekte abgespielt."

-- L["settings.hud_game.centerhint"] = "Tooltips"
-- L["settings.hud_game.centerhint_reload.title"] = "Display Reload Tip"
-- L["settings.hud_game.centerhint_reload.desc"] = "Display a reload tip when low on ammunition."
-- L["settings.hud_game.centerhint_reload_percent.title"] = "Magazine Percentage"
-- L["settings.hud_game.centerhint_reload_percent.desc"] = "Display the reload tip when the current magazine is at this percentage value."
-- L["settings.hud_game.centerhint_bipod.title"] = "Display Toggle Bipod"
-- L["settings.hud_game.centerhint_bipod.desc"] = "Display a tip when the bipod can be toggled."
-- L["settings.hud_game.centerhint_jammed.title"] = "Display Jammed Tip"
-- L["settings.hud_game.centerhint_jammed.desc"] = "Display a tip when your weapon is jammed."

-- L["settings.hud_game.centerhint_firemode.title"] = "Display Firemode Tip"
-- L["settings.hud_game.centerhint_firemode.desc"] = "Display a tip when you swap firing mode or toggle your safety."
-- L["settings.hud_game.centerhint_firemode_time.title"] = "Display Firemode Time"
-- L["settings.hud_game.centerhint_firemode_time.desc"] = "How long the firing mode should be displayed."

-- L["settings.hud_game.centerhint_overheat.title"] = "Display Overheat Tip"
-- L["settings.hud_game.centerhint_overheat.desc"] = "Displays an overlayed tip showing how close the weapon is to overheating.\n\nNot displayed if ARC9 HUD is enabled or the weapon does not support overheat."

-- L["settings.hud_game.hud_glyph"] = "Glyph Type"

-- L["settings.hud_game.hud_glyph_type_hud.title"] = "HUD"
-- L["settings.hud_game.hud_glyph_type_hud.desc"] = "Change which family of glyphs to use.\nThis affects the HUD tips."

-- L["settings.hud_game.hud_glyph_type_cust.title"] = "Customization Menu"
-- L["settings.hud_game.hud_glyph_type_cust.desc"] = "Change which family of glyphs to use.\nThis affects the customization menu tips.\nChanges apply next time the customization menu is opened."

-- L["settings.hud_game.hud_glyph_light"] = "Light"
-- L["settings.hud_game.hud_glyph_dark"] = "Dark"
-- L["settings.hud_game.hud_glyph_knockout"] = "Knockout"

////////////////////// NPCs
L["settings.tabname.npc"] = "NPCs"

L["settings.npc.weapons"] = "NPC-Waffen"
L["settings.npc.npc_equality.title"] = "Schadensgleichheit"
L["settings.npc.npc_equality.desc"] = "NPCs richten genauso viel Schaden an wie Spieler.\n\nDies ist eine Server-Variable."
L["settings.npc.npc_spread.title"] = "NPC-Streuung"
L["settings.npc.npc_spread.desc"] = "Multiplikator für wie ungenau NPCs beim Feuern sein sollen."
L["settings.npc.npc_atts.title"] = "Anhänge geben"
L["settings.npc.npc_atts.desc"] = "Gespawnte oder gegebene ARC9-Waffen erhalten einen zufälligen Satz von Anhängen.\n\nDies ist eine Server-Variable."
L["settings.npc.npc_autoreplace.title"] = "NPC-Waffen ersetzen"
L["settings.npc.npc_autoreplace.desc"] = "NPC-Waffen werden durch zufällig ausgewählte ARC9-Waffen ersetzt.\n\nDies ist eine Server-Variable."
L["settings.npc.replace_spawned.title"] = "Bodenwaffen ersetzen"
L["settings.npc.replace_spawned.desc"] = "Map- oder manuell gespawnte HL2-Waffen werden durch zufällig ausgewählte ARC9-Waffen ersetzt.\n\nDies ist eine Server-Variable."
L["settings.npc.npc_give_weapons.title"] = "Spieler können Waffen geben"
L["settings.npc.npc_give_weapons.desc"] = "Spieler können bei NPCs E drücken, um ihnen ihre Waffe zu geben.\n\nDies ist eine Server-Variable."

////////////////////// Gameplay
L["settings.tabname.gameplay"] = "Gameplay"

L["settings.gameplay.controls"] = "Steuerung"
L["settings.gameplay.toggleads.title"] = "ADS umschalten"
L["settings.gameplay.toggleads.desc"] = "Durch das Zielen wird das Visier umgeschaltet."
L["settings.gameplay.autolean.title"] = "Automatisches Lehnen"
L["settings.gameplay.autolean.desc"] = "Beim Zielen wird versuchen, sich automatisch zu lehnen, wenn dies möglich ist."
L["settings.gameplay.autoreload.title"] = "Automatisches Nachladen"
L["settings.gameplay.autoreload.desc"] = "Leere ARC9-Waffen werden automatisch nachgeladen."
L["settings.gameplay.togglelean.title"] = "Lehnen umschalten"
L["settings.gameplay.togglelean.desc"] = "Das Drücken der Lehnen-Tasten schaltet die Lehn-Richtung um, anstatt gedrückt gehalten werden zu müssen.\n\nFunktioniert nicht perfekt zusammen mit Auto-Lehnen. Du solltest Auto-Lehnen deaktivieren, solange du \"Lehnen umschalten\" benutzt."
L["settings.gameplay.togglepeek.title"] = "Spähen umschalten"
L["settings.gameplay.togglepeek.desc"] = "Das Drücken der Spähen-Taste schaltet das Spähen um, anstatt gedrückt gehalten werden zu müssen."
-- L["settings.gameplay.togglepeek_reset.title"] = "Reset Peek State After Aiming"
-- L["settings.gameplay.togglepeek_reset.desc"] = "(Only if Toggle Peek is on)\nPeek state will not be retained when exiting aim down sights."
-- L["settings.gameplay.togglebreath.title"] = "Toggle Holding Breath"
-- L["settings.gameplay.togglebreath.desc"] = "Pressing the Holding Breath key will toggle Holding Breath instead of needing to be held down."

L["settings.gameplay.mechanics"] = "Spielemechaniken"
L["settings.gameplay.infinite_ammo.title"] = "Unbegrenzte Munition"
L["settings.gameplay.infinite_ammo.desc"] = "Waffen haben unendlich Munition.\n\nDies ist eine Server-Variable."
L["settings.gameplay.realrecoil.title"] = "Physischer visueller Rückstoß"
L["settings.gameplay.realrecoil.desc"] = "Ausgewählte Waffen, die für diese Funktion eingerichtet wurden, erfahren einen physischen Mündungsanstieg, was bedeutet,\ndass sie dorthin feuern, wo das Viewmodel hin zeigt, und nicht in die Mitte des Bildschirms. Sehr wichtig für das Balancing einiger Waffenpakete.\n\nDies ist eine Server-Variable."
L["settings.gameplay.lean.title"] = "Lehnen"
L["settings.gameplay.lean.desc"] = "Ob Spieler mit +alt1 und +alt2 lehnen können, inklusive automatischem Lehnen.\n\nDies ist eine Server-Variable."
L["settings.gameplay.mod_sway.title"] = "Schwanken"
L["settings.gameplay.mod_sway.desc"] = "Waffen schwanken, wenn sie dafür eingerichtet sind.\n\nDies ist eine Server-Variable."
L["settings.gameplay.mod_freeaim.title"] = "Freies Zielen"
L["settings.gameplay.mod_freeaim.desc"] = "Waffen können frei zielen und schießen nicht immer in die Mitte des Bildschirms.\n\nDies ist eine Server-Variable."
L["settings.gameplay.mod_bodydamagecancel.title"] = "Körperschaden ignorieren"
L["settings.gameplay.mod_bodydamagecancel.desc"] = "ARC9-Körperschadensmultiplikator ignorieren. Nur deaktivieren, wenn ein anderer Mod verwendet wird, der diese Art von Funktionalität bietet.\nz.B. Mods, die die Standard-Gliedmaßen-Multiplikatoren ändern.\n\nDies ist eine Server-Variable."
L["settings.gameplay.breath_slowmo.title"] = "Slow-Mo-Atem"
L["settings.gameplay.breath_slowmo.desc"] = "Atem anhalten verlangsamt die Zeit.\n\nNur Einzelspieler."
L["settings.gameplay.manualbolt.title"] = "Manuelles Repetieren"
L["settings.gameplay.manualbolt.desc"] = "Repetierwaffen, die für diese Funktion konfiguriert sind, schießen nur, wenn R gedrückt wird, und nicht, wenn die Angriffstaste losgelassen wird."
L["settings.gameplay.never_ready.title"] = "Keine \"Ready\"-Animationen."
L["settings.gameplay.never_ready.desc"] = "Deaktiviere \"Ready\"-Animationen beim zücken einer Waffe."
-- L["settings.gameplay.recoilshake.title"] = "Recoil FOV Shake"
-- L["settings.gameplay.recoilshake.desc"] = "Snaps field of view when shooting"
-- L["settings.gameplay.equipment_generate_ammo.title"] = "Unique Ammo Types for Equipment"
-- L["settings.gameplay.equipment_generate_ammo.desc"] = "There is a limit of 255 ammo types, and disabling this option may help fix some problems if you have lots of addons.\n\nThis is a server variable.\n\nRequires restart."

-- ??
-- L["settings.gameplay.mult_defaultammo.title"] = "Default Reserve Ammo"
-- L["settings.gameplay.mult_defaultammo.desc"] = "How many magazines/grenades/equipment give to player when he takes weapon for first time?\n\nThis is a server variable."
L["settings.gameplay.nearwall.title"] = "Wandnähe"
L["settings.gameplay.nearwall.desc"] = "Schießen verbieten, wenn du zu nahe an einer Wand oder einem Hindernis stehst."

////////////////////// Visuals
L["settings.tabname.visuals"] = "Visuals"

L["settings.visuals.viewmodel"] = "Viewmodel"
L["settings.visuals.vm_bobstyle.title"] = "Bob-Stil"
L["settings.visuals.vm_bobstyle.desc"] = "Wähle zwischen verschiedenen Bob-Stilen aus, je nach Geschmack verschiedener Mitglieder des ARC9-Teams (und Valve)."
L["settings.visuals.fov.title"] = "FOV"
L["settings.visuals.fov.desc"] = "Viewmodel-FOV verändern. Vergrößert oder verkleinert das Viewmodel. Verwende diese Einstellung verantwortungsbewusst!"
L["settings.visuals.vm_addx.title"] = "X hinzufügen"
L["settings.visuals.vm_addx.desc"] = "Verschiebe das Viewmodel nach rechts oder links."
L["settings.visuals.vm_addy.title"] = "Y hinzufügen"
L["settings.visuals.vm_addy.desc"] = "Verschiebe das Viewmodel vorwärts und rückwärts."
L["settings.visuals.vm_addz.title"] = "Z hinzufügen"
L["settings.visuals.vm_addz.desc"] = "Verschiebe das Viewmodel nach oben und unten."
L["settings.visuals.vm_hipsway.title"] = "Hüftschwungmultiplikator"
L["settings.visuals.vm_hipsway.desc"] = "Ändert die Stärke des Auf- und Abschwingens beim Schießen aus der Hüfte."
L["settings.visuals.vm_adssway.title"] = "ADS-Schwungmultiplikator"
L["settings.visuals.vm_adssway.desc"] = "Ändert die Stärke des Auf- und Abschwingens beim Zielen über das Visier."
L["settings.visuals.vm_airsway.title"] = "Schwungmultiplikator in der Luft"
L["settings.visuals.vm_airsway.desc"] = "Ändert die Stärke des Auf- und Abschwingens in der Luft."

-- L["settings.visuals.cambob"] = "View Bobbing"
-- L["settings.visuals.vm_cambob.title"] = "Sprint View Bobbing"
-- L["settings.visuals.vm_cambob.desc"] = "Makes your camera move when you sprinting"
-- L["settings.visuals.vm_cambobwalk.title"] = "Walk View Bobbing"
-- L["settings.visuals.vm_cambobwalk.desc"] = "Makes your camera slightly move when you walking around (requires sprint bobbing)"
-- L["settings.visuals.vm_cambobintensity.title"] = "Intensity"
-- L["settings.visuals.vm_cambobintensity.desc"] = "How intense bobbing will be"

L["settings.visuals.tpik"] = "TPIK"
L["settings.visuals.tpik.title"] = "TPIK aktivieren"
L["settings.visuals.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) ist ein System, das es den meisten Waffen ermöglicht, Nachlade- und Feueranimationen aus der Ego-Perspektive in der Third-Person-Perspektive zu zeigen."
L["settings.visuals.tpik_others.title"] = "TPIK für andere Spieler"
L["settings.visuals.tpik_others.desc"] = "TPIK für andere Spieler als dich selbst anzeigen. Beeinflusst die Leistung negativ."
L["settings.visuals.tpik_framerate.title"] = "TPIK-Framerate"
L["settings.visuals.tpik_framerate.desc"] = "Maximale Framerate, mit der TPIK ausgeführt werden kann. Für unbegrenzt auf 0 setzen."

////////////////////// Bullet Physics
L["settings.tabname.bullets"] = "Projektil-Physik"

L["settings.bullets.bullets"] = "Projektilphysik"
L["settings.bullets.bullet_physics.title"] = "Projektile"
L["settings.bullets.bullet_physics.desc"] = "Waffen, die diese Funktion unterstützen, feuern physische Kugeln ab, die Fall, Dauer und Widerstand haben.\n\nDies ist eine Server-Variable."
L["settings.bullets.bullet_gravity.title"] = "Schwerkraft"
L["settings.bullets.bullet_gravity.desc"] = "Multiplikator für die Schwerkraft des Projektil.\n\nDies ist eine Server-Variable."
L["settings.bullets.bullet_drag.title"] = "Widerstand"
L["settings.bullets.bullet_drag.desc"] = "Multiplikator für Projektilwiderstand.\n\nDies ist eine Server-Variable."
L["settings.bullets.ricochet.title"] = "Abprall"
L["settings.bullets.ricochet.desc"] = "Kugeln, die von ausgewählten Waffen abgefeuert werden, können manchmal von Oberflächen abprallen und weiterfliegen und Schaden anrichten.\n\nDies ist eine Server-Variable."
L["settings.bullets.mod_penetration.title"] = "Penetration"
L["settings.bullets.mod_penetration.desc"] = "Von ausgewählten Waffen abgefeuerte Kugeln können Oberflächen durchdringen und allem, was sich auf der anderen Seite befindet, Schaden zufügen.\n\nDies ist eine Server-Variable."
L["settings.bullets.bullet_lifetime.title"] = "Lebensdauer"
L["settings.bullets.bullet_lifetime.desc"] = "Zeit in Sekunden, nach der ein Projektil gelöscht wird.\n\nDies ist eine Server-Variable."
L["settings.bullets.bullet_imaginary.title"] = "Imaginäre Projektile"
L["settings.bullets.bullet_imaginary.desc"] = "Kugeln scheinen in die Skybox zu wandern, jenseits der Grenzen der Map."

////////////////////// Attachments
L["settings.tabname.attachments"] = "Aufsätze"

L["settings.attachments.customization"] = "Anpassung"
L["settings.attachments.atts_nocustomize.title"] = "Keine Anpassung"
L["settings.attachments.atts_nocustomize.desc"] = "Alle Anpassungen über das Anpassungsmenü verbieten.\n\nDies ist eine Server-Variable."
L["settings.attachments.atts_max.title"] = "Maximale Aufsätze"
L["settings.attachments.atts_max.desc"] = "Die maximale Anzahl an Aufsätzen, die an einer Waffe angebracht werden können, einschließlich kosmetischer Aufsätze.\n\nDies ist eine Server-Variable."
L["settings.attachments.autosave.title"] = "Auto-Speichern"
L["settings.attachments.autosave.desc"] = "Deine letzten Waffenanpassungsoptionen werden gespeichert und automatisch angewendet, wenn du diese Waffe das nächste Mal spawnst."
-- L["settings.attachments.blacklist.title"] = "Blacklist Menu"
-- L["settings.attachments.blacklist.open"] = "Open"

L["settings.attachments.inventory"] = "Inventar"
L["settings.attachments.free_atts.title"] = "Freie Auswahl"
L["settings.attachments.free_atts.desc"] = "Aufsätze können verwendet werden, ohne vorher aufgehoben zu werden.\n\nDies ist eine Server-Variable."
L["settings.attachments.atts_lock.title"] = "Einer für Alle"
L["settings.attachments.atts_lock.desc"] = "Wenn du eine Instanz eines Aufsatzes aufhebst, kannst du diesen unendlich oft für alle Ihre Waffen verwenden.\n\nDies ist eine Server-Variable."
L["settings.attachments.atts_loseondie.title"] = "Beim Tod verlieren"
L["settings.attachments.atts_loseondie.desc"] = "Dein Aufsatz-Inventar geht verloren, wenn du stirbst.\n\nDies ist eine Server-Variable."
L["settings.attachments.atts_generateentities.title"] = "Entities generieren"
L["settings.attachments.atts_generateentities.desc"] = "Generiere Entities, mit denen du Aufsätze abrufen kannst, wenn Freie Auswahl deaktiviert ist.\n\nKönnte die Ladezeit erhöhen.\n\nDies ist eine Server-Variable."

////////////////////// Modifiers
L["settings.tabname.modifiers"] = "Modifiers"

L["settings.modifiers.quick.title"] = "Schnell-Stats-Modifier"
L["settings.modifiers.quick.desc"] = " "

L["settings.mod_damage.title"] = "Schaden"
L["settings.mod_spread.title"] = "Streuung"
L["settings.mod_recoil.title"] = "Rückstoß"
L["settings.mod_visualrecoil.title"] = "Visueller Rückstoß"
L["settings.mod_adstime.title"] = "Zielvorrichtungs-Zeit"
L["settings.mod_sprinttime.title"] = "Sprint-bis-Feuer-Zeit"
L["settings.mod_damagerand.title"] = "Schadens-Spanne"
L["settings.mod_muzzlevelocity.title"] = "Mündungsgeschwindigkeit"
L["settings.mod_rpm.title"] = "Feuerrate"
L["settings.mod_headshotdamage.title"] = "Kopfschuss-Schaden"
-- L["settings.mod_malfunction.title"] = "Malfunction Chance"

////////////////////// Controller
L["settings.tabname.controller"] = "Controller"

L["settings.controller.misc"] = "Gemischtes"
L["settings.controller.misc.desc"] = "Es sollte hier einen Knopf geben, der das erweiterte Controller-Konfigurationspanel öffnet, aber bis jetzt befindet es sich in  spawnmenu > Options > ARC9 > Controller."
L["settings.controller.controller.title"] = "Controller-Symbole"
L["settings.controller.controller.desc"] = "Aktiviere Controller-kompatible Symbole, und zeige anstatt von Tastatursymbolen Controllerknöpfe."
-- L["settings.controller.controller_rumble.title"] = "Rumble"
-- L["settings.controller.controller_rumble.desc"] = "Enable controller rumble as long as Fesiug's DLL mod is loaded.\n\ngithub.com/Fesiug/\ngmod-sinput"
L["settings.controller.controller_config.title"] = "Erweiterte Konfiguration"
L["settings.controller.controller_config.content"] = "Öffne Panel"
L["settings.controller.controller_config.desc"] = "Öffne das erweiterte Controller-Konfigurationspanel."

-- L["settings.controller.glyphs.title"] = "Glyph Type"
-- L["settings.controller.glyphs.desc"] = "Choose which family of glyphs you want to use.\nSet up glyphs in \"Spawnmenu\" > Options > ARC9 > Controller."

////////////////////// Aim Assist
-- L["settings.tabname.aimassist"] = "Aim Assist"
-- L["settings.tabname.aimassist.desc"] = "You can enable aim assistance if you might have trouble keeping your aim on your target, or if you just prefer to not put effort into shooting your targets."

-- L["settings.aimassist.enable.title"] = "Enable Aim Assist"
-- L["settings.aimassist.enable.desc"] = "Enables an aim assistance feature that moves your aim towards a target when aiming near them.\n\nThis is a server variable.\n\nRequires Aim Assist to be enabled on CLIENT."

-- L["settings.aimassist.enable_general.desc"] = "Enables an aim assistance feature that moves your aim towards a target when aiming near them.\n\nConfigure it in the \"Aim Assist\" tab."

-- L["settings.aimassist.enable_client.desc"] = "Enables an aim assistance feature that moves your aim towards a target when aiming near them.\n\nRequires Aim Assist to be enabled on SERVER."

-- L["settings.aimassist.intensity.title"] = "Intensity"
-- L["settings.aimassist.intensity.desc"] = "How intense the aim assist is.\n\nThis is a server variable."

-- L["settings.aimassist.cone.title"] = "Cone"
-- L["settings.aimassist.cone.desc"] = "How close or far away you need to look towards a target before the aim assist engages.\n\nThis is a server variable."

-- L["settings.aimassist.head.title"] = "Lock onto head"
-- L["settings.aimassist.head.desc"] = "If the aim assist should lock onto the target's head instead of its chest.\n\nThis is a server variable."

-- L["settings.aimassist.sensmult.desc"] = "Multiply the look sensitivity by this amount when hovering over a valid target.\nThe lower the value, the lower the sensitivity."

////////////////////// Asset Caching
-- L["settings.tabname.caching"] = "Asset Caching"
-- L["settings.caching.title"] = "Asset Caching"
-- L["settings.caching.desc"] = "You can cache some ARC9 assets (save in memory without loading while playing) to prevent stutters for comfort gameplay!\n\nYou surely should enable some stuff if your gmod running on HDD."

-- L["settings.caching.precache_sounds_onfirsttake.title"] = "On first equip: Cache gun sounds"
-- L["settings.caching.precache_sounds_onfirsttake.desc"] = "Caches all sounds only from gun you just took in hands (except reload sounds).\n\nNot any impactful, rather helpful to prevent stutters while firing."

-- L["settings.caching.precache_attsmodels_onfirsttake.title"] = "On first equip: Cache all attachments"
-- L["settings.caching.precache_attsmodels_onfirsttake.desc"] = "Caches all ARC9 attachments models when any ARC9 weapon was first equipped.\n\nCauses pretty big freeze, especially when you have lots of weapons."
-- L["settings.caching.precache_wepmodels_onfirsttake.title"] = "On first equip: Cache all weapon models"
-- L["settings.caching.precache_wepmodels_onfirsttake.desc"] = "Caches all ARC9 weapons viewmodels when any ARC9 weapon was first equipped.\n\nCauses REALLY BIG freeze, especially when you have lots of weapons."

-- L["settings.caching.precache_allsounds_onstartup.title"] = "On game start: Cache all guns sounds"
-- L["settings.caching.precache_allsounds_onstartup.desc"] = "Caches all sounds from all guns on server start-up. (except reload sounds).\n\nNot so impactful, but anyway you better use first option here."
-- L["settings.caching.precache_attsmodels_onstartup.title"] = "On game start: Cache all attachments"
-- L["settings.caching.precache_attsmodels_onstartup.desc"] = "Caches all ARC9 attachments models on server start-up.\n\nCauses pretty big load time increase, especially when you have lots of weapons."
-- L["settings.caching.precache_wepmodels_onstartup.title"] = "On game start: Cache all weapon models"
-- L["settings.caching.precache_wepmodels_onstartup.desc"] = "Caches all ARC9 weapons viewmodels on server start-up.\n\nCauses REALLY BIG load time increase, especially when you have lots of weapons."

-- L["settings.caching.precache_allsounds.title"] = "All weapon sounds"
-- L["settings.caching.precache_wepmodels.title"] = "All weapon models"
-- L["settings.caching.precache_attsmodels.title"] = "All attachments models"

-- L["settings.developer.cache"] = "Cache"

////////////////////// Developer
L["settings.tabname.developer"] = "Entwickler"

L["settings.developer.developer"] = "Entwickleroptionen"
L["settings.developer.dev_always_ready.title"] = "Immer bereit"
L["settings.developer.dev_always_ready.desc"] = "Spiele immer die \"ready\" Animation, wenn eine Waffe gezückt wird.\n\nDies ist eine Server-Variable."
L["settings.developer.dev_benchgun.title"] = "Benchgun"
L["settings.developer.dev_benchgun.desc"] = "Lasse die Waffe dort wo sie gerade ist."
-- L["settings.developer.dev_crosshair.title"] = "Dev Crosshair"
-- L["settings.developer.dev_crosshair.desc"] = "Funky looking crosshair showing the exact point of aim and some useful numbers.\n\nThis is a server variable, and only works for admins - don't get cheaty with this!"
-- L["settings.developer.dev_show_affectors.title"] = "Display Affectors"
-- L["settings.developer.dev_show_affectors.desc"] = "Displays which current affectors are currently applied.\n\nRequires \"Dev Crosshair\"."
L["settings.developer.dev_show_shield.title"] = "Schild zeigen"
L["settings.developer.dev_show_shield.desc"] = "Zeige das Modell vom Schild des Spielers."
L["settings.developer.dev_greenscreen.title"] = "Green-Screen"
L["settings.developer.dev_greenscreen.desc"] = "Zeigt einen Green-Screen-Hintergrund im Menü.\n\nFalls du HDR benutzt, vergiss nicht, mat_bloom_scalefactor_scalar auf 0 zu setzen!"
L["settings.developer.reloadatts.title"] = "Aufsätze neu laden"
L["settings.developer.reloadlangs.title"] = "Sprachen neu laden"
-- L["settings.developer.dev_listmyatts.title"] = "List My Attachments"
L["settings.developer.dev_listanims.title"] = "Animationen auflisten"
L["settings.developer.dev_listbones.title"] = "Knochen auflisten"
L["settings.developer.dev_listbgs.title"] = "Bodygroups auflisten"
L["settings.developer.dev_listatts.title"] = "QCAttach. auflisten"
L["settings.developer.dev_export.title"] = "Export-Code holen"
L["settings.developer.dev_getjson.title"] = "Weapon-JSON holen"

L["settings.developer.presets_clear.title"] = "Waffen-Daten löschen"
L["settings.developer.presets_clear.desc"] = "Lösche Voreinstellungen, alle Icons und Standardvoreinstellungen für Waffen, die du gerade hältst.\n\nWarnung: Wenn das Menü ohne eine ARC9-Waffe in den Händen geöffnet wird, werden alle vorhandenen ARC9-Voreinstellungen und -Icons gelöscht!"

L["settings.developer.clear"] = "Löschen"
L["settings.developer.print"] = "In die Konsole schreiben"
L["settings.developer.reload"] = "Neu laden"
