L = {}

/////////////////////////////////////// Font
////////////////////// See "font_en" file

/////////////////////////////////////// General
////////////////////// Units of measurement
L["unit.second"] = "s"
L["unit.meter"] = "m"
L["unit.millimeter"] = "mm"
L["unit.meterpersecond"] = "m/s"
L["unit.hammerunit"] = "HUwU"
L["unit.decibel"] = "dB"
L["unit.rpm"] = "RPM"
L["unit.moa"] = "MwA"
L["unit.dmg"] = "DMG"
L["unit.projectiles"] = "PRwJ"

L["unit.inch"] = "in"
L["unit.foot"] = "ft"
L["unit.footpersecond"] = "ft/s"
L["unit.yard"] = "yd"

////////////////////// Ammo types
L["ammo.pistol"] = "Piswol AmmOwO"
L["ammo.357"] = "Mawwnum AmmOwO"
L["ammo.smg1"] = "Cawwbine AmmOwO"
L["ammo.ar2"] = "Wufle AmmOwO"
L["ammo.buckshot"] = "Showotgwun AmmOwO"
L["ammo.sniperpenetratedround"] = "S-sniwew AmmOwO"
L["ammo.smg1_grenade"] = "Wufle Gwenawades"
L["ammo.xbowbolt"] = "Cwosbow Bowts"
L["ammo.rpg_round"] = "Wokets"
L["ammo.grenade"] = "Gwenadews"
L["ammo.slam"] = "SWAM"
L["ammo.alyxgun"] = "Awyx Gun AmmOwO"

/////////////////////////////////////// HUD
L["hud.version"] = "OWO SYwwEwS HUD w"
L["hud.jammed"] = "JAWWED >~<"
L["hud.therm_deco"] = "BAWWEL TEMP uwu"

L["hud.firemode.single"] = "S-SEMI ^w^"
L["hud.firemode.burst"] = "BUwUWST"
L["hud.firemode.auto"] = "AUTOwO"
L["hud.firemode.safe"] = "SAWE~"

L["hud.hint.bash"] = "Baww >w<"
L["hud.hint.bipod"] = "Towgl bipOwOd >w<"
L["hud.hint.breath"] = "Howold bwweath owo"
L["hud.hint.customize"] = "Cuwustomise owo"
L["hud.hint.cycle"] = "C-cycle owo"
L["hud.hint.firemode"] = "S-swich fiwemood"
L["hud.hint.inspect"] = "I-inspewt uwu"
L["hud.hint.lean"] = "Lewn"
L["hud.hint.peek"] = "Peek ^w^"
L["hud.hint.reload"] = "Weload!!! Now!"
L["hud.hint.safe"] = "Towgle Sawe"
L["hud.hint.switchsights"] = "S-switch siwts"
L["hud.hint.toggleatts"] = "Towgle awatachmewws"
L["hud.hint.ubgl"] = "Towgwle"
-- L["hud.hint.unjam"] = "Unjam"
L["hud.hint.zoom"] = "Chawanwe zowom"

L["hud.hint.lowammo"] = "Low Ammowo!!"
L["hud.hint.noammo"] = "Nyo Ammowo!! 0_0"

L["hud.error.missingbind"] = "awooga! %s isnt bindwed!!"
L["hud.error.missingbind_zoom"] = "wetawd!! bind \"Suit Zoom\" in setings o.o"
L["hud.error.missingbind_context"] = "wetawd!! bind \"Open Context Menu\" in setings o.o"

/////////////////////////////////////// Customization menu
L["customize.panel.customize"] = "CUwUSTOwOMIZE"
L["customize.panel.personalize"] = "PEWWSOWONALIWE"
L["customize.panel.stats"] = "STAWTS uwu BAWWIWTICS"
L["customize.panel.trivia"] = "TWIWIA owo"
L["customize.panel.inspect"] = "WINSWECT"
L["customize.panel.presets"] = "Pwesews"

L["customize.stats.aimtime"] = "Awaim  time"
L["customize.stats.ammo"] = "Ammowo typwe"
L["customize.stats.armorpiercing"] = "Awrmow Purrrcing >w<"
L["customize.stats.burstdelay"] = "Buwwst delay"
L["customize.stats.capacity"] = "C-cawawity"
L["customize.stats.cyclic"] = "Cuclic WoOF"
L["customize.stats.explosive"] = "E-explowosion Dawage >w<"
L["customize.stats.firemodes"] = "Fiwwe Moods"
L["customize.stats.firepower"] = "Fiwepowew"
L["customize.stats.freeaim"] = "Fwee awaim wadius"
L["customize.stats.muzzlevelocity"] = "Nuzle welocitwy"
L["customize.stats.noise"] = "Nowoise"
L["customize.stats.penetration"] = "p-penewawion UwU"
L["customize.stats.precision"] = "Pwecisiwon"
L["customize.stats.range"] = "Wange owo"
L["customize.stats.ricochet"] = "Rrricwowhet Chwancwe"
L["customize.stats.rof"] = "WOOF"
L["customize.stats.speed"] = "Mowement Spewwed"
L["customize.stats.sprinttofire"] = "Spwint to fiwe time"
L["customize.stats.supplylimit"] = "Suwuply wimit owo"
L["customize.stats.sway"] = "Swaway"
L["customize.stats.triggerdelay"] = "Twiwger delay"

L["customize.hint.attach"] = "Atwaach uwu"
L["customize.hint.controller"] = "Cowntwowwew Modwe is on >w<"
L["customize.hint.cursor"] = "Cuwursow"
L["customize.hint.cycle"] = "C-cycwe swot"
L["customize.hint.delete"] = "Dewete >~<"
L["customize.hint.deselect"] = "Desewect"
L["customize.hint.expand"] = "Expaand owo"
L["customize.hint.export"] = "Expowwt"
L["customize.hint.favorite"] = "Fowowite <3"
L["customize.hint.import"] = "Impowt owo"
L["customize.hint.install"] = "Instawww"
L["customize.hint.last"] = "Lawt swot"
L["customize.hint.lastmode"] = "Lawt moode"
L["customize.hint.nextmode"] = "Newxt mode"
L["customize.hint.open"] = "OWOpen"
L["customize.hint.pan"] = "Paw"
L["customize.hint.quicksave"] = "Quwucksawe"
L["customize.hint.randomize"] = "Awtach wandom 'w'"
L["customize.hint.recalculate"] = "Wecawcuwate"
L["customize.hint.recenter"] = "Rr-recentew"
L["customize.hint.rotate"] = "Wotawe OwO"
L["customize.hint.save"] = "Sawwe >w<"
L["customize.hint.select"] = "Sewect >w<"
L["customize.hint.unattach"] = "Unatwach >~<"
L["customize.hint.unfavorite"] = "Wemowe fowowite >w<"
L["customize.hint.zoom"] = "Zowom"

L["customize.trivia.description"] = "D-descwipwion"

L["customize.stats.explain.firepower"] = "de dawage powotential at powoint-bwank wange"
L["customize.stats.explain.rof"] = "de guns wate of fiwe ^w^"
L["customize.stats.explain.cyclic"] = "de weapon c-cyclic wate of fiwe,,,ignowes factows like buwst delay ow weload wequiwements"
L["customize.stats.explain.capacity"] = "howo much ammo de gun can hold in de magazine + chambew"
L["customize.stats.explain.range"] = "de wange at which de gun deals minimum damage"
L["customize.stats.explain.precision"] = "de weapon's accuwacy. Measuwed in Minutes of Accuwacy (MOA)"
L["customize.stats.explain.muzzlevelocity"] = "de nuzzle velocity of bullets fiwed fwom dis gun"
L["customize.stats.explain.ammo"] = "de type of ammo dis gun uses"
L["customize.stats.explain.penetration"] = "UwU Amount of matewial dis gun can penetwate. Measuwed in millimetews of wood"
L["customize.stats.explain.ricochet"] = "maximum chance fow bullets fwom dis gun to wicochet"
L["customize.stats.explain.armorpiercing"] = "awmount of damage fwom dis gun that completely ignowes most damage wesistances"
L["customize.stats.explain.explosive"] = "amount of explosive damage dis gun will do"
L["customize.stats.explain.speed"] = "spweed at which you can move while using dis gun"
L["customize.stats.explain.aimtime"] = "howo long it takes to aim down sights fwom hip fwe"
L["customize.stats.explain.sprinttofire"] = "howo long it takes to exit spwint and begin shooting"
L["customize.stats.explain.firemodes"] = "wwhwich fiwe modes dis gun has access to"
L["customize.stats.explain.burstdelay"] = "amount of time aftew fiwing a buwst befowe de gun can fiwe again"
L["customize.stats.explain.triggerdelay"] = "delay between pulling de twiggew and fiwing a shot"
L["customize.stats.explain.noise"] = "howo loud de gun's gunshots awe"
L["customize.stats.explain.sway"] = "amount of sway applied to de gun"
L["customize.stats.explain.freeaim"] = "maximum fwee aim angle, Lowew is bettew"
L["customize.stats.explain.supplylimit"] = "amount of ammowo that de gun can weceive fwom AWC9 ammo souwces"

L["customize.bench.dummy"] = "BAWWIWTICS DUM TEWST uwu"
L["customize.bench.effect"] = "EWWEKT AT WANGE"
L["customize.bench.ballistics"] = "TEWMINAL BAWWIWTICS PERAWROWMANCE EWAwALUAWION"
L["customize.bench.precision"] = "MECHANICAL PWECIWWION TEWT"

L["folder.back"] = "Rawr"
L["folder.deselect"] = "Desewect"
L["folder.favorites"] = "Fowowites"
L["folder.select"] = "Sewect >w<"

////////////////////// Automatic stats
L["autostat.enable.pre"] = "Makes"
L["autostat.disable.pre"] = "Nyo"
L["autostat.enable.post"] = ""
L["autostat.disable.post"] = ""

L["autostat.aimdownsightstime"] = "Awaim Dowon Siwts time"
L["autostat.alwaysphysbullet"] = "Awways Phuwusical buwullets"
L["autostat.ammopershot"] = "AmmOwO Pew Shot"
L["autostat.armdamage"] = "Awwm Dawage"
L["autostat.armorpiercing"] = "Awrmow Purrrcing >w<"
L["autostat.autoburst"] = "Auwomawic Buwst Fiwe"
L["autostat.autoreload"] = "Widle weloading"
L["autostat.bash"] = "Mewee Ataks owo"
L["autostat.bashdamage"] = "Mewwee dawage"
L["autostat.bashlungerange"] = "Mewee wuwunge wange"
L["autostat.bashrange"] = "Mewee wange"
L["autostat.bashspeed"] = "Mewee Spewwed >w<"
L["autostat.bipod"] = "Biwod"
L["autostat.bottomlessclip"] = "Botom wess magawine owo"
L["autostat.breathholdtime"] = "ffuwucos time owo"
L["autostat.bulletguidance"] = "Guwuded rrr-rounws uwu"
L["autostat.bulletguidanceamount"] = "Guwudance Wawtor"
L["autostat.canfireunderwater"] = "Undewwawer Showoting"
L["autostat.cantpeek"] = "Nyo Peek .w."
L["autostat.chambersize"] = "Chawamber Lowoad Cunt OwO"
L["autostat.chestdamage"] = "Chest Dawage"
L["autostat.clipsize"] = "Magawine Cawpasity"
L["autostat.cycletime"] = "C-cycle time"
L["autostat.damagemax"] = "Clowose Wange Dawage"
L["autostat.damagemin"] = "Lowong Wange Dawage"
L["autostat.damagerand"] = "Dawage Owarawriance"
L["autostat.deploytime"] = "D-dwaw time"
L["autostat.distance"] = "Buwullet diwwtancwe"
L["autostat.entitymuzzlevelocity"] = "Prowekwtile muzzzel welocitwy"
L["autostat.explosiondamage"] = "E-explowosion Dawage >w<"
L["autostat.explosionradius"] = "E-explowosion Swlawsh Wadius >w<"
L["autostat.fixtime"] = "Uwunjam wime uwu"
L["autostat.freeaimradius"] = "Fwee Awaim Wadiuwus"
L["autostat.headshotdamage"] = "Snout Dawage owo"
L["autostat.heatcapacity"] = "Hewt Cawasity"
L["autostat.heatdissipation"] = "Hewt Diwwiwation uwu"
L["autostat.heatpershot"] = "Hewt Pew Showoot"
L["autostat.hybridreload"] = "H-hybrid widiwidual weloading"
L["autostat.infiniteammo"] = "Inwinite Amuwiwion awa"
L["autostat.legdamage"] = "Paw Dawage"
L["autostat.malfunction"] = "Jawwing >~<"
L["autostat.malfunctionmeanshotstofail"] = "Mewan showts Betwuen Faiwuwes"
L["autostat.malfunctionwait"] = "Mawwunwion w-wait time"
L["autostat.manualaction"] = "Manuwual Action rr~"
L["autostat.manualactionchamber"] = "Shwots Pew Cycwe owo"
L["autostat.neverphysbullet"] = "Nyo-Phuwusical buwullets"
L["autostat.noflash"] = "Nyo Nuzzle Wlash owo"
L["autostat.num"] = "Prowekwtile cunt"
L["autostat.overheat"] = "Owerhewting uwu"
L["autostat.overheattime"] = "OWOrhewat fox time owo"
L["autostat.pelletspread"] = "Cwump Spwead"
L["autostat.penetration"] = "Matewial p-penewawion UwU"
L["autostat.penetrationdelta"] = "Dawage awtew penetwation uwu"
L["autostat.physbulletdrag"] = "Buwullet Dwag"
L["autostat.physbulletgravity"] = "Buwullet Dwop"
L["autostat.physbulletmuzzlevelocity"] = "Muzzzel welocitwy"
L["autostat.postburstdelay"] = "Buwwst Dwelauwu"
L["autostat.pushbackforce"] = "Puwushbak Foworce"
L["autostat.rangemax"] = "Maximuwum wange"
L["autostat.rangemin"] = "M-Mimimal Dawage wange"
L["autostat.recoil"] = "Wecoil"
L["autostat.recoilautocontrol"] = "Wecoil Cowontwol"
L["autostat.recoildissipationrate"] = "Wecoil Dissipation Wate"
L["autostat.recoilkick"] = "Felt Wecoil"
L["autostat.recoilmodifiercap"] = "Maximum cum-ulatiwe wecoil uwu"
L["autostat.recoilpatterndrift"] = "Wecoil Dwwift uwu"
L["autostat.recoilpershot"] = "Wecoil pwer Shwot >w<"
L["autostat.recoilrandomside"] = "H-Howisontawal Wecoil Spwead"
L["autostat.recoilrandomup"] = "Wewtical Wecoil Spwead~"
L["autostat.recoilresettime"] = "Wecoil Weset Time"
L["autostat.recoilside"] = "H-Howisontawal Wecoil"
L["autostat.recoilup"] = "Wewtical Wecoil"
L["autostat.reloadtime"] = "W-weload time owo"
L["autostat.ricochetanglemax"] = "Rrricwowhet AWangwle"
L["autostat.ricochetchance"] = "Rrricwowhet Chwancwe"
L["autostat.rpm"] = "Fiwe Wate"
L["autostat.runawayburst"] = "WunAWAy Buwst"
L["autostat.secondarysupplylimit"] = "Rwesewwe Secowondawy AmmOwO"
L["autostat.shootvolume"] = "Wepowt owolume"
L["autostat.shootwhilesprint"] = "Showot Ww-while Spwinting"
L["autostat.shotgunreload"] = "Windiwidual weloading o"
L["autostat.speed"] = "Mowement Spewwed"
L["autostat.spread"] = "Spwead >w<"
L["autostat.sprinttofiretime"] = "Spwint To fiwe time uwu"
L["autostat.stomachdamage"] = "Stowach Dawage"
L["autostat.supplylimit"] = "Rwesewwe Magawines uwu"
L["autostat.sway"] = "S-sway <w>"
L["autostat.triggerdelay"] = "Twiggew d-deway"
L["autostat.triggerdelaytime"] = "Twiggew deway time"
L["autostat.visualrecoil"] = "W-wisual Wecoil"
L["autostat.visualrecoilpunch"] = "Wisual Wecoil Puwnch"
L["autostat.visualrecoilroll"] = "Wisual Wecoil wwroll"
L["autostat.visualrecoilside"] = "H-Howisontawal Wisual Wecoil"
L["autostat.visualrecoilup"] = "W-wertical wisual Wecoil"

L["autostat.secondary._beforephrase"] = false
-- if true, secondary stat phrasing comes before the stat
L["autostat.secondary._divider"] = " "
-- space between the secondary phrase from the stat phrase. set true to use empty string

-- L["autostat.secondary.blindfire"] = "w-whiwe bwind-fiwing"
L["autostat.secondary.bipod"] = "on bipOwOd"
L["autostat.secondary.crouch"] = "w-whiwe cwouchiwuwung"
L["autostat.secondary.empty"] = "owon wast wound in mag"
L["autostat.secondary.evenreload"] = "ewewy uwuwen weload"
L["autostat.secondary.evenshot"] = "ewewy uwuwen shwot >//<"
L["autostat.secondary.first"] = "owon first shwot"
L["autostat.secondary.firstshot"] = "owon first shwot"
L["autostat.secondary.heated"] = "while hewted"
L["autostat.secondary.hipfire"] = "in beeppfiwe uwu"
L["autostat.secondary.hot"] = "fwom hewt"
L["autostat.secondary.last"] = "owon wast wound in mag"
L["autostat.secondary.lastshot"] = "owon wast round in mag"
L["autostat.secondary.midair"] = "in meow-air"
L["autostat.secondary.move"] = "wwhiwe mowing"
L["autostat.secondary.oddreload"] = "ewewy owdd weload"
L["autostat.secondary.oddshot"] = "ewewy owdd shwot >///<"
L["autostat.secondary.recoil"] = "from wecoil" --"With Each Shot"
L["autostat.secondary.shooting"] = "w-whiwe showoting"
L["autostat.secondary.sighted"] = "while siwted"
L["autostat.secondary.sights"] = "in siwts!"
L["autostat.secondary.silenced"] = "wwhen siwenced owo"
L["autostat.secondary.sprint"] = "while Spwinting"
L["autostat.secondary.true"] = "wwith TwueNawes"
L["autostat.secondary.ubgl"] = "in UwUBGL"

////////////////////// Blacklist menu
L["blacklist.title"] = "AWWC9 awatachmenws bwackwist >w<"
L["blacklist.desc"] = "AwAtachmenws checkewd hewe wiww be bwocked from use ^w^"
L["blacklist.blisted"] = "BWACKWISTED"
L["blacklist.all"] = "AWW"
L["blacklist.id"] = "ID :3"
L["blacklist.name"] = "NAME"
L["blacklist.filter"] = "FIWTEW"

////////////////////// Incompatible addons
L["incompatible.title"] = "AWC9: INCOwOMPATIBLE ADDONS >w<"
L["incompatible.line1"] = "Y-you hawwe some awaddons that awwe knowon to not wowk with AWC9"
L["incompatible.line2"] = "Diawawable dem orrrawr expect bwoken behaviow >~<"
L["incompatible.confirm"] = "Acknowowewge owo"
L["incompatible.wait"] = "W-Wait {time}s uwu"
L["incompatible.never"] = "Nevew wawn me awagain >///<"
L["incompatible.never.hover"] = "Awe you sillius wight meow? you undewwstand de consewuences??? >-<"
L["incompatible.never.confirm"] = "You hawe chowwen to newew showww INCOwOMPATIBLE owawnings again. If you encountew ewwows owr bwoken behaviouw its youw own wesponsibwwity >-< you silly ass"

////////////////////// Presets
L["customize.presets.atts"] = " awatachmenws >w<"
L["customize.presets.back"] = "Bawack >w<"
L["customize.presets.cancel"] = "C-cancel >w<"
L["customize.presets.code"] = "Pwewewet c-ode (Copied to Clipboawd owo)"
L["customize.presets.default"] = "Dewaauwt"
L["customize.presets.default.long"] = "Dewaauwt pwesew"
L["customize.presets.dumb"] = "Awe you silly?"
L["customize.presets.import"] = "Impowwt"
L["customize.presets.invalid"] = "Invalid stwing! >~<"
L["customize.presets.new"] = "New pwesew name"
L["customize.presets.paste"] = "Paste pwesew code hewwe tee hee"
L["customize.presets.random"] = "OwO waandom"
L["customize.presets.save"] = "Sawwe"
L["customize.presets.unnamed"] = "Uwwamed"

L["customize.presets.deldef"] = "Awee yyu suwe yu wawt two dewete \"{name}\" dewaauwt pwesew? owo"
L["customize.presets.deldef2"] = "Youw woulwd hawe to weset uwuweapon in dewelopew sewtings two weturn it >~<"
L["customize.presets.yes"] = "MEOW !"

////////////////////// Tips
L["tips.arc-9"] = "Its AWC9  NOT ARC9 >~<"
L["tips.blacklist"] = "Yu can bwaklist awwtachments! See de AWC9 oWowkshop descwiption fow mowe infowmation"
L["tips.bugs"] = "Weporwt bugs on de official discowd sewvew ewww owr betew  open a gituwub iwwue owo"
L["tips.custombinds"] = "AWC9 kwey cowombows c-can be wepwaced with cuwustom binds. Stawt typing +arc9_ to find de awailable bwinds!"
L["tips.cyberdemon"] = "To kill de tewwowist shoot him until he ded >~<"
L["tips.description"] = "W-we adwise yu to wead de descwiptions of addons befowe commenting owo"
L["tips.development"] = "Keen to dewelop AWC9 content? de official diwwcowd sewverwr does not have any rewwouwres >w<"
L["tips.discord"] = "Do not join diamond dDoves on diwwcowd! die"
L["tips.external"] = "If using de gituwub vewsion of AWC9 make suwe to upwate fwequently ^^"
L["tips.hints"] = "K-keep AWC9 HUD own to sewe cowontwol hintss"
L["tips.lean"] = "To mawuawwy wean, bwiwnd kewys to +alt1 awnd +alt2"
L["tips.love"] = "Feel fwee to tell de devs you appweciate theiw wowk UwU it weally helps us keep going owo"
L["tips.m9k"] = "Check out m9k guwuns meow"
L["tips.official"] = "Owly dowonload AWC9 fwom official souwces >.< Thiwd pawty upwoads may be mawicious ow outdated >o<"
L["tips.presets"] = "Shawe yuw fowowite pwesews with yuww furwiends by expowting dem!"
L["tips.settings"] = "You can tuwn dese tips off and much mowe in de AWC9 settings owo c-click de button in de top left cownew"
L["tips.tips"] = "Tips hawwe a fixed owdew. Kewep weading and yuw ewwentuawy see dem all"
L["tips.tolerance"] = "Aww weapon basews wowk fine togeww thewes no need fow fowowoitiswm"

////////////////////// Other
L["atts.favourites"] = "Fowowites"
L["atts.filter"] = "Filtew"

/////////////////////////////////////// Settings menu
-- Use this method to localize convars in settings menu:
-- settings.convar.title = "Convar Title"
-- settings.convar.desc = "Convar Description"

L["settings.title"] = "A-AWC9 Sewwings"
L["settings.desc"] = "D-descwipwion"

L["settings.default_convar"] = "defauwt wawue"
L["settings.convar_server"] = "Sewwvew wawiabwe"
L["settings.convar_client"] = "Cwient wawiabwe"

////////////////////// General
L["settings.tabname.general"] = "Genewal"

L["settings.general.client"] = "Cwient"
L["settings.truenames.title"] = "Twue names"
L["settings.truenames.desc"] = "Set whedew to use weapons' weal names ow fictional names made by de developews. Not all weapons utilize dis.\n\nSewvew setting may ovewwide dis pwefewence"
L["settings.resetsettings.cl.title"] = "Weset aww CWIENT setings"

L["settings.general.server"] = "Sewvewwr"
L["settings.truenames_default.title"] = "Default Twue Names"
L["settings.truenames_default.desc"] = "Set de default twue names mode on de sewvew. All playews using \"Default\" in pwefewence will use dis"
L["settings.truenames_enforced.title"] = "Default Twue Names Enfowced"
L["settings.truenames_enforced.desc"] = "Set to fowce all playews to use de sewvew setting fow twue names"

L["settings.resetsettings.sv.title"] = "Weset aww SErrWWEW setings"

L["settings.reset"] = "UwU Weset!!!"

////////////////////// Performance
L["settings.tabname.performance"] = "Perawawmance"

L["settings.performance.important"] = "High Pewfowmance Impact"
L["settings.cheapscopes.title"] = "Chweap Scopes"
L["settings.cheapscopes.desc"] = "A cheap wT scope implementation by zooming youw whole view to aim, instead of wendewing wowld again in a scope. Significantly incweases pewfowmance on lawge maps"
L["settings.tpik.title"] = "TPIK"
L["settings.tpik.desc"] = "TPIK (Thiwd Pewson Invewse Kinematics) is a system that allows most weapons display detailed and same as in fiwst pewson hands positions, weload and fiwing animations in thiwd pewson.\n\nConfiguwe it in Visuals tab"
L["settings.allflash.title"] = "All Flashlights"
L["settings.allflash.desc"] = "Fully wendew all flashlights fwom odew playews.\n\nVewy expensive on sewvews"

L["settings.performance.blur.title"] = "Bluw"
L["settings.cust_blur.title"] = "Customization Backgwound"
L["settings.cust_blur.desc"] = "Bluws customization backgwound"
L["settings.fx_reloadblur.title"] = "While weloading"
L["settings.fx_reloadblur.desc"] = "Bluws de wowld while weloading"
L["settings.fx_animblur.title"] = "While weadying"
L["settings.fx_animblur.desc"] = "Bluws de wowld while deploying a weapon fow de fiwst time"
L["settings.fx_rtblur.title"] = "In Scopes"
L["settings.fx_rtblur.desc"] = "Bluws de wowld while using a magnified scope"
L["settings.fx_adsblur.title"] = "In Sights"
L["settings.fx_adsblur.desc"] = "Bluws de weapon while aiming down sights"
L["settings.fx_rtvm.title"] = "Wendew Wewapown dwough WT Scowpes"
L["settings.fx_rtvm.desc"] = "! EXPEWIMENTAW !\nWendwrs de wewapon and its attwachments dwough WT scwopes. Wequiwes \"Chewp Scowpes\" to be disablewd.\nSigniwicantwy weduces pewwormance."

L["settings.performance.shelleject.title"] = "Sheww Eject"
L["settings.eject_fx.title"] = "Smoke Effects"
L["settings.eject_fx.desc"] = "Pwoduce smoke effects fwom ejected shell casings, whewe de weapon suppowts dis featuwe"
L["settings.eject_time.title"] = "Add Life Time"
L["settings.eject_time.desc"] = "Allow shell casings to stay in de wowld fow longew. Can be expensive"

L["settings.performance.fx.title"] = "Efwects"
L["settings.muzzle_light.title"] = "Nuzzle Light"
L["settings.muzzle_light.desc"] = "Enable light emitted fwom nuzzle flashes when fiwing a weapon"
L["settings.muzzle_others.title"] = "Otter nuzzle ewwekts"
L["settings.muzzle_others.desc"] = "Enabwe nuzzle ewwekts fwom othew pwayews guns :3"

////////////////////// Optics
L["settings.tabname.optics"] = "OwOptics"

L["settings.optics.control"] = "Contwol"
L["settings.optics.sensmult.title"] = "Muwtipwy ADS sensitiwity"
L["settings.optics.sensmult.desc"] = "Muwtipwy de wook sensitiwity by dis amouwunt wwen awiming.\nDe wowew de wawue, de wowew de sensitiwity.\nUwUsewuw wen uwusing controwwews or iw de usew juwust wants wowew awiming sensitiwity."
L["settings.optics.compensate_sens.title"] = "Compensate Sensitivity"
L["settings.optics.compensate_sens.desc"] = "Compensate sensitivity fow magnification"
L["settings.optics.toggleads.title"] = "Towggle ADS"
L["settings.optics.toggleads.desc"] = "Awiming wiw togwe sights."

-- L["settings.optics.dtap_sights.title"] = "Double-Tap to Switch Sights"
-- L["settings.optics.dtap_sights.desc"] = "Allows double-tapping the USE key to switch sights."

L["settings.optics.color"] = "Colow"
L["settings.optics.reflex.title"] = "weflex Sights"
L["settings.optics.reflex.desc"] = "Colow to use fow weflex/hologwaphic sights.\n\nNot all optics suppowt dis featuwe"
L["settings.optics.scope.title"] = "Scopes"
L["settings.optics.scope.desc"] = "Colow to use fow magnified scopes.\n\nNot all optics suppowt dis featuwe"

////////////////////// Crosshair
L["settings.tabname.crosshair"] = "Cwosshaiw"

L["settings.crosshair.crosshair"] = "Cwosshaiw"
L["settings.crosshair.cross_enable.title"] = "Enable cwosshaiw"
L["settings.crosshair.cross_enable.desc"] = "Enable cwosshaiw. Some guns do not allow you to use de cwosshair"
L["settings.crosshair.cross.title"] = "Cwosshaiw Colow"
L["settings.crosshair.cross.desc"] = "de colow of youw cwosshaiw"
L["settings.crosshair.cross_size_mult.title"] = "Cwosshaiw Size"
L["settings.crosshair.cross_size_mult.desc"] = "Muwtipwy de size of youw cwosshaiw"
L["settings.crosshair.cross_size_dot.title"] = "Dot Size"
L["settings.crosshair.cross_size_dot.desc"] = "Muwtipwy de size of de middle dot"
L["settings.crosshair.cross_size_prong.title"] = "Pwong Size"
L["settings.crosshair.cross_size_prong.desc"] = "Muwtipwy de size of de outew pwongs"
L["settings.crosshair.crosshair_static.title"] = "Static Cwosshaiw"
L["settings.crosshair.crosshair_static.desc"] = "Enable static cwosshaiw, which does not move when shooting"
L["settings.crosshair.crosshair_force.title"] = "Fowce Cwosshaiw"
L["settings.crosshair.crosshair_force.desc"] = "Fowce de cwosshaiw even on guns that don't want you to see it.\n\nSewvew setting"
L["settings.crosshair.crosshair_target.title"] = "Wed cwosshaiw on tawget"
L["settings.crosshair.crosshair_target.desc"] = "Make the cwosshaiw wed wen awiming on a tawget.\nAwso activates awim assist if it is tuwned on."
L["settings.crosshair.crosshair_peeking.title"] = "Dispway cwosshaiw when peeking"
L["settings.crosshair.crosshair_peeking.desc"] = "Dispways de cwosshaiw wen aiwming and uswing de pewek wunction."

////////////////////// Customization
L["settings.tabname.hud_cust"] = "Cuwustomiawon"

L["settings.hud_cust.hud"] = "HUD"
L["settings.hud_cust.hud_scale.title"] = "HUD Scale"
L["settings.hud_cust.hud_scale.desc"] = "Scale multipliew fow AWC9's HUD"
L["settings.hud_cust.hud_deadzonex.title"] = "HUD Widh dewdzowne"
L["settings.hud_cust.hud_deadzonex.desc"] = "Howizontal dewadzowne fow cuwtomiwation menuwu and huwud panel\nUwUseful for uwtwawidew monitows owo"
L["settings.hud_cust.hud_color.title"] = "HUD Colow"
L["settings.hud_cust.hud_color.desc"] = "Highlight colow fow de HUD.\nde accent colow"
L["settings.hud_cust.hud_holiday.title"] = "Howowiday demes"
L["settings.hud_cust.hud_holiday.desc"] = "demes dat actiwate duwing cewtain howidays.\nWiw ovewwide highwight colow >w<"
L["settings.hud_cust.hud_darkmode.title"] = "Dawk deme"
L["settings.hud_cust.hud_darkmode.desc"] = "Enables dawk colows in HUD instead of light gway and disables vignette effect in backgwound"
L["settings.hud_cust.cust_light.title"] = "Enable Light"
L["settings.hud_cust.cust_light.desc"] = "Enables gun lighting in de customization menu.\n\nSame thing as button neaw settings button"
L["settings.hud_cust.cust_light_brightness.title"] = "Light Bwightness"
L["settings.hud_cust.cust_light_brightness.desc"] = "howo bwight that light in de customization panel will be.\n\nDon't fowget to tuwn it on fiwst though!"

L["settings.hud_cust.customization"] = "Customization"
L["settings.hud_cust.cust_hints.title"] = "Hints"
L["settings.hud_cust.cust_hints.desc"] = "Enable hints in de customization menu"
L["settings.hud_cust.cust_tips.title"] = "Tiwips"
L["settings.hud_cust.cust_tips.desc"] = "Tiwips about AWC9 base neaw hints"
L["settings.hud_cust.cust_exit_reset_sel.title"] = "Exit wesets Selection"
L["settings.hud_cust.cust_exit_reset_sel.desc"] = "Exiting customization menu wesets de active slot selection"
-- L["settings.hud_cust.imperial.title"] = "Imperial Measurement"
-- L["settings.hud_cust.imperial.desc"] = "Replaces various measurement systems to their Imperial variants.\nOnly affects the \"Stats & Ballistics\" customization screen."

////////////////////// Game HUD
L["settings.tabname.hud_game"] = "Game HUwUD"

L["settings.hud_game.lcd"] = "LCD Panel"
L["settings.hud_game.hud_arc9.title"] = "Enable HUD"
L["settings.hud_game.hud_arc9.desc"] = "Enable HUD fow AWC9 weapons"
L["settings.hud_game.hud_always.title"] = "On all weapons"
L["settings.hud_game.hud_always.desc"] = "Enable that HUD on all weapons"
L["settings.hud_game.hud_compact.title"] = "Compact Mode"
L["settings.hud_game.hud_compact.desc"] = "Compact appeawance fow de HUD panel"
L["settings.hud_game.hud_nohints.title"] = "Diwable Hints >w<"
L["settings.hud_game.hud_nohints.desc"] = "Diawawable hints completely. dey will not showo up in de 3D HUD, now in de 2D HUD"
L["settings.hud_game.hud_keephints.title"] = "Keep Hints"
L["settings.hud_game.hud_keephints.desc"] = "Showo de AwC9 contwol hints on top on HUD panel"
L["settings.hud_game.hud_force_disable.title"] = "Fowce diswabwe HUwUD"
L["settings.hud_game.hud_force_disable.desc"] = "Disawbwe AWC9 HUD fow aww pwayews. does nowt awwect hiwnts."

L["settings.hud_game.killfeed"] = "Killfeed"
L["settings.hud_game.killfeed_enable.title"] = "Killfeed Icons"
L["settings.hud_game.killfeed_enable.desc"] = "Enable auto-genewation of killfeed icons fow AwC9 guns"
L["settings.hud_game.killfeed_dynamic.title"] = "Dynamic updating"
L["settings.hud_game.killfeed_dynamic.desc"] = "Killfeed icons will be wegenewated aftew each kill.\n\nTuwn off if you want get that 0.1 fps"
L["settings.hud_game.killfeed_colour.title"] = "Full colow Icons"
L["settings.hud_game.killfeed_colour.desc"] = "Dynamically genewated icons awe fully colowed"

L["settings.hud_game.breath"] = "Bweath"
L["settings.hud_game.breath_hud.title"] = "Bweath HUD"
L["settings.hud_game.breath_hud.desc"] = "Showo a baw that displays youw wemaining bweath while stabilizing youw gun in sights"
L["settings.hud_game.breath_pp.title"] = "Bweath Post-Pwocess"
L["settings.hud_game.breath_pp.desc"] = "Holding bweath will also add post-pwocessing effects to youw scween"
L["settings.hud_game.breath_sfx.title"] = "Bweath SFX"
L["settings.hud_game.breath_sfx.desc"] = "Holding bweath will play associated sound effects"

L["settings.hud_game.centerhint"] = "Centewed Hiwnts uwu"
L["settings.hud_game.centerhint_reload.title"] = "Centew weload hint"
L["settings.hud_game.centerhint_reload.desc"] = "Display a reload tip when low on ammunition."
L["settings.hud_game.centerhint_reload_percent.title"] = "Magawine Pewcentwage"
L["settings.hud_game.centerhint_reload_percent.desc"] = "Display the reload tip when the current magazine is at this percentage value."
L["settings.hud_game.centerhint_bipod.title"] = "Centew bipowod hint"
L["settings.hud_game.centerhint_bipod.desc"] = "Centewed bipowod hint"
-- L["settings.hud_game.centerhint_jammed.title"] = "Display Jammed Tip"
-- L["settings.hud_game.centerhint_jammed.desc"] = "Display a tip when your weapon is jammed."

-- L["settings.hud_game.centerhint_firemode.title"] = "Display Firemode Tip"
-- L["settings.hud_game.centerhint_firemode.desc"] = "Display a tip when you swap firing mode or toggle your safety."
-- L["settings.hud_game.centerhint_firemode_time.title"] = "Display Firemode Time"
-- L["settings.hud_game.centerhint_firemode_time.desc"] = "How long the firing mode should be displayed."

L["settings.hud_game.hud_glyph"] = "Gwyph Type"

L["settings.hud_game.hud_glyph_type_hud.title"] = "HUwUD"
L["settings.hud_game.hud_glyph_type_hud.desc"] = "Change which famiwy of gwyphs to use.\nDis awwects de HUD tips."

L["settings.hud_game.hud_glyph_type_cust.title"] = "Custowomization Menu"
L["settings.hud_game.hud_glyph_type_cust.desc"] = "Change which famiwy of gwyphs to use.\nDis awwects de cuwstomization menu tips.\nChanges appwy next time de customizatiwon menuwu is owpened."

L["settings.hud_game.hud_glyph_light"] = "Wight"
L["settings.hud_game.hud_glyph_dark"] = "Dawk"
L["settings.hud_game.hud_glyph_knockout"] = "Knokowot"

////////////////////// NPCs
L["settings.tabname.npc"] = "NPCs >w<"

L["settings.npc.weapons"] = "NPC Weapons"
L["settings.npc.npc_equality.title"] = "Damage Equality"
L["settings.npc.npc_equality.desc"] = "NPCs do just as much damage as playews do.\n\ndis is a sewvew wawiableh"
L["settings.npc.npc_spread.title"] = "NPC Spwead"
L["settings.npc.npc_spread.desc"] = "Multipliew fow howo inaccuwate NPCs will be when fiwing"
L["settings.npc.npc_atts.title"] = "Give awatachmenws"
L["settings.npc.npc_atts.desc"] = "Spawned ow given AwC9 weapons weceive a wandom set of awatachmenws.\n\ndis is a sewvew wawiableh"
L["settings.npc.npc_autoreplace.title"] = "Weplace NPC UWeapons"
L["settings.npc.npc_autoreplace.desc"] = "Weplace NPC weapons with wandomly chosen AwC9 weapons.\n\ndis is a sewvew wawiableh"
L["settings.npc.replace_spawned.title"] = "Weplace Gwound Weapons"
L["settings.npc.replace_spawned.desc"] = "Weplace map/spawned HL2 weapons with wandomly chosen AwC9 weapons.\n\ndis is a sewvew wawiableh"
L["settings.npc.npc_give_weapons.title"] = "Playews Can Give Weapons"
L["settings.npc.npc_give_weapons.desc"] = "Playews awe able to pwess E on NPCs to give dem deiw weapon.\n\ndis is a sewvew wawiableh"

////////////////////// Gameplay
L["settings.tabname.gameplay"] = "Gamepway"

L["settings.gameplay.controls"] = "Contwols"
L["settings.gameplay.toggleads.title"] = "Toggle ADS"
L["settings.gameplay.toggleads.desc"] = "Aiming will toggle sights"
L["settings.gameplay.autolean.title"] = "Automatic Lean"
L["settings.gameplay.autolean.desc"] = "Aiming will twy to automatically lean if dis is possible"
L["settings.gameplay.autoreload.title"] = "Automatic weload"
L["settings.gameplay.autoreload.desc"] = "Empty AWC9 weapons will weload automatically"
L["settings.gameplay.togglelean.title"] = "Toggle Lean"
L["settings.gameplay.togglelean.desc"] = "Pwessing de lean keys will toggle leaning instead of needing to be held down.\n\nWowks poowly in conjunction with autolean. If using toggle lean, you should Diawawable autolean"
L["settings.gameplay.togglepeek.title"] = "Towgle peeek"
L["settings.gameplay.togglepeek.desc"] = "Pwessing de peek key will toggle peeking instead of needing to be held down"
L["settings.gameplay.togglepeek_reset.title"] = "Weset pewek stawte awter awaiming"
L["settings.gameplay.togglepeek_reset.desc"] = "(owly if Towgle Pewek is on owo)\npeeeek state w-wil notw be wetaiwed wwen ewiting awaim dowon siwts uwu"
L["settings.gameplay.togglebreath.title"] = "Towgle howolding bweath"
L["settings.gameplay.togglebreath.desc"] = "Pwessing de Holding Bweath key will toggle Holding Bweath instead of needing to be held down"

L["settings.gameplay.mechanics"] = "Game Mechanics"
L["settings.gameplay.infinite_ammo.title"] = "Infinite Ammo"
L["settings.gameplay.infinite_ammo.desc"] = "Weapons have infinite ammunition.\n\ndis is a sewvew wawiableh"
L["settings.gameplay.realrecoil.title"] = "Physical Visual wecoil"
L["settings.gameplay.realrecoil.desc"] = "Select weapons set up fow dis featuwe expewience physical nuzzle wise, meaning dey will fiwe whewe deiw viewmodel shows it wadew than at de centew of de scween. Vewy impowtant fow some weapon packs' balancing schemes.\n\ndis is a sewvew wawiableh"
L["settings.gameplay.lean.title"] = "Leaning"
L["settings.gameplay.lean.desc"] = "Whedew playews can lean with +alt1 and +alt2, including automatic lean.\n\ndis is a sewvew wawiableh"
L["settings.gameplay.mod_sway.title"] = "Sway"
L["settings.gameplay.mod_sway.desc"] = "Weapons will have sway, if dey awe set up to use it.\n\ndis is a sewvew wawiableh"
L["settings.gameplay.mod_freeaim.title"] = "Fwee Aim"
L["settings.gameplay.mod_freeaim.desc"] = "Weapons will have fwee aim, and will not always shoot in de middle of de scween.\n\ndis is a sewvew wawiableh"
L["settings.gameplay.mod_bodydamagecancel.title"] = "Body Damage Cancel"
L["settings.gameplay.mod_bodydamagecancel.desc"] = "Cancel out default body damage multipliew. Only Diawawable if using anodew mod that pwovides dis type of functionality.\ne.g. Mods which change de default limb multipliews.\n\ndis is a sewvew wawiableh"
L["settings.gameplay.breath_slowmo.title"] = "Slow-Mo Bweath"
L["settings.gameplay.breath_slowmo.desc"] = "Holding bweath slows time.\n\nSingleplayew only"
L["settings.gameplay.manualbolt.title"] = "Manual Cycling"
L["settings.gameplay.manualbolt.desc"] = "Bolt-action weapons configuwed fow dis featuwe will only bolt when w is pwessed, and not when de attack key is weleased"
L["settings.gameplay.never_ready.title"] = "No weady Anims"
L["settings.gameplay.never_ready.desc"] = "Diawawable weady animations when deploying a weapon.\n\ndis is a sewwew wawiableh"
L["settings.gameplay.recoilshake.title"] = "Wecoiw FOW Shwake -w-"
L["settings.gameplay.recoilshake.desc"] = "Snwaps wield owo wiew when showoting"
L["settings.gameplay.equipment_generate_ammo.title"] = "Uniquwe Ammowo Tywps fow eckwipmenwt"
L["settings.gameplay.equipment_generate_ammo.desc"] = "Thewe wimit ow 255 ammowo typaws and diswabwing dis optiowon may hewp wix some pwoblems if u hawe lowts of addowons. \n\nWekuiwes westawt.\n\ndis is a sewwew wawiableh"

-- ??
L["settings.gameplay.mult_defaultammo.title"] = "Dewault Weserve Amo"
L["settings.gameplay.mult_defaultammo.desc"] = "How many magazinews/gwenades/eckwipmenwt giwe to plawew when he take weapon fow fiwst time?\n\ndis is a sewwew wawiableh"
L["settings.gameplay.nearwall.title"] = "Neaw-walling"
L["settings.gameplay.nearwall.desc"] = "Not allow gun shoot when you standing too close to wall ow any obstacle"

////////////////////// Visuals
L["settings.tabname.visuals"] = "Wisuwuals"

L["settings.visuals.viewmodel"] = "Viewmodel"
L["settings.visuals.vm_bobstyle.title"] = "Bob Style"
L["settings.visuals.vm_bobstyle.desc"] = "Select diffewent bobbing styles, to de flavow of diffewent membews of de AWC9 team (and Valve Softwawe), going fwom most newest style to oldest one"
L["settings.visuals.fov.title"] = "FOV"
L["settings.visuals.fov.desc"] = "Add viewmodel FOV. Makes de viewmodel biggew ow smallew. Use wesponsibly"
L["settings.visuals.vm_addx.title"] = "Add X"
L["settings.visuals.vm_addx.desc"] = "Shift de viewmodel to de wight ow left"
L["settings.visuals.vm_addy.title"] = "Add Y"
L["settings.visuals.vm_addy.desc"] = "Shift de viewmodel fowwawds and backwawds"
L["settings.visuals.vm_addz.title"] = "Add Z"
L["settings.visuals.vm_addz.desc"] = "Shift de viewmodel up and down"

L["settings.visuals.cambob"] = "Wiew bowobing"
L["settings.visuals.vm_cambob.title"] = "Spwint wiew bowobing"
L["settings.visuals.vm_cambob.desc"] = "Makes youw camewa move when you spwinting"
L["settings.visuals.vm_cambobwalk.title"] = "Walk wiew bowobing"
L["settings.visuals.vm_cambobwalk.desc"] = "Makes youw camewa slightly move when you walking awound (wequiwes spwint bobbing)"
L["settings.visuals.vm_cambobintensity.title"] = "Inwenwity"
L["settings.visuals.vm_cambobintensity.desc"] = "howo intense bobbing will be"

L["settings.visuals.tpik"] = "TPIK"
L["settings.visuals.tpik.title"] = "Enable TPIK"
L["settings.visuals.tpik.desc"] = "TPIK (Thiwd Pewson Invewse Kinematics) is a system that allows most weapons display detailed and same as in fiwst pewson hands positions, weload and fiwing animations in thiwd pewson"
L["settings.visuals.tpik_others.title"] = "Otter Pwayews TPIK"
L["settings.visuals.tpik_others.desc"] = "Show TPIK fow pwaywrs ottew dan uwselw. Negatively impacts pewwowmance."
L["settings.visuals.tpik_framerate.title"] = "TPIK Fwamewate"
L["settings.visuals.tpik_framerate.desc"] = "Maximum fwamewate at which TPIK can wun. Set to 0 fow unlimited"

////////////////////// Bullet Physics
L["settings.tabname.bullets"] = "Buwuwwet Pwysics"

L["settings.bullets.bullets"] = "Bullet Physics"
L["settings.bullets.bullet_physics.title"] = "Physical Bullets"
L["settings.bullets.bullet_physics.desc"] = "Weapons that suppowt dis featuwe will fiwe physical bullets, which have dwop, twavel time, and dwag.\n\ndis is a sewvew wawiableh"
L["settings.bullets.bullet_gravity.title"] = "Gwavity"
L["settings.bullets.bullet_gravity.desc"] = "Multipliew fow bullet gwavity.\n\ndis is a sewvew wawiableh"
L["settings.bullets.bullet_drag.title"] = "Dwag"
L["settings.bullets.bullet_drag.desc"] = "Multipliew fow bullet dwag.\n\ndis is a sewvew wawiableh"
L["settings.bullets.ricochet.title"] = "Wwwicochet"
L["settings.bullets.ricochet.desc"] = "Bullets fiwed fwom select weapons can sometimes bounce off of suwfaces and continue to twavel and do damage.\n\ndis is a sewvew wawiableh"
L["settings.bullets.mod_penetration.title"] = "Penetwation"
L["settings.bullets.mod_penetration.desc"] = "Bullets fiwed fwom select weapons can penetwate suwfaces and deal damage to whatevew is on de odew side.\n\ndis is a sewwew wawiableh"
L["settings.bullets.bullet_lifetime.title"] = "Life Time"
L["settings.bullets.bullet_lifetime.desc"] = "Time in seconds aftew which a bullet will be deleted.\n\ndis is a sewwew wawiableh"
L["settings.bullets.bullet_imaginary.title"] = "Imaginawy Bullets"
L["settings.bullets.bullet_imaginary.desc"] = "Bullets will appeaw to twavel into de skybox, beyond de map's bounds"

////////////////////// Attachments
L["settings.tabname.attachments"] = "Awachmewts"

L["settings.attachments.customization"] = "Customization"
L["settings.attachments.atts_nocustomize.title"] = "Diawawable Customization"
L["settings.attachments.atts_nocustomize.desc"] = "Disallow all customization via de customization menu.\n\ndis is a sewwew wawiableh"
L["settings.attachments.atts_max.title"] = "Max awatachmenws"
L["settings.attachments.atts_max.desc"] = "de maximum numbew of awatachmenws that can be put on a weapon, including cosmetic awatachmenws.\n\ndis is a sewwew wawiableh"
L["settings.attachments.autosave.title"] = "Autosave"
L["settings.attachments.autosave.desc"] = "Youw last weapon customization options will be saved and automatically applied de next time you spawn that weapon"
L["settings.attachments.blacklist.title"] = "Bwackwist Menuwu"
L["settings.attachments.blacklist.open"] = "OwOpen :3"

L["settings.attachments.inventory"] = "Inventowy"
L["settings.attachments.free_atts.title"] = "Fwee awatachmenws"
L["settings.attachments.free_atts.desc"] = "Awatachmenws can be used without being picked up fiwst.\n\ndis is a sewwew wawiableh"
L["settings.attachments.atts_lock.title"] = "One Fow All"
L["settings.attachments.atts_lock.desc"] = "Picking up one instance of an awatachmenws allows you to use it infinite times on all youw guns.\n\ndis is a sewwew wawiableh"
L["settings.attachments.atts_loseondie.title"] = "Lose On Death"
L["settings.attachments.atts_loseondie.desc"] = "Youw attachment inventowy will be lost when you die.\n\ndis is a sewwew wawiableh"
L["settings.attachments.atts_generateentities.title"] = "Genewate Entities"
L["settings.attachments.atts_generateentities.desc"] = "Genewate entities that can be spawned, allowing you to pick up awatachmenws when fwee awatachmenws is off.\n\nMight incwease load time.\n\ndis is a sewwew wawiableh"

////////////////////// Modifiers
L["settings.tabname.modifiers"] = "Modifiews"

L["settings.modifiers.quick.title"] = "Quick Stats Modifiews"
L["settings.modifiers.quick.desc"] = " "

L["settings.mod_damage.title"] = "Damage"
L["settings.mod_spread.title"] = "Spwead"
L["settings.mod_recoil.title"] = "Wecoil"
L["settings.mod_visualrecoil.title"] = "Wusual wecoil"
L["settings.mod_adstime.title"] = "Awaim Dowon Siwts time"
L["settings.mod_sprinttime.title"] = "Spwint To fiwe time"
L["settings.mod_damagerand.title"] = "Dawage Wawiance"
L["settings.mod_muzzlevelocity.title"] = "Nuzzzel welocitwy"
L["settings.mod_rpm.title"] = "RPM"
L["settings.mod_headshotdamage.title"] = "Snout Damage owo"
L["settings.mod_malfunction.title"] = "Mawwunctiwon Chanwce"

////////////////////// Controller
L["settings.tabname.controller"] = "Contwollew"

L["settings.controller.misc"] = "Misc"
L["settings.controller.misc.desc"] = "dewe should be button that will open panel with advanced contwollew config, but fow now it is in  spawnmenu > Options > AwC9 > Contwollew"
L["settings.controller.controller.title"] = "Contwollew Glyphs"
L["settings.controller.controller.desc"] = "Enable custom contwollew-compatible glyphs, showing contwollew buttons instead of de default keys"
L["settings.controller.controller_rumble.title"] = "Wumble"
L["settings.controller.controller_rumble.desc"] = "Enabwe contwowwew wumble as wong as Fesiug's DLL mod is loaded.\n\ngithub.com/Fesiug/\ngmod-sinput"
L["settings.controller.controller_config.title"] = "Advanced config"
L["settings.controller.controller_config.content"] = "Open panel"
L["settings.controller.controller_config.desc"] = "Open advanced contwollew configuwation panel"

L["settings.controller.glyphs.title"] = "Gwyph Type"
L["settings.controller.glyphs.desc"] = "Change which famiwy of gwyphs to uuse..\nSet uwp gwyphs in \"Spawnmenu\" > Owoptions > AWC9 > Contwowwew."

////////////////////// Aim Assist
L["settings.tabname.aimassist"] = "Awim Asist :3"
L["settings.tabname.aimassist.desc"] = "You can enabwe aim assistance if you might have twouble keeping youw aim on youw tawget, ow if you just pwefew to not put effowt into shooting youw tawgets."

L["settings.aimassist.enable.title"] = "Enabwe Awim Assist"
L["settings.aimassist.enable.desc"] = "Enabwes an aim assistance weatuwe dat mowes ur aim towawds a tawget wen awiming neaw dem.\n\nDis is a sewvew wawiable.\n\nWequires Awim Assist to be enabwed on CWIENT."

L["settings.aimassist.enable_general.desc"] = "Enabwes an awim assiwstance featuwe dat mowes us awim towawds a tawget when awiming neaw dem.\n\nConfiguwe it in de \"Awim Assist\" tab."

L["settings.aimassist.enable_client.desc"] = "Enables an aim assist featuwe that slows down youw sensitivity when aiming ovew a valid tawget.\n\nAlso wequiwes Aim Assist to be enabled on SEWWEW."

L["settings.aimassist.intensity.title"] = "Intensity"
L["settings.aimassist.intensity.desc"] = "How intense de aim assist is.\n\ndis is a sewwew wawiableh."

L["settings.aimassist.cone.title"] = "Cowone"
L["settings.aimassist.cone.desc"] = "How close ow faw away you need to look towawds a tawget befowe de aim assist engages.\n\ndis is a sewwew wawiableh."

L["settings.aimassist.head.title"] = "Lowck owonto snouts"
L["settings.aimassist.head.desc"] = "If de aim assist should lock onto de tawgets snout instead of its chest.\n\ndis is a sewwew wawiableh."

L["settings.aimassist.sensmult.desc"] = "Multipwy de lowok sensitivity by dis amount wen hovewing ovew a wawid tawget.\nDe wower de walue, de wower de sensitivity."

////////////////////// Asset Caching
L["settings.tabname.caching"] = "Awwet Cashwing :3"
L["settings.caching.title"] = "Awwet Cawwing uwu"
L["settings.caching.desc"] = "Youw can cawhe some AWC9 awwets (sawe in memowy wwidout woading wwile plawing owo) to pwewent stuttews fow comwowt gameplay uwu\n\nYwou suwely shouwd enable some stuww iw youw gmod wunning on HDD :3"

L["settings.caching.precache_sounds_onfirsttake.title"] = "On fiwst take: Cawhe gun sounds"
L["settings.caching.precache_sounds_onfirsttake.desc"] = "Cawhes aww sounds only fwom gun you just took in hands (excewt weload sounds owo \n\nNow any impactwul, wadew helpful to pwevent stuttews while fiwing owo"

L["settings.caching.precache_attsmodels_onfirsttake.title"] = "On fiwst take: Cawhe aww awatachmenws"
L["settings.caching.precache_attsmodels_onfirsttake.desc"] = "Cawhes aww AWC9 awatachmenws models when any AWC9 uwuweapon was taken in hands uwu\n\nCauses pwetty big fweeze uwu especiawwy when you have lots of wweapons"
L["settings.caching.precache_wepmodels_onfirsttake.title"] = "On fiwst take: Cawhe aww wweapon models"
L["settings.caching.precache_wepmodels_onfirsttake.desc"] = "Cawhes aww AWC9 uwuweapon viewmodels when any AWC9 uwuweapon was taken in hands owo\n\nCauses w-WEALLY BIG fweeze uwu especiawwy when you have lots of wwwweapons"

L["settings.caching.precache_allsounds_onstartup.title"] = "On game stawt: Cawhe aww guns sounds"
L["settings.caching.precache_allsounds_onstartup.desc"] = "Cawhes aww sounds fwom aww guns on sewvew stawt up  (except weload sounds)\n\nNow so impactwul but anyway you bettew use fiwst option hewe uwu"
L["settings.caching.precache_attsmodels_onstartup.title"] = "On game stawt: Cawhe aww awatachmenws"
L["settings.caching.precache_attsmodels_onstartup.desc"] = "Cawhes aww AWC9 awatachmenws models on sewvew stawt up \n\nCauses pwetty big load time incwease especiawwy when you have lots of weapons >w<"
L["settings.caching.precache_wepmodels_onstartup.title"] = "On game stawt: Cawhe aww weapon models"
L["settings.caching.precache_wepmodels_onstartup.desc"] = "Cawhes aww AWC9 uwuweapons viewmodels on sewvew stawt up \n\nCauses wW-WEALLY BIG load time incwease especiawwy when you have lots of weapons awoo"

L["settings.caching.precache_allsounds.title"] = "Aww uwuweapon sounds"
L["settings.caching.precache_wepmodels.title"] = "Aww uwuweapon models"
L["settings.caching.precache_attsmodels.title"] = "Aww awtachmenws models"

L["settings.developer.cache"] = "Cawhe"

////////////////////// Developer
L["settings.tabname.developer"] = "D-dewolpew"

L["settings.developer.developer"] = "Developew Options"
L["settings.developer.dev_always_ready.title"] = "Always weady"
L["settings.developer.dev_always_ready.desc"] = "Always play \"weady\" animation when deploying a weapon.\n\ndis is a sewwew wawiableh"
L["settings.developer.dev_benchgun.title"] = "Benchgun"
L["settings.developer.dev_benchgun.desc"] = "Keep de weapon whewe it cuwrently is"
L["settings.developer.dev_crosshair.title"] = "Deww Cwosshaiw"
L["settings.developer.dev_crosshair.desc"] = "Funky looking cwosshaiw showing de exact point of aim and some useful numbews.\n\ndis is a sewwew wawiableh, and only wowks fow admins - don't get cheaty with dis!"
-- L["settings.developer.dev_show_affectors.title"] = "Display Affectors"
-- L["settings.developer.dev_show_affectors.desc"] = "Displays which current affectors are currently applied.\n\nRequires \"Dev Crosshair\"."
L["settings.developer.dev_show_shield.title"] = "Showo Shield"
L["settings.developer.dev_show_shield.desc"] = "Showo de model fow de playew's shield"
L["settings.developer.dev_greenscreen.title"] = "Gween Scween"
L["settings.developer.dev_greenscreen.desc"] = "Showo a gween scween backgwound in de customisation menu fow scweenshots.\n\nIf you awe using HDR, don't fowget to set mat_bloom_scalefactor_scalar to 0!"
L["settings.developer.reloadatts.title"] = "Weload awatachmenws"
L["settings.developer.reloadlangs.title"] = "Weload Languages"
L["settings.developer.dev_listmyatts.title"] = "List My awatachmenws"
L["settings.developer.dev_listanims.title"] = "List Anims"
L["settings.developer.dev_listbones.title"] = "List Bones"
L["settings.developer.dev_listbgs.title"] = "List Bodygwoups"
L["settings.developer.dev_listatts.title"] = "List QCawatachmenws"
L["settings.developer.dev_export.title"] = "Get ExpoWt Code"
L["settings.developer.dev_getjson.title"] = "Get Weapon JSON"

L["settings.developer.presets_clear.title"] = "Cleaw weapon data"
L["settings.developer.presets_clear.desc"] = "Cleaw pwesets, all icons and default pweset fow weapon you cuwwently holding.\n\nWawning: if menu opened without AwC9 weapon in hands it will delete all existing AwC9 pwesets and icons!"

L["settings.developer.clear"] = "Cleaw"
L["settings.developer.print"] = "Pwint to Console"
L["settings.developer.reload"] = "W-weload"
