L = {}

--L["font"] = "Exo Regular"

-- Language loc is actually unused so you can feel free to skip these
L["bg"] = "Bulgarian"
L["cs"] = "Czech"
L["da"] = "Danish"
L["de"] = "German"
L["el"] = "Greek"
L["en"] = "English"
L["en-pt"] = "Pirate English"
L["es-es"] = "Spanish"
L["et"] = "Estonian"
L["fi"] = "Finnish"
L["fr"] = "French"
L["he"] = "Hebrew"
L["hr"] = "Croatian"
L["hu"] = "Hungarian"
L["it"] = "Italian"
L["ja"] = "Japanese"
L["ko"] = "Korean"
L["lt"] = "Lithuanian"
L["nl"] = "Dutch"
L["no"] = "Norwegian"
L["pl"] = "Polish"
L["pt-br"] = "Portuguese (Brazil)"
L["pt-pt"] = "Portuguese (Portugal)"
L["ro"] = "Romanian"
L["ru"] = "Russian"
L["sk"] = "Slovak"
L["sv"] = "Swedish"
L["th"] = "Thai"
L["tr"] = "Turkish"
L["uk"] = "Ukrainian"
L["vi"] = "Vietnamese"
L["zh-cn"] = "Chinese (Simplified)"
L["zh-tw"] = "Chinese (Traditional)"


L["autostat.damagemax"] = "Close Range Damage"
L["autostat.damagemin"] = "Long Range Damage"
L["autostat.damagerand"] = "Damage Variance"
L["autostat.rangemin"] = "Minimum Damage Range"
L["autostat.rangemax"] = "Maximum Range"
L["autostat.distance"] = "Bullet Distance"
L["autostat.num"] = "Projectile Count"
L["autostat.penetration"] = "Material Penetration"
L["autostat.ricochetanglemax"] = "Ricochet Angle"
L["autostat.ricochetchance"] = "Ricochet Chance"
L["autostat.armorpiercing"] = "Armor Piercing"
L["autostat.entitymuzzlevelocity"] = "Projectile Muzzle Velocity"
L["autostat.physbulletmuzzlevelocity"] = "Muzzle Velocity"
L["autostat.physbulletdrag"] = "Bullet Drag"
L["autostat.physbulletgravity"] = "Bullet Drop"
L["autostat.chambersize"] = "Chamber Load Count"
L["autostat.clipsize"] = "Magazine Capacity"
L["autostat.supplylimit"] = "Reserve Magazines"
L["autostat.secondarysupplylimit"] = "Reserve Secondary Ammo"
L["autostat.ammopershot"] = "Ammo Per Shot"
L["autostat.manualactionchamber"] = "Shots Per Cycle"
L["autostat.triggerdelay"] = "Trigger Delay Time"
L["autostat.rpm"] = "Fire Rate"
L["autostat.postburstdelay"] = "Burst Delay"
L["autostat.pushbackforce"] = "Pushback Force"
L["autostat.recoil"] = "Recoil"
L["autostat.recoilpatterndrift"] = "Recoil Drift"
L["autostat.recoilup"] = "Vertical Recoil"
L["autostat.recoilside"] = "Horizontal Recoil"
L["autostat.recoilrandomup"] = "Vertical Recoil Spread"
L["autostat.recoilrandomside"] = "Horizontal Recoil Spread"
L["autostat.recoildissipationrate"] = "Recoil Dissipation Rate"
L["autostat.recoilresettime"] = "Recoil Reset Time"
L["autostat.recoilautocontrol"] = "Recoil Control"
L["autostat.recoilkick"] = "Felt Recoil"
L["autostat.spread"] = "Spread"
L["autostat.pelletspread"] = "Clump Spread"
L["autostat.freeaimradius"] = "Free Aim Radius"
L["autostat.sway"] = "Sway"
L["autostat.aimdownsightstime"] = "Aim Down Sights Time"
L["autostat.sprinttofiretime"] = "Sprint To Fire Time"
L["autostat.reloadtime"] = "Reload Time"
L["autostat.deploytime"] = "Draw Time"
L["autostat.cycletime"] = "Cycle Time"
L["autostat.fixtime"] = "Unjam Time"
L["autostat.overheattime"] = "Overheat Fix Time"
L["autostat.speed"] = "Movement Speed"
L["autostat.bashdamage"] = "Melee Damage"
L["autostat.bashrange"] = "Melee Range"
L["autostat.bashlungerange"] = "Melee Lunge Range"
L["autostat.heatcapacity"] = "Heat Capacity"
L["autostat.heatdissipation"] = "Heat Dissipation"
L["autostat.malfunctionmeanshotstofail"] = "Mean Shots Between Failures"
L["autostat.shootvolume"] = "Report Volume"
L["autostat.alwaysphysbullet"] = "Always Physical Bullets"
L["autostat.neverphysbullet"] = "Non-Physical Bullets"
L["autostat.infiniteammo"] = "Infinite Ammunition"
L["autostat.bottomlessclip"] = "Bottomless Magazine"
L["autostat.shotgunreload"] = "Individual Reloading"
L["autostat.hybridreload"] = "Hybrid Individual Reloading"
L["autostat.manualaction"] = "Manual Action"
L["autostat.canfireunderwater"] = "Underwater Shooting"
L["autostat.autoreload"] = "Idle Reloading"
L["autostat.autoburst"] = "Automatic Burst Fire"
L["autostat.runawayburst"] = "Runaway Burst"
L["autostat.shootwhilesprint"] = "Shoot While Sprinting"
L["autostat.bash"] = "Melee Attacks"
L["autostat.overheat"] = "Overheating"
L["autostat.malfunction"] = "Jamming"
L["autostat.malfunctionwait"] = "Malfunction Wait Time"
L["autostat.bipod"] = "Bipod"
L["autostat.noflash"] = "No Muzzle Flash"
L["autostat.bulletguidance"] = "Guided Rounds"
L["autostat.bulletguidanceamount"] = "Guidance Factor"
L["autostat.heatpershot"] = "Heat Per Shot"
L["autostat.explosiondamage"] = "Explosion Damage"
L["autostat.explosionradius"] = "Explosion Splash Radius"
L["autostat.headshotdamage"] = "Headshot Damage"
L["autostat.chestdamage"] = "Chest Damage"
L["autostat.stomachdamage"] = "Stomach Damage"
L["autostat.armdamage"] = "Arm Damage"
L["autostat.legdamage"] = "Leg Damage"
L["autostat.visualrecoil"] = "Visual Recoil"
L["autostat.visualrecoilup"] = "Vertical Visual Recoil"
L["autostat.visualrecoilside"] = "Horizontal Visual Recoil"
L["autostat.visualrecoilroll"] = "Visual Recoil Roll"
L["autostat.visualrecoilpunch"] = "Visual Recoil Punch"
L["autostat.breathholdtime"] = "Focus Time"

L["autostat.secondary._beforephrase"] = false -- if true, secondary stat phrasing comes before the stat
L["autostat.secondary._divider"] = " " -- space between the secondary phrase from the stat phrase. set true to use empty string

L["autostat.secondary.true"] = "when TrueNames is on"
L["autostat.secondary.silenced"] = "when Silenced"
L["autostat.secondary.midair"] = "in Mid-Air"
L["autostat.secondary.crouch"] = "while Crouching"
L["autostat.secondary.first"] = "on First Shot"
L["autostat.secondary.firstshot"] = "on First Shot"
L["autostat.secondary.last"] = "on Last round in mag"
L["autostat.secondary.lastshot"] = "on Last round in mag"
L["autostat.secondary.empty"] = "on Last round in mag"
L["autostat.secondary.evenshot"] = "every Even Shot"
L["autostat.secondary.oddshot"] = "every Odd Shot"
L["autostat.secondary.evenreload"] = "every Even Reload"
L["autostat.secondary.oddreload"] = "every Odd Reload"
L["autostat.secondary.sights"] = "in Sights"
L["autostat.secondary.hipfire"] = "in Hipfire"
L["autostat.secondary.shooting"] = "while Shooting"
L["autostat.secondary.recoil"] = "from Recoil" --"With Each Shot"
L["autostat.secondary.move"] = "while Moving"
L["autostat.secondary.blindfire"] = "while Blind-Firing" -- No longer exists, you can skip this line
L["autostat.secondary.ubgl"] = "in UBGL"

L["unit.second"] = "s"
L["unit.meter"] = "m"
L["unit.millimeter"] = "mm"
L["unit.meterpersecond"] = "m/s"
L["unit.hammerunit"] = "HU"
L["unit.decibel"] = "dB"
L["unit.rpm"] = "RPM"
L["unit.moa"] = "MOA"
L["unit.dmg"] = "DMG"
L["unit.projectiles"] = "PROJ"

L["hud.firemode.single"] = "SINGLE"
L["hud.firemode.burst"] = "BURST"
L["hud.firemode.auto"] = "AUTO"
L["hud.firemode.safe"] = "SAFE"

L["hud.version"] = "ARCTIC SYSTEMS HUD v"
L["hud.jammed"] = "JAMMED!"
L["hud.therm_deco"] = "BARREL TEMP"

L["hud.hint.ubgl"] = "Toggle"
L["hud.hint.switchsights"] = "Switch Sights"
L["hud.hint.zoom"] = "Change Zoom"
L["hud.hint.breath"] = "Hold Breath"
L["hud.hint.bash"] = "Bash"
L["hud.hint.inspect"] = "Inspect"
L["hud.hint.switchsights"] = "Switch Sights"
L["hud.hint.firemode"] = "Switch Firemode"
L["hud.hint.cycle"] = "Cycle"
L["hud.hint.toggleatts"] = "Toggle Attachments"
L["hud.hint.peek"] = "Peek"
L["hud.hint.customize"] = "Customize"
L["hud.hint.safe"] = "Toggle Safe"
L["hud.hint.lean"] = "Lean"

L["autostat.enable.pre"] = "Enables"
L["autostat.disable.pre"] = "Disables"
L["autostat.enable.post"] = ""
L["autostat.disable.post"] = ""

L["ammo.pistol"] = "Pistol Ammo"
L["ammo.357"] = "Magnum Ammo"
L["ammo.smg1"] = "Carbine Ammo"
L["ammo.ar2"] = "Rifle Ammo"
L["ammo.buckshot"] = "Shotgun Ammo"
L["ammo.sniperpenetratedround"] = "Sniper Ammo"
L["ammo.smg1_grenade"] = "Rifle Grenades"

L["customize.panel.customize"] = "CUSTOMIZE"
L["customize.panel.personalize"] = "PERSONALIZE"
L["customize.panel.stats"] = "STATS & BALLISTICS"
L["customize.panel.trivia"] = "TRIVIA"
L["customize.panel.inspect"] = "INSPECT"
L["customize.panel.presets"] = "Presets"

L["customize.stats.firepower"] = "Firepower"
L["customize.stats.rof"] = "ROF"
L["customize.stats.cyclic"] = "Cyclic ROF"
L["customize.stats.capacity"] = "Capacity"
L["customize.stats.range"] = "Range"
L["customize.stats.precision"] = "Precision"
L["customize.stats.muzzlevelocity"] = "Muzzle Velocity"
L["customize.stats.ammo"] = "Ammo Type"
L["customize.stats.penetration"] = "Penetration"
L["customize.stats.ricochet"] = "Ricochet Chance"
L["customize.stats.armorpiercing"] = "Armor Piercing"
L["customize.stats.explosive"] = "Explosive Damage"
L["customize.stats.speed"] = "Movement Speed"
L["customize.stats.aimtime"] = "Aim Time"
L["customize.stats.sprinttofire"] = "Sprint to Fire Time"
L["customize.stats.firemodes"] = "Fire Modes"
L["customize.stats.burstdelay"] = "Burst Delay"
L["customize.stats.triggerdelay"] = "Trigger Delay"
L["customize.stats.noise"] = "Noise"
L["customize.stats.sway"] = "Sway"
L["customize.stats.freeaim"] = "Free Aim Radius"
L["customize.stats.supplylimit"] = "Supply Limit"

L["customize.hint.controller"] = "Controller Mode is on."
L["customize.hint.expand"] = "Expand"
L["customize.hint.attach"] = "Attach"
L["customize.hint.unattach"] = "Unattach"
L["customize.hint.recenter"] = "Recenter"
L["customize.hint.rotate"] = "Rotate"
L["customize.hint.pan"] = "Pan"
L["customize.hint.zoom"] = "Zoom"
L["customize.hint.select"] = "Select"
L["customize.hint.deselect"] = "Deselect"
L["customize.hint.cycle"] = "Cycle Slot"
L["customize.hint.last"] = "Last Slot"
L["customize.hint.cursor"] = "Cursor"
L["customize.hint.recalculate"] = "Recalculate"
L["customize.hint.nextmode"] = "Next Mode"
L["customize.hint.lastmode"] = "Last Mode"
L["customize.hint.save"] = "Save"
L["customize.hint.quicksave"] = "Quicksave"
L["customize.hint.import"] = "Import"
L["customize.hint.install"] = "Install"
L["customize.hint.export"] = "Export"
L["customize.hint.delete"] = "Delete"
L["customize.hint.open"] = "Open"

L["customize.trivia.description"] = "Description"

L["folder.deselect"] = "Deselect"
L["folder.select"] = "Select"
L["folder.back"] = "Back"

L["customize.bench.dummy"] = "BALLISTICS DUMMY TEST"
L["customize.bench.effect"] = "EFFECT AT RANGE"
L["customize.bench.ballistics"] = "TERMINAL BALLISTICS PERFORMANCE EVALUATION"
L["customize.bench.precision"] = "MECHANICAL PRECISION TEST"

L["settings.title"] = "ARC9 Settings"
L["settings.desc"] = "Description"

L["settings.tabname.performance"] = "Performance"
L["settings.tabname.optics"] = "Optics"
L["settings.tabname.crosshair"] = "Crosshair"
L["settings.tabname.hud_cust"] = "Customization"
L["settings.tabname.hud_game"] = "Game HUD"
L["settings.tabname.npc"] = "NPCs"
L["settings.tabname.gameplay"] = "Gameplay"
L["settings.tabname.visuals"] = "Visuals"
L["settings.tabname.bullets"] = "Bullet Physics"
L["settings.tabname.attachments"] = "Attachments"
L["settings.tabname.modifiers"] = "Modifiers"
L["settings.tabname.controller"] = "Controller"
L["settings.tabname.developer"] = "Developer"


L["settings.cheapscopes.title"] = "Cheap Scopes"
L["settings.cheapscopes.desc"] = "A cheap RT scope implementation by zooming your whole view to aim, instead of rendering world again in a scope. Significantly increases performance on large maps."
L["settings.allflash.title"] = "All Flashlights"
L["settings.allflash.desc"] = "Fully render all flashlights from other players.\n\nVery expensive on servers."
L["settings.tpik.title"] = "TPIK"
L["settings.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) is a system that allows most weapons display detailed and same as in first person hands positions, reload and firing animations in third person.\n\nConfigure it in Visuals tab."
L["settings.cust_blur.title"] = "Customization Background"
L["settings.cust_blur.desc"] = "Blurs customization background."
L["settings.fx_reloadblur.title"] = "While Reloading"
L["settings.fx_reloadblur.desc"] = "Blurs the world while reloading."
L["settings.fx_animblur.title"] = "While readying"
L["settings.fx_animblur.desc"] = "Blurs the world while deploying a weapon for the first time."
L["settings.fx_rtblur.title"] = "In Scopes"
L["settings.fx_rtblur.desc"] = "Blurs the world while using a magnified scope."
L["settings.fx_adsblur.title"] = "In Sights"
L["settings.fx_adsblur.desc"] = "Blurs the weapon while aiming down sights."
L["settings.eject_fx.title"] = "Smoke Effects"
L["settings.eject_fx.desc"] = "Produce smoke effects from ejected shell casings, where the weapon supports this feature"
L["settings.eject_time.title"] = "Add Life Time"
L["settings.eject_time.desc"] = "Allow shell casings to stay in the world for longer. Can be expensive."

-- Use this method to localize convars in settings menu:
-- settings.convar.title = "Convar Title"
-- settings.convar.desc = "Convar Description"

L["settings.developer.developer"] = "Developer Options"
L["settings.attachments.inventory"] = "Inventory"
L["settings.attachments.customization"] = "Customization"
L["settings.bullets.bullets"] = "Bullet Physics"
L["settings.visuals.tpik"] = "TPIK"
L["settings.visuals.viewmodel"] = "Viewmodel"
L["settings.gameplay.mechanics"] = "Game Mechanics"
L["settings.gameplay.controls"] = "Controls"
L["settings.npc.weapons"] = "NPC Weapons"
L["settings.hud_game.breath"] = "Breath"
L["settings.hud_game.killfeed"] = "Killfeed"
L["settings.hud_game.lcd"] = "LCD Panel"
L["settings.hud_cust.customization"] = "Customization"
L["settings.hud_cust.hud"] = "HUD"
L["settings.crosshair.crosshair"] = "Crosshair"
L["settings.optics.color"] = "Color"
L["settings.optics.control"] = "Control"
L["settings.performance.important"] = "Important"
L["settings.performance.blur.title"] = "Blur"
L["settings.performance.shelleject.title"] = "Shell Eject"

L["settings.optics.cheapscopes.title"] = "Cheap Scopes"
L["settings.optics.cheapscopes.desc"] = "A cheap RT scope implementation by zooming your whole view to aim, instead of rendering world again in a scope. Significantly increases performance on large maps."
L["settings.optics.compensate_sens.title"] = "Compensate Sensitivity"
L["settings.optics.compensate_sens.desc"] = "Compensate sensitivity for magnification."
L["settings.optics.toggleads.title"] = "Toggle ADS"
L["settings.optics.toggleads.desc"] = "Aiming will toggle sights."
L["settings.optics.reflex.title"] = "Reflex Sights"
L["settings.optics.reflex.desc"] = "Color to use for reflex/holographic sights.\n\nNot all optics support this feature."
L["settings.optics.scope.title"] = "Scopes"
L["settings.optics.scope.desc"] = "Color to use for magnified scopes.\n\nNot all optics support this feature."

L["settings.crosshair.cross_enable.title"] = "Enable Crosshair"
L["settings.crosshair.cross_enable.desc"] = "Enable crosshair. Some guns do not allow you to use the crosshair."
L["settings.crosshair.cross.title"] = "Crosshair Color"
L["settings.crosshair.cross.desc"] = "The color of your crosshair."
L["settings.crosshair.cross_size_mult.title"] = "Crosshair Size"
L["settings.crosshair.cross_size_mult.desc"] = "Multiply the size of your crosshair."
L["settings.crosshair.cross_size_dot.title"] = "Dot Size"
L["settings.crosshair.cross_size_dot.desc"] = "Multiply the size of the middle dot."
L["settings.crosshair.cross_size_prong.title"] = "Prong Size"
L["settings.crosshair.cross_size_prong.desc"] = "Multiply the size of the outer prongs."
L["settings.crosshair.crosshair_static.title"] = "Static Crosshair"
L["settings.crosshair.crosshair_static.desc"] = "Enable static crosshair, which does not move when shooting."
L["settings.crosshair.crosshair_force.title"] = "Force Crosshair"
L["settings.crosshair.crosshair_force.desc"] = "Force the crosshair even on guns that don't want you to see it.\n\nServer setting."

L["settings.hud_cust.hud_scale.title"] = "HUD Scale"
L["settings.hud_cust.hud_scale.desc"] = "Scale multiplier for ARC9's HUD."
L["settings.hud_cust.hud_color.title"] = "HUD Color"
L["settings.hud_cust.hud_color.desc"] = "Highlight color for the HUD.\nThe accent color."
L["settings.hud_cust.language_id.title"] = "Language"
L["settings.hud_cust.language_id.desc"] = "Language pack to use for ARC9."
L["settings.hud_cust.cust_light.title"] = "Enable Light"
L["settings.hud_cust.cust_light.desc"] = "Enables gun lighting in the customization menu.\n\nSame thing as button near settings button."
L["settings.hud_cust.cust_light_brightness.title"] = "Light Brightness"
L["settings.hud_cust.cust_light_brightness.desc"] = "How bright that light in the customization panel will be.\n\nDon't forget to turn it on first though!"
L["settings.hud_cust.cust_hints.title"] = "Hints"
L["settings.hud_cust.cust_hints.desc"] = "Enable hints in the customization menu."
L["settings.hud_cust.cust_roll_unlock.title"] = "Unlock Roll" -- NOT USED ANYMORE
L["settings.hud_cust.cust_roll_unlock.desc"] = "Allow weapon roll in the customization menu.\n\nMight look and control not the best way." -- NOT USED ANYMORE
L["settings.hud_cust.cust_exit_reset_sel.title"] = "Exit Resets Selection"
L["settings.hud_cust.cust_exit_reset_sel.desc"] = "Exiting customization menu resets the active slot selection."

L["settings.hud_game.hud_arc9.title"] = "Enable HUD"
L["settings.hud_game.hud_arc9.desc"] = "Enable HUD for ARC9 weapons."
L["settings.hud_game.hud_always.title"] = "On all weapons"
L["settings.hud_game.hud_always.desc"] = "Enable that HUD on all weapons."
L["settings.hud_game.hud_compact.title"] = "Compact Mode"
L["settings.hud_game.hud_compact.desc"] = "Compact appearance for the HUD panel."
L["settings.hud_game.hud_keephints.title"] = "Keep Hints"
L["settings.hud_game.hud_keephints.desc"] = "Show the ARC9 control hints on top on HUD panel."
L["settings.hud_game.killfeed_enable.title"] = "Killfeed Icons"
L["settings.hud_game.killfeed_enable.desc"] = "Enable auto-generation of killfeed icons for ARC9 guns."
L["settings.hud_game.killfeed_dynamic.title"] = "Dynamic updating"
L["settings.hud_game.killfeed_dynamic.desc"] = "Killfeed icons will be regenerated after each kill.\n\nTurn off if you want get that 0.1 fps."
L["settings.hud_game.breath_hud.title"] = "Breath HUD"
L["settings.hud_game.breath_hud.desc"] = "Show a bar that displays your remaining breath while stabilizing your gun in sights."
L["settings.hud_game.breath_pp.title"] = "Breath Post-Process"
L["settings.hud_game.breath_pp.desc"] = "Holding breath will also add post-processing effects to your screen."
L["settings.hud_game.breath_sfx.title"] = "Breath SFX"
L["settings.hud_game.breath_sfx.desc"] = "Holding breath will play associated sound effects."

L["settings.npc.npc_equality.title"] = "Damage Equality"
L["settings.npc.npc_equality.desc"] = "NPCs do just as much damage as players do.\n\nThis is a server variable."
L["settings.npc.npc_atts.title"] = "Give Attachments"
L["settings.npc.npc_atts.desc"] = "Spawned or given ARC9 weapons receive a random set of attachments.\n\nThis is a server variable."
L["settings.npc.npc_autoreplace.title"] = "Replace NPC Weapons"
L["settings.npc.npc_autoreplace.desc"] = "Replace NPC weapons with randomly chosen ARC9 weapons.\n\nThis is a server variable."
L["settings.npc.replace_spawned.title"] = "Replace Ground Weapons"
L["settings.npc.replace_spawned.desc"] = "Replace map/spawned HL2 weapons with randomly chosen ARC9 weapons.\n\nThis is a server variable."
L["settings.npc.npc_give_weapons.title"] = "Players Can Give Weapons"
L["settings.npc.npc_give_weapons.desc"] = "Players are able to press E on NPCs to give them their weapon.\n\nThis is a server variable."

L["settings.gameplay.toggleads.title"] = "Toggle ADS"
L["settings.gameplay.toggleads.desc"] = "Aiming will toggle sights."
L["settings.gameplay.autolean.title"] = "Automatic Lean"
L["settings.gameplay.autolean.desc"] = "Aiming will try to automatically lean if this is possible."
L["settings.gameplay.autoreload.title"] = "Automatic Reload"
L["settings.gameplay.autoreload.desc"] = "Empty ARC9 weapons will reload automatically."
L["settings.gameplay.infinite_ammo.title"] = "Infinite Ammo"
L["settings.gameplay.infinite_ammo.desc"] = "Weapons have infinite ammunition.\n\nThis is a server variable."
L["settings.gameplay.realrecoil.title"] = "Physical Visual Recoil"
L["settings.gameplay.realrecoil.desc"] = "Select weapons set up for this feature experience physical muzzle rise, meaning they will fire where their viewmodel shows it rather than at the center of the screen. Very important for some weapon packs' balancing schemes.\n\nThis is a server variable."
L["settings.gameplay.lean.title"] = "Leaning"
L["settings.gameplay.lean.desc"] = "Whether players can lean with +alt1 and +alt2, including automatic lean.\n\nThis is a server variable."
L["settings.gameplay.mod_sway.title"] = "Sway"
L["settings.gameplay.mod_sway.desc"] = "Weapons will have sway, if they are set up to use it.\n\nThis is a server variable."
L["settings.gameplay.mod_freeaim.title"] = "Free Aim"
L["settings.gameplay.mod_freeaim.desc"] = "Weapons will have free aim, and will not always shoot in the middle of the screen.\n\nThis is a server variable."
L["settings.gameplay.mod_bodydamagecancel.title"] = "Body Damage Cancel"
L["settings.gameplay.mod_bodydamagecancel.desc"] = "Cancel out default body damage multiplier. Only disable if using another mod that provides this type of functionality.\ne.g. Mods which change the default limb multipliers.\n\nThis is a server variable."
L["settings.gameplay.breath_slowmo.title"] = "Slow-Mo Breath"
L["settings.gameplay.breath_slowmo.desc"] = "Holding breath slows time.\n\nSingleplayer only."
L["settings.gameplay.manualbolt.title"] = "Manual Cycling"
L["settings.gameplay.manualbolt.desc"] = "Bolt-action weapons configured for this feature will only bolt when R is pressed, and not when the attack key is released."
L["settings.gameplay.nearwall.title"] = "Near-walling"
L["settings.gameplay.nearwall.desc"] = "Not allow gun shoot when you standing too close to wall or any obstacle."

L["settings.visuals.vm_bobstyle.title"] = "Bob Style"
L["settings.visuals.vm_bobstyle.desc"] = "Select different bobbing styles, to the flavor of different members of the ARC9 team (and valve software), going from most newest style to oldest one."
L["settings.visuals.fov.title"] = "FOV"
L["settings.visuals.fov.desc"] = "Add viewmodel FOV. Makes the viewmodel bigger or smaller. Use responsibly."
L["settings.visuals.vm_addx.title"] = "Add X"
L["settings.visuals.vm_addx.desc"] = "Shift the viewmodel to the right or left."
L["settings.visuals.vm_addy.title"] = "Add Y"
L["settings.visuals.vm_addy.desc"] = "Shift the viewmodel forwards and backwards."
L["settings.visuals.vm_addz.title"] = "Add Z"
L["settings.visuals.vm_addz.desc"] = "Shift the viewmodel up and down."
L["settings.visuals.tpik.title"] = "Enable TPIK"
L["settings.visuals.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) is a system that allows most weapons display detailed and same as in first person hands positions, reload and firing animations in third person."
L["settings.visuals.tpik_others.title"] = "Other Players TPIK"
L["settings.visuals.tpik_others.desc"] = "Show TPIK for players other than yourself. Negatively impacts performance."
L["settings.visuals.tpik_framerate.title"] = "TPIK Framerate"
L["settings.visuals.tpik_framerate.desc"] = "Maximum framerate at which TPIK can run. Set to 0 for unlimited."

L["settings.bullets.bullet_physics.title"] = "Physical Bullets"
L["settings.bullets.bullet_physics.desc"] = "Weapons that support this feature will fire physical bullets, which have drop, travel time, and drag.\n\nThis is a server variable."
L["settings.bullets.bullet_gravity.title"] = "Gravity"
L["settings.bullets.bullet_gravity.desc"] = "Multiplier for bullet gravity.\n\nThis is a server variable."
L["settings.bullets.bullet_drag.title"] = "Drag"
L["settings.bullets.bullet_drag.desc"] = "Multiplier for bullet drag.\n\nThis is a server variable."
L["settings.bullets.ricochet.title"] = "Ricochet"
L["settings.bullets.ricochet.desc"] = "Bullets fired from select weapons can sometimes bounce off of surfaces and continue to travel and do damage.\n\nThis is a server variable."
L["settings.bullets.mod_penetration.title"] = "Penetration"
L["settings.bullets.mod_penetration.desc"] = "Bullets fired from select weapons can penetrate surfaces and deal damage to whatever is on the other side.\n\nThis is a server variable."
L["settings.bullets.bullet_lifetime.title"] = "Life Time"
L["settings.bullets.bullet_lifetime.desc"] = "Time in seconds after which a bullet will be deleted.\n\nThis is a server variable."
L["settings.bullets.bullet_imaginary.title"] = "Imaginary Bullets"
L["settings.bullets.bullet_imaginary.desc"] = "Bullets will appear to travel into the skybox, beyond the map's bounds."

L["settings.attachments.atts_nocustomize.title"] = "Disable Customization"
L["settings.attachments.atts_nocustomize.desc"] = "Disallow all customization via the customization menu.\n\nThis is a server variable."
L["settings.attachments.atts_max.title"] = "Max Attachments"
L["settings.attachments.atts_max.desc"] = "The maximum number of attachments that can be put on a weapon, including cosmetic attachments.\n\nThis is a server variable."
L["settings.attachments.autosave.title"] = "Autosave"
L["settings.attachments.autosave.desc"] = "Your last weapon customization options will be saved and automatically applied the next time you spawn that weapon."
L["settings.attachments.free_atts.title"] = "Free Attachments"
L["settings.attachments.free_atts.desc"] = "Attachments can be used without being picked up first.\n\nThis is a server variable."
L["settings.attachments.atts_lock.title"] = "One For All"
L["settings.attachments.atts_lock.desc"] = "Picking up one instance of an attachments allows you to use it infinite times on all your guns.\n\nThis is a server variable."
L["settings.attachments.atts_loseondie.title"] = "Lose On Death"
L["settings.attachments.atts_loseondie.desc"] = "Your attachment inventory will be lost when you die.\n\nThis is a server variable."
L["settings.attachments.atts_generateentities.title"] = "Generate Entities"
L["settings.attachments.atts_generateentities.desc"] = "Generate entities that can be spawned, allowing you to pick up attachments when free attachments is off.\n\nMight increase load time.\n\nThis is a server variable."


L["settings.modifiers.quick.title"] = "Quick Stats Modifiers"
-- wawa
L["settings.modifiers.quick.desc"] = "We are a little sorry but we couldn't finish them to release. You will have to use advanced modifiers in  spawnmenu > Options > ARC9 > Modifiers  for now."

L["settings.controller.misc"] = "Misc"
L["settings.controller.misc.desc"] = "There should be button that will open panel with advanced controller config, but for now it is in  spawnmenu > Options > ARC9 > Controller."
L["settings.controller.controller.title"] = "Controller Glyphs"
L["settings.controller.controller.desc"] = "Enable custom controller-compatible glyphs, showing controller buttons instead of the default keys."
L["settings.controller.controller_rumble.title"] = "Rumble"
L["settings.controller.controller_rumble.desc"] = "Enable controller rumble as long as Fesiug's DLL mod is loaded.\n\ngithub.com/Fesiug/\ngmod-sinput"
L["settings.controller.controller_config.title"] = "Advanced config"
L["settings.controller.controller_config.content"] = "Open panel"
L["settings.controller.controller_config.desc"] = "Open advanced controller configuration panel."

L["settings.developer.dev_always_ready.title"] = "Always Ready"
L["settings.developer.dev_always_ready.desc"] = "Always play \"ready\" animation when deploying a weapon.\n\nThis is a server variable."
L["settings.developer.dev_benchgun.title"] = "Benchgun"
L["settings.developer.dev_benchgun.desc"] = "Keep the weapon where it currently is."
L["settings.developer.dev_show_shield.title"] = "Show Shield"
L["settings.developer.dev_show_shield.desc"] = "Show the model for the player's shield."

L["settings.developer.print"] = "Print to Console"
L["settings.developer.reload"] = "Reload"

L["settings.developer.reloadatts.title"] = "Reload Attachments"
L["settings.developer.reloadlangs.title"] = "Reload Languages"
L["settings.developer.dev_listanims.title"] = "List Anims"
L["settings.developer.dev_listbones.title"] = "List Bones"
L["settings.developer.dev_listbgs.title"] = "List Bodygroups"
L["settings.developer.dev_listatts.title"] = "List QCAttachments"
L["settings.developer.dev_export.title"] = "Get Export Code"
L["settings.developer.dev_getjson.title"] = "Get Weapon JSON"


L["incompatible.title"] = "ARC9: INCOMPATIBLE ADDONS"
L["incompatible.line1"] = "You have some addons that are known to not work with ARC9."
L["incompatible.line2"] = "Disable them or expect broken behavior!"
L["incompatible.confirm"] = "Acknowledge"
L["incompatible.wait"] = "Wait {time}s"
L["incompatible.never"] = "Never warn me again"
L["incompatible.never.hover"] = "Are you absolutely sure you understand the consequences?"
L["incompatible.never.confirm"] = "You have chosen to never show incompatiblity warnings again. If you encounter errors or broken behaviour, it is your own responsibility."


L["customize.presets.default"] = "Default"
L["customize.presets.default.long"] = "Default preset"
L["customize.presets.random"] = "Random"
L["customize.presets.atts"] = " Attachments"
L["customize.presets.save"] = "Save"
L["customize.presets.import"] = "Import"
L["customize.presets.new"] = "New Preset Name"
L["customize.presets.code"] = "Preset Code (Copied to Clipboard)"
L["customize.presets.paste"] = "Paste Preset Code Here"
L["customize.presets.back"] = "Back"
L["customize.presets.cancel"] = "Cancel"
L["customize.presets.dumb"] = "Are you dumb"
L["customize.presets.invalid"] = "Invalid string!"

-- Added 02-JAN-2023

L["settings.gameplay.togglepeek.title"] = "Toggle Peek"
L["settings.gameplay.togglepeek.desc"] = "Pressing the peek key will toggle peeking instead of needing to be held down."

L["settings.npc.npc_spread.title"] = "NPC Spread"
L["settings.npc.npc_spread.desc"] = "Multiplier for how inaccurate NPCs will be when firing."

-- Modified/Added 03-JAN-2023

L["settings.gameplay.togglelean.title"] = "Toggle Lean"
L["settings.gameplay.togglelean.desc"] = "Pressing the lean keys will toggle leaning instead of needing to be held down.\n\nWorks poorly in conjunction with autolean. If using toggle lean, you should disable autolean."

L["settings.developer.presets_clear.title"] = "Clear weapon data"
L["settings.developer.presets_clear.desc"] = "Clear presets, all icons and default preset for weapon you currently holding.\n\nWarning: if menu opened without ARC9 weapon in hands it will delete all existing ARC9 presets and icons!"
L["settings.developer.clear"] = "Clear"

L["atts.favourites"] = "Favourites"
L["atts.filter"] = "Filter"
L["customize.hint.favorite"] = "Favorite"
L["customize.hint.unfavorite"] = "Remove Favorite"

L["customize.presets.unnamed"] = "Unnamed"
L["folder.favorites"] = "Favorites"

-- Added 04-JAN-2023

L["settings.gameplay.never_ready.title"] = "No Ready Anims"
L["settings.gameplay.never_ready.desc"] = "Disable ready animations when deploying a weapon."