L = {}

/////////////////////////////////////// Font
////////////////////// See "font_en" file

/////////////////////////////////////// General
////////////////////// Units of measurement
L["unit.second"] = "s"
L["unit.meter"] = "m"
L["unit.millimeter"] = "mm"
L["unit.meterpersecond"] = "m/s"
L["unit.hammerunit"] = "H-E"
L["unit.decibel"] = "dB"
L["unit.rpm"] = "SPM"
L["unit.moa"] = "BM"
L["unit.dmg"] = "SKD"
L["unit.projectiles"] = "PROJ"

////////////////////// Ammo types
L["ammo.pistol"] = "Pistol Ammo"
L["ammo.357"] = "Magnum Ammo"
L["ammo.smg1"] = "Karbin Ammo"
L["ammo.ar2"] = "Gevärs Ammo"
L["ammo.buckshot"] = "Hagelbössa Ammo"
L["ammo.sniperpenetratedround"] = "Prickskytt. Ammo"
L["ammo.smg1_grenade"] = "Gevärsgranater"
L["ammo.xbowbolt"] = "Armborstpilar"
L["ammo.rpg_round"] = "Raketer"
L["ammo.grenade"] = "Granater"
L["ammo.slam"] = "SLAM"
L["ammo.alyxgun"] = "Alyxs Vapenammo"

/////////////////////////////////////// HUD
L["hud.version"] = "ARCTIC SYSTEMS HUD v"
L["hud.jammed"] = "STOPPAD!"
L["hud.therm_deco"] = "ELDRÖR TEMP"

L["hud.firemode.single"] = "ENKEL"
L["hud.firemode.burst"] = "SALVO"
L["hud.firemode.auto"] = "AUTO"
L["hud.firemode.safe"] = "SÄKER"

L["hud.hint.bash"] = "Närstrid"
L["hud.hint.bipod"] = "Växla Skjutstöd"
L["hud.hint.breath"] = "Håll Andan"
L["hud.hint.customize"] = "Anpassa"
L["hud.hint.cycle"] = "Cykel"
L["hud.hint.firemode"] = "Växla Skjutlägen"
L["hud.hint.inspect"] = "Inspektera"
L["hud.hint.lean"] = "Luta"
L["hud.hint.peek"] = "Kika"
L["hud.hint.reload"] = "Ladda om"
L["hud.hint.safe"] = "Växla Säkring"
L["hud.hint.switchsights"] = "Växla Sikten"
L["hud.hint.toggleatts"] = "Växla Tillbehör"
L["hud.hint.ubgl"] = "Växla"
L["hud.hint.zoom"] = "Ändra Zoom"

L["hud.hint.lowammo"] = "Låg Ammo"
L["hud.hint.noammo"] = "Ingen Ammo"

L["hud.error.missingbind"] = "\" %s \" ej bunden"

/////////////////////////////////////// Customization menu
L["customize.panel.customize"] = "ANPASSA"
L["customize.panel.personalize"] = "PERSONALISERA"
L["customize.panel.stats"] = "STATS & BALLISTIK"
L["customize.panel.trivia"] = "TRIVIA"
L["customize.panel.inspect"] = "INSPEKTERA"
L["customize.panel.presets"] = "Förinställ."

L["customize.stats.aimtime"] = "Siktetid"
L["customize.stats.ammo"] = "Patrontyp"
L["customize.stats.armorpiercing"] = "Pansarbrytande"
L["customize.stats.burstdelay"] = "Salvo Fördröj."
L["customize.stats.capacity"] = "Kapacitet"
L["customize.stats.cyclic"] = "Cykel Eldhastighet"
L["customize.stats.explosive"] = "Explosiv Skada"
L["customize.stats.firemodes"] = "Skjutlägen"
L["customize.stats.firepower"] = "Eldkraft"
L["customize.stats.freeaim"] = "Fritt Sikte Radie"
L["customize.stats.muzzlevelocity"] = "Utgångshastighet"
L["customize.stats.noise"] = "Ljud"
L["customize.stats.penetration"] = "Penetration"
L["customize.stats.precision"] = "Precision"
L["customize.stats.range"] = "Räckvidd"
L["customize.stats.ricochet"] = "Rikoschett Chans"
L["customize.stats.rof"] = "Eldhastighet"
L["customize.stats.speed"] = "Rörelsehastighet"
L["customize.stats.sprinttofire"] = "Spring-till-Sikte Tid"
L["customize.stats.supplylimit"] = "Påfyll Begränsning"
L["customize.stats.sway"] = "Svängning"
L["customize.stats.triggerdelay"] = "Avtryckare Fördröj."

L["customize.hint.attach"] = "Sätt På"
L["customize.hint.controller"] = "Kontrollerläge är på."
L["customize.hint.cursor"] = "Pekare"
L["customize.hint.cycle"] = "Växla Plats"
L["customize.hint.delete"] = "Ta Bort"
L["customize.hint.deselect"] = "Välj Bort"
L["customize.hint.expand"] = "Expandera"
L["customize.hint.export"] = "Exportera"
L["customize.hint.favorite"] = "Favorit"
L["customize.hint.import"] = "Importera"
L["customize.hint.install"] = "Installera"
L["customize.hint.last"] = "Sista Plats"
L["customize.hint.lastmode"] = "Föreg. Läge"
L["customize.hint.nextmode"] = "Nästa Läge"
L["customize.hint.open"] = "Öppna"
L["customize.hint.pan"] = "Panorera"
L["customize.hint.quicksave"] = "Snabbspara"
L["customize.hint.randomize"] = "Sätt på Slumpmässig"
L["customize.hint.recalculate"] = "Omkalkylera"
L["customize.hint.recenter"] = "Centrera Om"
L["customize.hint.rotate"] = "Rotera"
L["customize.hint.save"] = "Spara"
L["customize.hint.select"] = "Välj"
L["customize.hint.unattach"] = "Ta Av"
L["customize.hint.unfavorite"] = "Ta bort Favorit"
L["customize.hint.zoom"] = "Zooma"

L["customize.trivia.description"] = "Beskrivning"

L["customize.stats.explain.firepower"] = "Skadepotential på närdistans."
L["customize.stats.explain.rof"] = "Vapnets eldhastighet."
L["customize.stats.explain.cyclic"] = "Vapnets cykel eldhastighet. Ignorerar faktorer som salvo fördröjning eller omladdning krav."
L["customize.stats.explain.capacity"] = "Hur mycket ammo vapnet kan hålla i magasin + slutstycket."
L["customize.stats.explain.range"] = "Räckvidden då vapnet delar ut minimum skada."
L["customize.stats.explain.precision"] = "Vapnets träffsäkerhet. Mäts i \"Minutes of Accuracy\" (MOA)."
L["customize.stats.explain.muzzlevelocity"] = "Patronernas utgångshastighet efter dem skjutits från detta vapnet."
L["customize.stats.explain.ammo"] = "Vilket sorts ammo detta vapen använder."
L["customize.stats.explain.penetration"] = "Antal material detta vapnet kan penetrera. Mäts i millimeter av träd."
L["customize.stats.explain.ricochet"] = "Maximal chans för att skott från detta vapnet ska studsa."
L["customize.stats.explain.armorpiercing"] = "Antal skada detta vapen gör som totalt ignorerar dem flesta skademotstånd."
L["customize.stats.explain.explosive"] = "Antal explosiv skada detta vapnet kommer göra."
L["customize.stats.explain.speed"] = "Hastigheten du kan förflytta dig medans du använder vapnet."
L["customize.stats.explain.aimtime"] = "Hur länge det tar att gå in i siktet från höften."
L["customize.stats.explain.sprinttofire"] = "Hur länge det tar att avsluta springning och börja skjuta."
L["customize.stats.explain.firemodes"] = "Vilka skjutlägen detta vapnet har tillgång till."
L["customize.stats.explain.burstdelay"] = "Antal tid det tar efter man skjutit en spurt innan vapnet kan skjuta igen."
L["customize.stats.explain.triggerdelay"] = "Fördröjning mellan att trycka på avtryckaren och att ett skott skjuts."
L["customize.stats.explain.noise"] = "Hur höga vapnets skott är."
L["customize.stats.explain.sway"] = "Antal svängning som tillämpas på vapnet."
L["customize.stats.explain.freeaim"] = "Maximal fritt sikte vinkel. Lägre är bättre."
L["customize.stats.explain.supplylimit"] = "Antal ammo vapnet kan motta från ARC9-ammo källor."

L["customize.bench.dummy"] = "BALLISTIK DUMMY TEST"
L["customize.bench.effect"] = "EFFEKT PÅ RÄCKVIDD"
L["customize.bench.ballistics"] = "TERMINAL BALLISTISK PRESTANDA EVALUERING"
L["customize.bench.precision"] = "MEKANISK TRÄFFSÄKERHET TEST"

L["folder.back"] = "Tillbaka"
L["folder.deselect"] = "Välj Bort"
L["folder.favorites"] = "Favoriter"
L["folder.select"] = "Välj"

////////////////////// Automatic stats
L["autostat.enable.pre"] = "Aktiverar"
L["autostat.disable.pre"] = "Avaktiverar"
L["autostat.enable.post"] = ""
L["autostat.disable.post"] = ""

L["autostat.aimassist"] = "Siktehjälp"
L["autostat.aimassiststrength"] = "Siktehjälp Styrka"
L["autostat.aimdownsightstime"] = "Res/Sänk Sikte Tid"
L["autostat.alwaysphysbullet"] = "Alltid Fysiska Skott"
L["autostat.ammopershot"] = "Ammo Per Skott"
L["autostat.armdamage"] = "Armskada"
L["autostat.armorpiercing"] = "Pansarbrytande"
L["autostat.autoburst"] = "Automatisk Salvo Eld"
L["autostat.autoreload"] = "Idle Reloading"
L["autostat.bash"] = "Närstrid Angrepp"
L["autostat.bashdamage"] = "Närstridskada"
L["autostat.bashlungerange"] = "Närstrid Longera Räckvidd"
L["autostat.bashrange"] = "Närstrid Räckvidd"
L["autostat.bashspeed"] = "Närstridshastighet"
L["autostat.bipod"] = "Skjutstöd"
L["autostat.bottomlessclip"] = "Bottenlöst Magasin"
L["autostat.breathholdtime"] = "Fokustid"
L["autostat.bulletguidance"] = "Guidade Skott"
L["autostat.bulletguidanceamount"] = "Guidande Faktor"
L["autostat.canfireunderwater"] = "Under Vatten Skjutning"
L["autostat.canpeek"] = "Kika"
L["autostat.chambersize"] = "Eldrör Laddantal"
L["autostat.chestdamage"] = "Skada till Bröstkorgen"
L["autostat.clipsize"] = "Magasinkapacitet"
L["autostat.cycletime"] = "Cykeltid"
L["autostat.damagemax"] = "Närdistans Skada"
L["autostat.damagemin"] = "Långdistans Skada"
L["autostat.damagerand"] = "Skadevariering"
L["autostat.deploytime"] = "Ta Fram Tid"
L["autostat.distance"] = "Patron Avstånd"
L["autostat.entitymuzzlevelocity"] = "Projektilens Utgångshastighet"
L["autostat.explosiondamage"] = "Explosiv Skada"
L["autostat.explosionradius"] = "Explosion Stänkradie"
L["autostat.fixtime"] = "Fixa Felfunktion Tid"
L["autostat.freeaimradius"] = "Fritt Sikte Radie"
L["autostat.headshotdamage"] = "Huvudskott Skada"
L["autostat.heatcapacity"] = "Hetta Kapacitet"
L["autostat.heatdissipation"] = "Hetta Förlust"
L["autostat.heatpershot"] = "Hetta Per Skott"
L["autostat.hybridreload"] = "Hybrid Individuell Omladdning"
L["autostat.infiniteammo"] = "Oändlig Ammo"
L["autostat.legdamage"] = "Benskada"
L["autostat.malfunction"] = "Felfunktion"
L["autostat.malfunctionmeanshotstofail"] = "Elaka Skott Mellan Fel"
L["autostat.malfunctionwait"] = "Felfunktion Väntetid"
L["autostat.manualaction"] = "Manuell Handling"
L["autostat.manualactionchamber"] = "Skott Per Cykel"
L["autostat.neverphysbullet"] = "Ej Fysiska Skott"
L["autostat.noflash"] = "Ingen Mynningseld"
L["autostat.num"] = "Antal Projektiler"
L["autostat.overheat"] = "Överhettning"
L["autostat.overheattime"] = "Överhet. Fix Tid"
L["autostat.pelletspread"] = "Klump Spridning"
L["autostat.penetration"] = "Material Penetration"
L["autostat.penetrationdelta"] = "Skada Efter Penetration"
L["autostat.physbulletdrag"] = "Skottmotstånd"
L["autostat.physbulletgravity"] = "Skott Nedsläpp"
L["autostat.physbulletmuzzlevelocity"] = "Utgångshastighet"
L["autostat.postburstdelay"] = "Salvo Fördröjning"
L["autostat.pushbackforce"] = "Tillbakatryckt Styrka"
L["autostat.rangemax"] = "Maximal Räckvidd"
L["autostat.rangemin"] = "Minimum Skade Räckvidd"
L["autostat.recoil"] = "Rekyl"
L["autostat.recoilautocontrol"] = "Rekylkontroll"
L["autostat.recoildissipationrate"] = "Rekyl Förlust Takt"
L["autostat.recoilkick"] = "Känd Rekyl"
L["autostat.recoilmodifiercap"] = "Maximal Kumulativ Rekyl"
L["autostat.recoilpatterndrift"] = "Rekyl Drift"
L["autostat.recoilpershot"] = "Rekyl per Skott"
L["autostat.recoilrandomside"] = "Horisontell Rekyl Spridning"
L["autostat.recoilrandomup"] = "Vertikal Rekyl Spridning"
L["autostat.recoilresettime"] = "Rekyl Återställ. Tid"
L["autostat.recoilside"] = "Horisontell Rekyl"
L["autostat.recoilup"] = "Vertikal Rekyl"
L["autostat.reloadtime"] = "Omladdningstid"
L["autostat.ricochetanglemax"] = "Rikoschett Vinkel"
L["autostat.ricochetchance"] = "Rikoschett Chans"
L["autostat.rpm"] = "Eldhastighet"
L["autostat.runawayburst"] = "Bortsprungen Salvo"
L["autostat.secondarysupplylimit"] = "Reserv Sekundär Ammo"
L["autostat.shootvolume"] = "Rapportera Volym"
L["autostat.shootwhilesprint"] = "Skjut i Sprint"
L["autostat.shotgunreload"] = "Individuell Omladdning"
L["autostat.speed"] = "Rörelsehastighet"
L["autostat.spread"] = "Spridning"
L["autostat.sprinttofiretime"] = "Spring-till-Sikte Tid"
L["autostat.stomachdamage"] = "Magskada"
L["autostat.supplylimit"] = "Reservmagasin"
L["autostat.sway"] = "Svängning"
L["autostat.triggerdelay"] = "Avtryckare Fördröj. Tid"
L["autostat.triggerdelaytime"] = "Avtryckare Fördröj. Tid"
L["autostat.visualrecoil"] = "Visuell Rekyl"
L["autostat.visualrecoilpunch"] = "Visuell Rekylkick"
L["autostat.visualrecoilroll"] = "Visuell Rekylrullning"
L["autostat.visualrecoilside"] = "Horisontell Visuell Rekyl"
L["autostat.visualrecoilup"] = "Vertikal Visuell Rekyl"

L["autostat.secondary._beforephrase"] = false
-- if true, secondary stat phrasing comes before the stat
L["autostat.secondary._divider"] = " "
-- space between the secondary phrase from the stat phrase. set true to use empty string

-- L["autostat.secondary.blindfire"] = "under blind skjutning"
L["autostat.secondary.bipod"] = "med Skjutstöd"
L["autostat.secondary.crouch"] = "medans Hukad"
L["autostat.secondary.empty"] = "på Sista skottet i magasinet"
L["autostat.secondary.evenreload"] = "varje Jämn Omladdning"
L["autostat.secondary.evenshot"] = "varje Jämnt skott"
L["autostat.secondary.first"] = "på Första Skottet"
L["autostat.secondary.firstshot"] = "på Första Skottet"
L["autostat.secondary.heated"] = "när den är Het"
L["autostat.secondary.hipfire"] = "från Höften"
L["autostat.secondary.hot"] = "från Hetta"
L["autostat.secondary.last"] = "på Sista Skottet i magasinet"
L["autostat.secondary.lastshot"] = "på Sista skottet i magasinet"
L["autostat.secondary.midair"] = "i Luften"
L["autostat.secondary.move"] = "under Rörelse"
L["autostat.secondary.oddreload"] = "varje Udda Omladdning"
L["autostat.secondary.oddshot"] = "varje Udda skott"
L["autostat.secondary.recoil"] = "från Rekylen" --"With Each Shot"
L["autostat.secondary.shooting"] = "under Skjutning"
L["autostat.secondary.sighted"] = "i Siktet"
L["autostat.secondary.sights"] = "i Siktet"
L["autostat.secondary.silenced"] = "när Ljuddämpad"
L["autostat.secondary.true"] = "när Sanna Namn är på"
L["autostat.secondary.ubgl"] = "på Tillsats"

////////////////////// Blacklist menu
L["blacklist.title"] = "ARC9-Tillbehör Svartlista"
L["blacklist.desc"] = "Tillbehör avbockade här kommer blockeras från att användas"
L["blacklist.blisted"] = "SVARTLISTAD"
L["blacklist.all"] = "ALLA"
L["blacklist.id"] = "ID"
L["blacklist.name"] = "NAMN"
L["blacklist.filter"] = "FILTER"

////////////////////// Incompatible addons
L["incompatible.title"] = "ARC9: INKOMPATIBLA TILLÄGG"
L["incompatible.line1"] = "Du har några tillägg som är kända att inte fungera med ARC9."
L["incompatible.line2"] = "Avaktivera dem eller förvänta brutet beteende!"
L["incompatible.confirm"] = "Bekräfta"
L["incompatible.wait"] = "Vänta {time}s"
L["incompatible.never"] = "Varna mig aldrig igen"
L["incompatible.never.hover"] = "Är du absolut säker på att du förstår konsekvenserna?"
L["incompatible.never.confirm"] = "Du har valt att aldrig igen visa inkompatibla varningar igen. Om du upplever problem eller brutet beteende så är det ditt eget ansvar."

////////////////////// Presets
L["customize.presets.atts"] = " Tillbehör"
L["customize.presets.back"] = "Tillbaka"
L["customize.presets.cancel"] = "Avbryt"
L["customize.presets.code"] = "Förinställ. Kod (Kopierad till Urklipp)"
L["customize.presets.default"] = "Standard"
L["customize.presets.default.long"] = "Standard förinställning"
L["customize.presets.dumb"] = "Är du korkad"
L["customize.presets.import"] = "Importera"
L["customize.presets.invalid"] = "Ogiltig sträng!"
L["customize.presets.new"] = "Nytt Förinställ. Namn"
L["customize.presets.paste"] = "Klistra in Förinställ. Kod Här"
L["customize.presets.random"] = "Slumpmässig"
L["customize.presets.save"] = "Spara"
L["customize.presets.unnamed"] = "Namnlös"

L["customize.presets.deldef"] = "Är du säker på att du vill plocka bort standard förinställning \"{name}\"?"
L["customize.presets.deldef2"] = "Du kommer behöva återställa vapnet via tillverkare inställningar för att få tillbaka den."
L["customize.presets.yes"] = "Ja"

////////////////////// Tips
L["tips.arc-9"] = "Det är ARC9, inte ARC-9, inte Arc9."
L["tips.blacklist"] = "Du kan svartlista tillbehör! Se ARC9 Workshop-beskrivningen för mer information."
L["tips.bugs"] = "Rapportera buggar på den officiella Discord-servern, eller ännu bättre, öppna ett Github-problem."
L["tips.custombinds"] = "ARC9-knappkombinationer kan ersättas med anpassade knappar. Börja skriva in +arc9_ för att hitta dem tillgängliga knapparna!"
L["tips.cyberdemon"] = "För att döda en terrorist så skjuter du honom tills han dör."
L["tips.description"] = "Vi föreslår att du läser beskrivningen på tilläggen innan du kommenterar."
L["tips.development"] = "Vill du skapa ARC9-innehåll? Den officiella Discord-servern har massvis med resurser för att hjälpa till!"
L["tips.discord"] = "Gå med Diamond Doves på Discord! Länken är i ARC9-beskrivningen."
L["tips.external"] = "Om du använder Github-versionen av ARC9, försäkra dig att du ofta uppdaterar den!"
L["tips.hints"] = "Behåll ARC9-gränssnittet för att se kontrolltips."
L["tips.lean"] = "För att manuellt luta på dig, koppla knappar till +alt1 och +alt2."
L["tips.love"] = "Tacka gärna tillverkarna om du tycker om deras arbete! Det hjälper oss verkligen att fortsätta framåt."
L["tips.m9k"] = "Checka ut M9K-vapnen!"
L["tips.official"] = "Ladda endast ner ARC9 från officiella källor. Tredje part uppladdningar kan vara farliga eller föråldrade!"
L["tips.presets"] = "Dela med dig av dina favorita förinställningar med dina vänner genom att exportera dem!"
L["tips.settings"] = "Du kan stänga av dessa tips, och mycket mer, via ARC9-inställningarna. Klicka på knappen i topphögra hörnet!"
L["tips.tips"] = "Tips har en fast ordning. Fortsätt läsa så ser du till sist allihopa."
L["tips.tolerance"] = "Alla vapenpaket fungerar bra tillsammans. Det finns ingen anledning för favorisering."

////////////////////// Other
L["atts.favourites"] = "Favoriter"
L["atts.filter"] = "Filtrera"

/////////////////////////////////////// Settings menu
-- Use this method to localize convars in settings menu:
-- settings.convar.title = "Convar Title"
-- settings.convar.desc = "Convar Description"

L["settings.title"] = "ARC9-Inställningar"
L["settings.desc"] = "Beskrivning"

L["settings.default_convar"] = "Standard värde"
L["settings.convar_server"] = "Servervariabel"
L["settings.convar_client"] = "Client-variabel"

////////////////////// General
L["settings.tabname.general"] = "Generellt"

L["settings.general.client"] = "Klient"
L["settings.truenames.title"] = "Sanna Namn"
L["settings.truenames.desc"] = "Välj om vapnen ska använda riktiga namn eller fiktiva namn valda av utvecklarna. Notera att inte alla vapen använder detta.\n\nServerinställningar kan överskrida denna preferens."
L["settings.resetsettings.cl.title"] = "Återställ alla KLIENT inställ."

L["settings.general.server"] = "Server"
L["settings.truenames_default.title"] = "Standard Sanna Namn"
L["settings.truenames_default.desc"] = "Sätt standard sanna namn läget på servern. Alla spelare som använder \"Standard\" i preferensen kommer använda detta."
L["settings.truenames_enforced.title"] = "Standard Sanna Namn (Tvinga)"
L["settings.truenames_enforced.desc"] = "Välj för att tvinga alla spelare att använda serverinställningen för sanna namn."

L["settings.resetsettings.sv.title"] = "Återställ alla SERVER inställ."

L["settings.reset"] = "Återställ!"

////////////////////// Performance
L["settings.tabname.performance"] = "Prestanda"

L["settings.performance.important"] = "Viktigt"
L["settings.cheapscopes.title"] = "Billiga Sikten"
L["settings.cheapscopes.desc"] = "En billig RT-sikte genomförande genom att zooma in hela din vy när du siktar istället för att framställa världen igen i siktet. Ökar drastiskt prestandan på större kartor."
L["settings.tpik.title"] = "TPIK"
L["settings.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) är ett system som tillåter dem flesta vapen att visa detaljerade och oftast samma första person positioner, omladdning och skjut animationer i tredje person.\n\nKonfiguera den i Visuellt-fliken."
L["settings.allflash.title"] = "Alla Ficklampor"
L["settings.allflash.desc"] = "Framställ helt alla ficklampor från alla spelare.\n\nVäldigt dyr på servrar."

L["settings.performance.blur.title"] = "Sudd"
L["settings.cust_blur.title"] = "Anpassnings Bakgrund"
L["settings.cust_blur.desc"] = "Suddar ut anpassnings bakgrunden."
L["settings.fx_reloadblur.title"] = "Under Omladdning"
L["settings.fx_reloadblur.desc"] = "Suddar ut världen under omladdning."
L["settings.fx_animblur.title"] = "Under förberedelse"
L["settings.fx_animblur.desc"] = "Suddar ut världen när ett vapen tas fram för första gången."
L["settings.fx_rtblur.title"] = "I Magnifierade Sikten"
L["settings.fx_rtblur.desc"] = "Suddar ut världen när ett magnifierat sikte används."
L["settings.fx_adsblur.title"] = "I Siktet"
L["settings.fx_adsblur.desc"] = "Suddar ut världen i siktet."
L["settings.fx_rtvm.title"] = "Visa vapnet genom RT-Sikten"
L["settings.fx_rtvm.desc"] = "! EXPERIMENTAL !\nVisar vapnet och dess tillbehör genom RT-sikten. Kräver att \"Billiga Sikten\" är avstängt.\nSänker drastiskt prestandan."

L["settings.performance.shelleject.title"] = "Patron Utmatning"
L["settings.eject_fx.title"] = "Rökeffekter"
L["settings.eject_fx.desc"] = "Tillverkar rökeffekter från spenderade patroner om vapnet stödjer denna funktion"
L["settings.eject_time.title"] = "Lägg Till Livstid"
L["settings.eject_time.desc"] = "Tillåt att patroner håller sig kvar i världen längre. Kan vara dyrt."

L["settings.performance.fx.title"] = "Effekter"
L["settings.muzzle_light.title"] = "Mynningseld"
L["settings.muzzle_light.desc"] = "Aktiverar ljus från mynningseld när du skjuter ett vapen."
L["settings.muzzle_others.title"] = "Andras Mynningseld"
L["settings.muzzle_others.desc"] = "Aktivera mynningseld effekter från andra spelares vapen."

////////////////////// Optics
L["settings.tabname.optics"] = "Sikten"

L["settings.optics.control"] = "Kontroll"
L["settings.optics.sensmult.title"] = "Mult. Känslighet i Siktet"
L["settings.optics.sensmult.desc"] = "Multiplicerar titta runt känsligheten med detta antal i siktet.\nJu lägre värdet är ju lägre är känsligheten.\nAnvändbar när kontroller används, eller om användaren vill ha lägre känslighet i siktet."
L["settings.optics.compensate_sens.title"] = "Kompensera Känslighet"
L["settings.optics.compensate_sens.desc"] = "Kompensera känsligheten för magnifiering."
L["settings.optics.toggleads.title"] = "Växla Sikte"
L["settings.optics.toggleads.desc"] = "Användning av sikten växlas."

L["settings.optics.color"] = "Färg"
L["settings.optics.reflex.title"] = "Reflexsikten"
L["settings.optics.reflex.desc"] = "Färg att använda för reflex-/holografiska sikten.\n\nInte alla sikten stödjer denna funktion."
L["settings.optics.scope.title"] = "Kikarsikten"
L["settings.optics.scope.desc"] = "Färg att använda för magnifierade sikten.\n\nInte alla sikten stödjer denna funktion."

////////////////////// Crosshair
L["settings.tabname.crosshair"] = "Hårkors"

L["settings.crosshair.crosshair"] = "Hårkors"
L["settings.crosshair.cross_enable.title"] = "Aktivera Hårkors"
L["settings.crosshair.cross_enable.desc"] = "Aktiverar hårkorset. Vissa sikten tillåter inte dig att använda hårkorset."
L["settings.crosshair.cross.title"] = "Hårkors Färg"
L["settings.crosshair.cross.desc"] = "Hårkorsets färg."
L["settings.crosshair.cross_size_mult.title"] = "Hårkors Färg"
L["settings.crosshair.cross_size_mult.desc"] = "Multiplicera storleken på ditt hårkors."
L["settings.crosshair.cross_size_dot.title"] = "Punktstorlek"
L["settings.crosshair.cross_size_dot.desc"] = "Multiplicera storleken på den mittersta punkten."
L["settings.crosshair.cross_size_prong.title"] = "Klostorlek"
L["settings.crosshair.cross_size_prong.desc"] = "Multiplicera storleken på de yttre klorna."
L["settings.crosshair.crosshair_static.title"] = "Statiskt Hårkors"
L["settings.crosshair.crosshair_static.desc"] = "Aktiverar en statisk hårkors som inte förflyttar sig under skjutning."
L["settings.crosshair.crosshair_force.title"] = "Tvinga Hårkors"
L["settings.crosshair.crosshair_force.desc"] = "Tvingar att hårkorset visas på vapen som inte vill att du ser den.\n\nServerinställning."
L["settings.crosshair.crosshair_target.title"] = "Rött Hårkors på Måltavla"
L["settings.crosshair.crosshair_target.desc"] = "Gör hårkorset rött när man siktar på en måltavla.\nAktiverar också sikthjälp om den är påslagen."
L["settings.crosshair.crosshair_peeking.title"] = "Visa Hårkors när man Kikar"
L["settings.crosshair.crosshair_peeking.desc"] = "Visar hårkorset när man är i siktet och använder kika funktionen."

////////////////////// Customization
L["settings.tabname.hud_cust"] = "Anpassning"

L["settings.hud_cust.hud"] = "Gränssnitt"
L["settings.hud_cust.hud_scale.title"] = "Gränssnitt Skala"
L["settings.hud_cust.hud_scale.desc"] = "Skalmodifierare för ARC9-gränssnittet."
L["settings.hud_cust.hud_deadzonex.title"] = "Gräns. Bredd Dödszon"
L["settings.hud_cust.hud_deadzonex.desc"] = "Horisontell \"dödszon\" för anpassningsmenyn och gränssnitt panelen.\nAnvändbra för ultrawide-skärmar."
L["settings.hud_cust.hud_color.title"] = "Gränssnitt Färg"
L["settings.hud_cust.hud_color.desc"] = "Markerar färgen för gränssnittet.\nAccentfärgen."
L["settings.hud_cust.hud_holiday.title"] = "Högtidsteman"
L["settings.hud_cust.hud_holiday.desc"] = "Teman som aktiverar under vissa högtider.\nSkriver över gränssnitt färger"
L["settings.hud_cust.hud_darkmode.title"] = "Mörkt Tema"
L["settings.hud_cust.hud_darkmode.desc"] = "Aktiverar mörka färger på gränssnittet istället för ljusgrått och avaktiverar vinjetteffekten i bakgrunden."
L["settings.hud_cust.cust_light.title"] = "Aktivera Ljus"
L["settings.hud_cust.cust_light.desc"] = "Aktiverar vapenljus i anpassnings menyn.\n\nSamma som knappen nära inställningar knappen."
L["settings.hud_cust.cust_light_brightness.title"] = "Ljusstyrka för ljus"
L["settings.hud_cust.cust_light_brightness.desc"] = "Hur starkt ljuset kommer vara i anpassnings panelen.\n\nGlöm inte att sätta på den först!"

L["settings.hud_cust.customization"] = "Anpassning"
L["settings.hud_cust.cust_hints.title"] = "Knapptips"
L["settings.hud_cust.cust_hints.desc"] = "Aktivera knapptips i anpassnings menyn."
L["settings.hud_cust.cust_tips.title"] = "Tips"
L["settings.hud_cust.cust_tips.desc"] = "Tips om ARC9-basen nära knapptipsen."
L["settings.hud_cust.cust_exit_reset_sel.title"] = "Stängning Återställer Val"
L["settings.hud_cust.cust_exit_reset_sel.desc"] = "Stängning av anpassnings menyn återställer den aktiva valda platsen."

////////////////////// Game HUD
L["settings.tabname.hud_game"] = "Spelgränssnitt"

L["settings.hud_game.lcd"] = "LCD-Panel"
L["settings.hud_game.hud_arc9.title"] = "Aktivera Gränssnitt"
L["settings.hud_game.hud_arc9.desc"] = "Aktiverar gränssnittet på ARC9-vapen."
L["settings.hud_game.hud_always.title"] = "På alla vapen"
L["settings.hud_game.hud_always.desc"] = "Aktiverar gränssnittet på alla vapen."
L["settings.hud_game.hud_compact.title"] = "Kompaktläge"
L["settings.hud_game.hud_compact.desc"] = "Kompakt utseende för gränssnitt panelen."
L["settings.hud_game.hud_nohints.title"] = "Avaktivera Tips"
L["settings.hud_game.hud_nohints.desc"] = "Avaktiverar tips helt och hållet. Dem kommer inte visas upp i 3D eller 2D gränssnittet."
L["settings.hud_game.hud_keephints.title"] = "Behåll Tips"
L["settings.hud_game.hud_keephints.desc"] = "Visa ARC9-kontroll tipsen på toppen av gränssnitt panelen."
L["settings.hud_game.hud_force_disable.title"] = "Tvinga Av ARC9 Gränssnitt"
L["settings.hud_game.hud_force_disable.desc"] = "Stänger av ARC9 Gränssnittet till alla spelare. Gäller ej för knapptips."

L["settings.hud_game.killfeed"] = "Killfeed"
L["settings.hud_game.killfeed_enable.title"] = "Killfeed-Ikoner"
L["settings.hud_game.killfeed_enable.desc"] = "Aktivera automatisk generering av killfeed-ikoner på ARC9-vapen."
L["settings.hud_game.killfeed_dynamic.title"] = "Dynamisk uppdatering"
L["settings.hud_game.killfeed_dynamic.desc"] = "Killfeed-ikoner genereras om efter varje dödad.\n\nStäng av om du vill ha den där 0.1 FPS:en."
L["settings.hud_game.killfeed_colour.title"] = "Fullfärgade Ikoner"
L["settings.hud_game.killfeed_colour.desc"] = "Dem dynamiskt skapade ikonerna är fullfärgade."

L["settings.hud_game.breath"] = "Anda"
L["settings.hud_game.breath_hud.title"] = "Andning Gränssnitt"
L["settings.hud_game.breath_hud.desc"] = "Visar en stång som visar din kvarstående andetag när du stabiliserar ditt vapen i siktet."
L["settings.hud_game.breath_pp.title"] = "Andning Efterbehandling"
L["settings.hud_game.breath_pp.desc"] = "Hålla andan lägger också till ett efterbehandling effekt på skärmen."
L["settings.hud_game.breath_sfx.title"] = "Andning Ljudeffekt"
L["settings.hud_game.breath_sfx.desc"] = "Hålla andan spelar också associerade ljudeffekter."

L["settings.hud_game.centerhint"] = "Verktygstips"
L["settings.hud_game.centerhint_reload.title"] = "Visa Omladdning Tips"
L["settings.hud_game.centerhint_reload.desc"] = "Visar ett omladdning tips när ammunition är lågt."
L["settings.hud_game.centerhint_reload_percent.title"] = "Magasinprocent"
L["settings.hud_game.centerhint_reload_percent.desc"] = "Visar omladdningstipset när det nuvarande magasinet är vid detta procentvärde."
L["settings.hud_game.centerhint_bipod.title"] = "Visa Växla Skjutstöd"
L["settings.hud_game.centerhint_bipod.desc"] = "Visa ett tips när skjutstödet kan växlas."

L["settings.hud_game.hud_glyph"] = "Sortens Glyfer"

L["settings.hud_game.hud_glyph_type_hud.title"] = "Gränssnitt"
L["settings.hud_game.hud_glyph_type_hud.desc"] = "Ändrar vilken familj av glyfer du vill använda.\nDetta gäller för gränssnittens tips."

L["settings.hud_game.hud_glyph_type_cust.title"] = "Anpassningsmeny"
L["settings.hud_game.hud_glyph_type_cust.desc"] = "Ändrar vilken familj av glyfer du vill använda.\nDetta gäller för anpassningsmenyns tips.\nÄndringar tillämpas nästa gång anpassnignsmenyn öppnas."

L["settings.hud_game.hud_glyph_light"] = "Ljusa"
L["settings.hud_game.hud_glyph_dark"] = "Mörka"
L["settings.hud_game.hud_glyph_knockout"] = "\"Knockout\""

////////////////////// NPCs
L["settings.tabname.npc"] = "NPC:er"

L["settings.npc.weapons"] = "NPC Vapen"
L["settings.npc.npc_equality.title"] = "Skadejämlikhet"
L["settings.npc.npc_equality.desc"] = "NPC:er gör lika mycket skada som spelare gör.\n\nDetta är en servervariabel."
L["settings.npc.npc_spread.title"] = "NPC Spridning"
L["settings.npc.npc_spread.desc"] = "Multiplikator för hur oträffsäkra NPC:er är när de skjuter."
L["settings.npc.npc_atts.title"] = "Ge Tillbehör"
L["settings.npc.npc_atts.desc"] = "Spawnade eller upplockade ARC9-vapen ger en slumpmässig samling tillbehör.\n\nDetta är en servervariabel."
L["settings.npc.npc_autoreplace.title"] = "Ersätt NPC Vapen"
L["settings.npc.npc_autoreplace.desc"] = "Ersätter NPC:ernas vapen med slumpmässigt valda ARC9-vapen.\n\nDetta är en servervariabel."
L["settings.npc.replace_spawned.title"] = "Ersätt Markvapen"
L["settings.npc.replace_spawned.desc"] = "Ersätter karta/spawnade HL2 vapen med slumpmässigt valda ARC9-vapen.\n\nDetta är en servervariabel."
L["settings.npc.npc_give_weapons.title"] = "Spelare Kan Ge Vapen"
L["settings.npc.npc_give_weapons.desc"] = "Spelare kan trycka på E på NPC:er för att kunna ge de deras vapen.\n\nDetta är en servervariabel."

////////////////////// Gameplay
L["settings.tabname.gameplay"] = "Spel"

L["settings.gameplay.controls"] = "Kontroller"
L["settings.gameplay.toggleads.title"] = "Växla Sikte"
L["settings.gameplay.toggleads.desc"] = "Användning av sikten växlas."
L["settings.gameplay.autolean.title"] = "Automatisk Lutning"
L["settings.gameplay.autolean.desc"] = "Försöker automatiskt luta i siktet när möjligt."
L["settings.gameplay.autoreload.title"] = "Automatisk Omladdning"
L["settings.gameplay.autoreload.desc"] = "Tomma ARC9-vapen kommer automatiskt laddas om."
L["settings.gameplay.togglelean.title"] = "Växla Lutning"
L["settings.gameplay.togglelean.desc"] = "Tryck på luta-knapparna kommer växla lutningen istället för att den behövs hållas inne."
L["settings.gameplay.togglepeek.title"] = "Växla Kikande"
L["settings.gameplay.togglepeek.desc"] = "Tryck på kika-knapparna kommer växla kikandet istället för att den behövs hållas inne."
L["settings.gameplay.togglepeek_reset.title"] = "Återställ Kikande Status Efter Sikte"
L["settings.gameplay.togglepeek_reset.desc"] = "(Endast om Växla Kikande är på)\nKik-status kommer inte behållas efter du går ur siktet."
L["settings.gameplay.togglebreath.title"] = "Växla Hålla Andan"
L["settings.gameplay.togglebreath.desc"] = "Att trycka på Hålla Andan-knappen kommer växla Hålla Andan istället för att den krävs att hållas ner."

L["settings.gameplay.mechanics"] = "Spelfunktioner"
L["settings.gameplay.infinite_ammo.title"] = "Oändlig Ammo"
L["settings.gameplay.infinite_ammo.desc"] = "Vapen får oändligt med ammo.\n\nDetta är en servervariabel."
L["settings.gameplay.realrecoil.title"] = "Fysisk Visuell Rekyl"
L["settings.gameplay.realrecoil.desc"] = "Valda vapen uppsatta för denna funktion får fysisk mynningstigning, vilket betyder att dem skjuter dit deras viewmodel visar istället för skärmens center. Väldigt viktigt för vissa vapenpakes balansering.\n\nDetta är en servervariabel."
L["settings.gameplay.lean.title"] = "Lutning"
L["settings.gameplay.lean.desc"] = "Om spelare kan luta med +alt1 och +alt2, inklusive automatisk lutning.\n\nDetta är en servervariabel."
L["settings.gameplay.mod_sway.title"] = "Svängning"
L["settings.gameplay.mod_sway.desc"] = "Vapen kommer svänga om de är uppsatta att använda det.\n\nDetta är en servervariabel."
L["settings.gameplay.mod_freeaim.title"] = "Fritt Sikte"
L["settings.gameplay.mod_freeaim.desc"] = "Vapen kommer få fritt sikte och kommer inte alltid skjuta på skärmens mitt.\n\nDetta är en servervariabel."
L["settings.gameplay.mod_bodydamagecancel.title"] = "Kroppsskada Avbrytning"
L["settings.gameplay.mod_bodydamagecancel.desc"] = "Avbryt standard kroppsskada modifierare. Avaktivera endast om en annan modd erbjuder denna sorts funktion\nex. Moddar som ändrar standard lem modifierare.\n\nDetta är en servervariabel."
L["settings.gameplay.breath_slowmo.title"] = "Slow-Mo Andning"
L["settings.gameplay.breath_slowmo.desc"] = "Hålla andan saktar ner tiden.\n\nEndast Singleplayer."
L["settings.gameplay.manualbolt.title"] = "Manuell Cykel"
L["settings.gameplay.manualbolt.desc"] = "Cylinderrepeter vapen konfiguerademed denna funktion laddarendast om när R tryckas ner och inte när attack-knappen släpps."
L["settings.gameplay.never_ready.title"] = "Inga \"Redo\" Anim."
L["settings.gameplay.never_ready.desc"] = "Avaktivera \"Redo\" animationer när du tar fram ett vapen.\n\nDetta är en servervariabel."
L["settings.gameplay.recoilshake.title"] = "Rekyl skakning i synfält"
L["settings.gameplay.recoilshake.desc"] = "Knäpper synfältet under skjutning"
L["settings.gameplay.equipment_generate_ammo.title"] = "Unik Ammo Typ för Utrustning"
L["settings.gameplay.equipment_generate_ammo.desc"] = "Det finns en begränsning på 255 ammo typer och avaktiverar du detta alternativ kan det fixa några problem ifall du har många tillägg.\n\nDetta är en servervariabel.\n\nKräver omstart."

-- ??
L["settings.gameplay.mult_defaultammo.title"] = "Standard Reserv Ammo"
L["settings.gameplay.mult_defaultammo.desc"] = "Hur många magasin/granater/utrustning som ges till spelaren när hen plockar upp ett vapen för första gången?\n\nDetta är en servervariabel."
L["settings.gameplay.nearwall.title"] = "Nära Väggen"
L["settings.gameplay.nearwall.desc"] = "Tillåt inte att vapnet skjuts när du står för nära en vägg eller ett hinder."

////////////////////// Visuals
L["settings.tabname.visuals"] = "Visuellt"

L["settings.visuals.viewmodel"] = "Viewmodel"
L["settings.visuals.vm_bobstyle.title"] = "Gupp Stil"
L["settings.visuals.vm_bobstyle.desc"] = "Välj olika gupp stilar till smaken av olika medlemmar av ARC9-teamet (och valve software) från mest nyaste stil till den äldsta."
L["settings.visuals.fov.title"] = "Synfält"
L["settings.visuals.fov.desc"] = "Lägg till vymodell synfält. Gör vymodellen större eller mindre. Använd ansvarsfullt."
L["settings.visuals.vm_addx.title"] = "Lägg till X"
L["settings.visuals.vm_addx.desc"] = "Flyttar vymodellen till vänster eller höger."
L["settings.visuals.vm_addy.title"] = "Lägg till Y"
L["settings.visuals.vm_addy.desc"] = "Flyttar vymodellen fram- eller bakåt."
L["settings.visuals.vm_addz.title"] = "Lägg till Z"
L["settings.visuals.vm_addz.desc"] = "Flyttar vymodellen upp eller ner."

L["settings.visuals.cambob"] = "Vy Guppande"
L["settings.visuals.vm_cambob.title"] = "Spring Vy Guppande"
L["settings.visuals.vm_cambob.desc"] = "Gör att din kamera förflyttar sig när du springer"
L["settings.visuals.vm_cambobwalk.title"] = "Gå Vy Guppande"
L["settings.visuals.vm_cambobwalk.desc"] = "Gör att din kamera lätt förflyttar sig när du går runt (kräver spring guppande)"
L["settings.visuals.vm_cambobintensity.title"] = "Intensitet"
L["settings.visuals.vm_cambobintensity.desc"] = "Hur intensiv guppandet är"

L["settings.visuals.tpik"] = "TPIK"
L["settings.visuals.tpik.title"] = "Aktivera TPIK"
L["settings.visuals.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) är ett system tom tillåter dem flesta vapen att visa detaljerade och oftast samma första person positioner, omladdning och skjut animationer i tredje person."
L["settings.visuals.tpik_others.title"] = "Andra Spelares TPIK"
L["settings.visuals.tpik_others.desc"] = "Visa TPIK på andra spelare förutom dig själv. Påverkar prestandan negativt."
L["settings.visuals.tpik_framerate.title"] = "TPIK-Bildhastighet"
L["settings.visuals.tpik_framerate.desc"] = "Maximal bildhastighet då TPIK kan köras. Sätt till 0 för oändlig."

////////////////////// Bullet Physics
L["settings.tabname.bullets"] = "Skottfysik"

L["settings.bullets.bullets"] = "Skottfysik"
L["settings.bullets.bullet_physics.title"] = "Fysiska Skott"
L["settings.bullets.bullet_physics.desc"] = "Vapen som stödjer denna funktion kommer skjuta fysiska skott, som har avsläpp, restid och motstånd.\n\nDetta är en servervariabel."
L["settings.bullets.bullet_gravity.title"] = "Gravitation"
L["settings.bullets.bullet_gravity.desc"] = "Multiplikator för skott gravitation.\n\nDetta är en servervariabel."
L["settings.bullets.bullet_drag.title"] = "Motstånd"
L["settings.bullets.bullet_drag.desc"] = "Multiplikator för skottmotstånd.\n\nDetta är en servervariabel."
L["settings.bullets.ricochet.title"] = "Rikoschett"
L["settings.bullets.ricochet.desc"] = "Skott skjutna från valda vapen kan ibland studsa av ytor och fortsätta att resa och göra skada.\n\nDetta är en servervariabel."
L["settings.bullets.mod_penetration.title"] = "Penetration"
L["settings.bullets.mod_penetration.desc"] = "Skott skjutna från valda vapen kan penetrera ytor och göra skada till vad som finns på andra sidan.\n\nDetta är en servervariabel."
L["settings.bullets.bullet_lifetime.title"] = "Livstid"
L["settings.bullets.bullet_lifetime.desc"] = "Tid i sekunder då ett skott ska plockas bort.\n\nDetta är en servervariabel."
L["settings.bullets.bullet_imaginary.title"] = "Inbillade Skott"
L["settings.bullets.bullet_imaginary.desc"] = "Skott ser ut att de flyger till skyboxen, förbi kartans gränser."

////////////////////// Attachments
L["settings.tabname.attachments"] = "Tillbehör"

L["settings.attachments.customization"] = "Anpassning"
L["settings.attachments.atts_nocustomize.title"] = "Avaktivera Anpassning"
L["settings.attachments.atts_nocustomize.desc"] = "Tillåter ingen mer anpassning via anpassnings menyn.\n\nDetta är en servervariabel."
L["settings.attachments.atts_max.title"] = "Max. Tillbehör"
L["settings.attachments.atts_max.desc"] = "Maximalt antal tillbehör som kan utrustas på ett vapen, inklusive kosmetiska tillbehör.\n\nDetta är en servervariabel."
L["settings.attachments.autosave.title"] = "Autospar"
L["settings.attachments.autosave.desc"] = "Ditt sista vapens anpassningsinställningar kommer sparas och automatiskt utrustas nästa gång du spawnar det vapen."
L["settings.attachments.blacklist.title"] = "Svartlista Meny"
L["settings.attachments.blacklist.open"] = "Öppna"

L["settings.attachments.inventory"] = "Lager"
L["settings.attachments.free_atts.title"] = "Gratis Tillbehör"
L["settings.attachments.free_atts.desc"] = "Tillbehör kan användas utan att plockas upp först.\n\nDetta är en servervariabel."
L["settings.attachments.atts_lock.title"] = "En För Alla"
L["settings.attachments.atts_lock.desc"] = "När du plockar upp ett tillbehör så kan du använda den oändligt många gånger på alla dina vapen.\n\nDetta är en servervariabel."
L["settings.attachments.atts_loseondie.title"] = "Förlora Vid Död"
L["settings.attachments.atts_loseondie.desc"] = "Ditt tillbehörlager förloras när du dör.\n\nDetta är en servervariabel."
L["settings.attachments.atts_generateentities.title"] = "Generera Entiteter"
L["settings.attachments.atts_generateentities.desc"] = "Generera entiteter som kan spawnas som tillåter dig att plockas upp tillbehör när gratis tillbehör är avaktiverade.\n\nKan öka laddtiden.\n\nDetta är en servervariabel."

////////////////////// Modifiers
L["settings.tabname.modifiers"] = "Modifierare"

L["settings.modifiers.quick.title"] = "Snabbstatistik Modifierare"
L["settings.modifiers.quick.desc"] = " "

L["settings.mod_damage.title"] = "Skada"
L["settings.mod_spread.title"] = "Spridning"
L["settings.mod_recoil.title"] = "Rekyl"
L["settings.mod_visualrecoil.title"] = "Visuell Rekyl"
L["settings.mod_adstime.title"] = "Res/Sänk Sikte Tid"
L["settings.mod_sprinttime.title"] = "Spring-till-Sikte Tid"
L["settings.mod_damagerand.title"] = "Skadevariering"
L["settings.mod_muzzlevelocity.title"] = "Utgångshastighet"
L["settings.mod_rpm.title"] = "Eldhastighet"
L["settings.mod_headshotdamage.title"] = "Huvudskott Skada"
L["settings.mod_malfunction.title"] = "Felfunktion Chans"

////////////////////// Controller
L["settings.tabname.controller"] = "Kontroller"

L["settings.controller.misc"] = "Annat"
L["settings.controller.misc.desc"] = "Det borde vara en knapp för att öppna panelen med avancerad kontroller konfiguering, men för tillfället är det Spawnmeny > Options > ARC9 > Kontroller."
L["settings.controller.controller.title"] = "Kontroller Glyfer"
L["settings.controller.controller.desc"] = "Aktiverar anpassade kontroller-kompatibla glyfer som visar kontroller knappar istället för standard knappar."
-- L["settings.controller.controller_rumble.title"] = "Rumble"
-- L["settings.controller.controller_rumble.desc"] = "Enable controller rumble as long as Fesiug's DLL mod is loaded.\n\ngithub.com/Fesiug/\ngmod-sinput"
L["settings.controller.controller_config.title"] = "Avancerad konfig."
L["settings.controller.controller_config.content"] = "Öppna panel"
L["settings.controller.controller_config.desc"] = "Öppna avancerad kontroller konfigurering panel."

L["settings.controller.glyphs.title"] = "Familj av Glyfer"
L["settings.controller.glyphs.desc"] = "Välj från vilken familj av glyfer du vill använda.\nSätt upp glyfer i \"Spawnmeny\" > Options > ARC9 > Controller."

////////////////////// Aim Assist
L["settings.tabname.aimassist"] = "Siktehjälp"
L["settings.tabname.aimassist.desc"] = "Du kan aktivera siktehjälp om du har problem att hålla ditt sikte på din måltavla, eller om du föredrar att inte anstränga dig när du skjuter på dina måltavlor."

L["settings.aimassist.enable.title"] = "Aktivera Siktehjälp"
L["settings.aimassist.enable.desc"] = "Aktiverar en siktehjälp som förflyttar din vy mot en måltavla när du siktar nära dem.\n\nDetta är en servervariabel.\n\nKräver att Siktehjälp är aktiverad på CLIENT."

L["settings.aimassist.enable_general.desc"] = "Aktiverar en siktehjälp som förflyttar din vy mot en måltavla när du siktar nära dem.\n\nKonfiguera den i \"Siktehjälp\"-fliken."

L["settings.aimassist.enable_client.desc"] = "Aktiverar en siktehjälp som förflyttar din vy mot en måltavla när du siktar nära dem.\n\nKräver att Siktehjälp är aktiverad på SERVER."

L["settings.aimassist.intensity.title"] = "Kraft"
L["settings.aimassist.intensity.desc"] = "Hur kraftfull siktehjälpen är.\n\nDetta är en servervariabel."

L["settings.aimassist.cone.title"] = "Kon"
L["settings.aimassist.cone.desc"] = "Hur nära eller hur långt borta du måste titta på en måltavla innan siktehjälpen aktiveras.\n\nDetta är en servervariabel."

L["settings.aimassist.head.title"] = "Lås mot huvud"
L["settings.aimassist.head.desc"] = "Om siktehjälpen ska låsa sig mot måltavlans huvud istället för dess bröst.\n\nDetta är en servervariabel."

L["settings.aimassist.sensmult.desc"] = "Multiplicerar titta runt känsligheten med detta antal när du siktar på en giltig måltavla.\nJu lägre värdet är ju lägre är känsligheten."

////////////////////// Asset Caching
L["settings.tabname.caching"] = "Tillgång-Cache"
L["settings.caching.title"] = "Tillgång-Cache"
L["settings.caching.desc"] = "Du kan cacha några ARC9-tillgångar (spara i minnet utan att ladda när du spelar) för att förhindra stamning för en bra spel upplevelse!\n\nDu borde säkert aktivera några grejer om ditt GMod spelas på en HDD."

L["settings.caching.precache_sounds_onfirsttake.title"] = "På första upplock: Cache vapenljud"
L["settings.caching.precache_sounds_onfirsttake.desc"] = "Cache alla ljud endast för det vapnet du tar upp i handen (förutom omladdning ljud).\n\nInte väldigt effektfull men kan hjälpa att förhindra stamning när man skjuter."

L["settings.caching.precache_attsmodels_onfirsttake.title"] = "På första upplock: Cache alla tillbehör"
L["settings.caching.precache_attsmodels_onfirsttake.desc"] = "Cache alla ARC9-tillbehör modeller när ett ARC9-vapen är i händerna.\n\nOrsakar en stor frysning, speciellt när du har många vapen."
L["settings.caching.precache_wepmodels_onfirsttake.title"] = "På första upplock: Cache alla vapenmodeller"
L["settings.caching.precache_wepmodels_onfirsttake.desc"] = "Cache alla ARC9-vapen viewmodeller när ett ARC9-vapen är i händerna.\n\nOrsakar en MASSIV frysning, speciellt när du har många vapen."

L["settings.caching.precache_allsounds_onstartup.title"] = "På spelstart: Cache alla vapenljud"
L["settings.caching.precache_allsounds_onstartup.desc"] = "Cache alla ljud från alla vapen vid serverstart (förutom omladdning ljud).\n\nInte väldigt effektfull men det är bättre att du använder första alternativet här."
L["settings.caching.precache_attsmodels_onstartup.title"] = "På spelstart: Cache alla tillbehör"
L["settings.caching.precache_attsmodels_onstartup.desc"] = "Cache alla ARC9-tillbehör modeller vid serverstart.\n\nOrsakar väldigt högt ökad laddningstid, speciellt när du har många vapen."
L["settings.caching.precache_wepmodels_onstartup.title"] = "På spelstart: Cache alla vapenmodeller"
L["settings.caching.precache_wepmodels_onstartup.desc"] = "Cache alla ARC9-vapen viewmodeller vid serverstart.\n\nOrsakar VÄLDIGT ökad laddningstid, speciellt när du har många vapen."

L["settings.caching.precache_allsounds.title"] = "Alla vapenljud"
L["settings.caching.precache_wepmodels.title"] = "Alla vapenmodeller"
L["settings.caching.precache_attsmodels.title"] = "Alla tillbehör modeller"

L["settings.developer.cache"] = "Cache"

////////////////////// Developer
L["settings.tabname.developer"] = "Tillverkare"

L["settings.developer.developer"] = "Tillverkare Inställ."
L["settings.developer.dev_always_ready.title"] = "Alltid Redo"
L["settings.developer.dev_always_ready.desc"] = "Spela alltid \"redo\"-animationen när du tar fram ett vapen.\n\nDetta är en servervariabel."
L["settings.developer.dev_benchgun.title"] = "Benchgun"
L["settings.developer.dev_benchgun.desc"] = "Behåll vapnet där den för tillfället är."
L["settings.developer.dev_crosshair.title"] = "Tillv. Hårkors"
L["settings.developer.dev_crosshair.desc"] = "Ett konstigt hårkors som visar exakt sikte pukt och några användbara nummer.\n\nDetta är en servervariabel och fungerar endast för admins - försök inte fuska med detta!"
L["settings.developer.dev_show_shield.title"] = "Visa Sköld"
L["settings.developer.dev_show_shield.desc"] = "Visa modellen för spelarens sköld."
L["settings.developer.dev_greenscreen.title"] = "Grön Skärm"
L["settings.developer.dev_greenscreen.desc"] = "Visar en grön skärm bakgrund i anpassningsmenyn för skärmbilder.\n\nOm du använder HDR, glöm inte att sätta mat_bloom_scalefactor_scalar till 0!"
L["settings.developer.reloadatts.title"] = "Ladda om Tillbehör"
L["settings.developer.reloadlangs.title"] = "Ladda om Språk"
L["settings.developer.dev_listmyatts.title"] = "Lista Mina Tillbehör"
L["settings.developer.dev_listanims.title"] = "Lista Anim."
L["settings.developer.dev_listbones.title"] = "Lista Ben"
L["settings.developer.dev_listbgs.title"] = "Lista Bodygroups"
L["settings.developer.dev_listatts.title"] = "Lista QCAttachments"
L["settings.developer.dev_export.title"] = "Skaffa Export Kod"
L["settings.developer.dev_getjson.title"] = "Skaffa Vapen JSON"

L["settings.developer.presets_clear.title"] = "Rensa vapendata"
L["settings.developer.presets_clear.desc"] = "Rensar förinställningar, alla ikoner och standard förinställningar för vapnet du håller i.\n\nVarning: om menyn är öppnad utan ett ARC9-vapen i händerna så kommer den plocka bort alla ARC9-förinställningar och ikoner!"

L["settings.developer.clear"] = "Rensa"
L["settings.developer.print"] = "Skriv till Konsol"
L["settings.developer.reload"] = "Ladda Om"
