L = {}

/////////////////////////////////////// Font
////////////////////// See "font_en" file

/////////////////////////////////////// General
////////////////////// Units of measurement
L["unit.second"] = "s"
L["unit.meter"] = "m"
L["unit.millimeter"] = "mm"
L["unit.meterpersecond"] = "m/s"
L["unit.hammerunit"] = "HU"
L["unit.decibel"] = "dB"
L["unit.rpm"] = "DPM"
L["unit.moa"] = "MOA"
L["unit.dmg"] = "DMG"
L["unit.projectiles"] = "PROJ"

////////////////////// Ammo types
L["ammo.pistol"] = "Municion de Pistola"
L["ammo.357"] = "Municion de Magnum"
L["ammo.smg1"] = "Municion de Carabina"
L["ammo.ar2"] = "Municion de Rifle"
L["ammo.buckshot"] = "Municion de Escopeta"
L["ammo.sniperpenetratedround"] = "Municion de Sniper"
L["ammo.smg1_grenade"] = "Granadas de Rifle"

/////////////////////////////////////// HUD
L["hud.version"] = "ARCTIC SYSTEMS HUD v"
L["hud.jammed"] = "FALLO!"
L["hud.therm_deco"] = "TEMP CAÑON"

L["hud.firemode.single"] = "SEMI"
L["hud.firemode.burst"] = "RÁFAGA"
L["hud.firemode.auto"] = "AUTO"
L["hud.firemode.safe"] = "SEGURO"

L["hud.hint.bash"] = "Golpear"
L["hud.hint.bipod"] = "Alternar Bípode"
L["hud.hint.breath"] = "Mantener Respiracion"
L["hud.hint.customize"] = "Customizar"
L["hud.hint.cycle"] = "Ciclo"
L["hud.hint.firemode"] = "Cambiar Modo de Disparo"
L["hud.hint.inspect"] = "Inspeccionar"
L["hud.hint.lean"] = "Inclinarse"
L["hud.hint.peek"] = "Vistazo"
L["hud.hint.reload"] = "Recarga"
L["hud.hint.safe"] = "Poner Seguro"
L["hud.hint.switchsights"] = "Cambiar Miras"
L["hud.hint.toggleatts"] = "Alternar Accesorios"
L["hud.hint.ubgl"] = "Alternar"
L["hud.hint.zoom"] = "Cambiar Zoom"

L["hud.error.missingbind"] = "\" %s \" sin asignar"

/////////////////////////////////////// Customization menu
L["customize.panel.customize"] = "CUSTOMIZAR"
L["customize.panel.personalize"] = "PERSONALIZAR"
L["customize.panel.stats"] = "ESTADÍSTICAS & BALÍSTICAS"
L["customize.panel.trivia"] = "TRIVIA"
L["customize.panel.inspect"] = "INSPECCIONAR"
L["customize.panel.presets"] = "PREAJUSTES"

L["customize.stats.aimtime"] = "Tiempo para Apuntar"
L["customize.stats.ammo"] = "Tipo de Munición"
L["customize.stats.armorpiercing"] = "Penetración de Armadura"
L["customize.stats.burstdelay"] = "Tiempo entre Ráfagas"
L["customize.stats.capacity"] = "Capacidad"
L["customize.stats.cyclic"] = "DPM Cíclicos"
L["customize.stats.explosive"] = "Daño Explosivo"
L["customize.stats.firemodes"] = "Modos de Disparo"
L["customize.stats.firepower"] = "Potencia de fuego"
L["customize.stats.freeaim"] = "Radio de Vista Libre"
L["customize.stats.muzzlevelocity"] = "Velocidad de salida"
L["customize.stats.noise"] = "Ruido"
L["customize.stats.penetration"] = "Penetración"
L["customize.stats.precision"] = "Precisión"
L["customize.stats.range"] = "Rango"
L["customize.stats.ricochet"] = "Probablidad de Rebote"
L["customize.stats.rof"] = "DPM"
L["customize.stats.speed"] = "Velocidad de Movimiento"
L["customize.stats.sprinttofire"] = "Tiempo de Esprint a Disparo"
L["customize.stats.supplylimit"] = "Limite de Suministros"
L["customize.stats.sway"] = "Estabilidad"
L["customize.stats.triggerdelay"] = "Retraso de Gatillo"

L["customize.hint.attach"] = "Acoplar"
L["customize.hint.controller"] = "Modo con Mando esta Activo."
L["customize.hint.cursor"] = "Cursor"
L["customize.hint.cycle"] = "Mover de Ranura"
L["customize.hint.delete"] = "Borrar"
L["customize.hint.deselect"] = "Deseleccionar"
L["customize.hint.expand"] = "Expandir"
L["customize.hint.export"] = "Exportar"
L["customize.hint.favorite"] = "Favorito"
L["customize.hint.import"] = "Importar"
L["customize.hint.install"] = "Instalar"
L["customize.hint.last"] = "Ultima Ranura"
L["customize.hint.lastmode"] = "Último Modo"
L["customize.hint.nextmode"] = "Siguiente Modo"
L["customize.hint.open"] = "Abrir"
L["customize.hint.pan"] = "Paneo"
L["customize.hint.quicksave"] = "Guardado Rapido"
-- L["customize.hint.randomize"] = "Attach Random"
L["customize.hint.recalculate"] = "Recalcular"
L["customize.hint.recenter"] = "Recentrar"
L["customize.hint.rotate"] = "Rotar"
L["customize.hint.save"] = "Guardar"
L["customize.hint.select"] = "Seleccionar"
L["customize.hint.unattach"] = "Desacoplar"
L["customize.hint.unfavorite"] = "Remover favorito"
L["customize.hint.zoom"] = "Zoom"

L["customize.trivia.description"] = "Descripción"

L["customize.stats.explain.firepower"] = "El potencial de daño a quemarropa."
L["customize.stats.explain.rof"] = "La cadencia de fuego del arma."
L["customize.stats.explain.cyclic"] = "La cadencia de tiro cíclica del arma. Ignora factores como el retardo de la ráfaga o los requisitos de recarga."
L["customize.stats.explain.capacity"] = "Cuánta munición puede contener el arma en el cargador + recámara."
L["customize.stats.explain.range"] = "Alcance en el que el arma inflige el daño mínimo."
L["customize.stats.explain.precision"] = "La precisión del arma. Se mide en minutos de angulo (MOA)."
L["customize.stats.explain.muzzlevelocity"] = "La velocidad de salida de las balas disparadas con esta arma."
L["customize.stats.explain.ammo"] = "El tipo de munición que utiliza esta arma."
L["customize.stats.explain.penetration"] = "Cantidad de material que puede penetrar esta pistola. Medido en milímetros de madera."
L["customize.stats.explain.ricochet"] = "Máxima probabilidad de que las balas de esta arma reboten."
L["customize.stats.explain.armorpiercing"] = "Cantidad de daño de esta arma que ignora por completo la mayoría de las resistencias al daño."
L["customize.stats.explain.explosive"] = "Cantidad de daño explosivo que hará esta arma."
L["customize.stats.explain.speed"] = "Velocidad a la que puedes moverte mientras usas esta arma."
L["customize.stats.explain.aimtime"] = "El tiempo que se tarda en apuntar con la mira desde la cadera."
L["customize.stats.explain.sprinttofire"] = "El tiempo que se tarda en salir del sprint y empezar a disparar."
L["customize.stats.explain.firemodes"] = "A qué modos de disparo tiene acceso esta arma."
L["customize.stats.explain.burstdelay"] = "Tiempo que transcurre tras disparar una ráfaga antes de que el arma pueda volver a disparar."
L["customize.stats.explain.triggerdelay"] = "Retraso entre apretar el gatillo y disparar."
L["customize.stats.explain.noise"] = "Lo ruidosos que son los disparos del arma."
L["customize.stats.explain.sway"] = "Cantidad de estabilidad aplicada al arma."
L["customize.stats.explain.freeaim"] = "Ángulo máximo de puntería libre. Cuanto más bajo, mejor."
L["customize.stats.explain.supplylimit"] = "Cantidad de munición que el arma puede recibir de las fuentes de munición ARC9."

L["customize.bench.dummy"] = "PRUEBA BALÍSTICA CON MANIQUÍ"
L["customize.bench.effect"] = "EFECTO A DISTANCIA"
L["customize.bench.ballistics"] = "EVALUACIÓN DEL RENDIMIENTO BALÍSTICO TERMINAL"
L["customize.bench.precision"] = "ENSAYO MECÁNICO DE PRECISIÓN"

L["folder.back"] = "Atras"
L["folder.deselect"] = "Deseleccionar"
L["folder.favorites"] = "Favoritos"
L["folder.select"] = "Seleccionar"

////////////////////// Automatic stats
L["autostat.enable.pre"] = "Habilita"
L["autostat.disable.pre"] = "Deshabilita"
L["autostat.enable.post"] = ""
L["autostat.disable.post"] = ""

L["autostat.aimdownsightstime"] = "Tiemp. al Apuntar con la Mira"
L["autostat.alwaysphysbullet"] = "Siempre Balas Físicas"
L["autostat.ammopershot"] = "Municion por Disparo"
L["autostat.armdamage"] = "Daño a Brazo"
L["autostat.armorpiercing"] = "Penetración de Armadura"
L["autostat.autoburst"] = "Disparo a Ráfagas Automatico"
L["autostat.autoreload"] = "Recarga Pasiva"
L["autostat.bash"] = "Ataques Cuerpo a Cuerpo"
L["autostat.bashdamage"] = "Daño Cuerpo a Cuerpo"
L["autostat.bashlungerange"] = "Alcance de Estocada Cuerpo a Cuerpo"
L["autostat.bashrange"] = "Rango Cuerpo a Cuerpo"
L["autostat.bashspeed"] = "Velocidad cuerpo a cuerpo"
L["autostat.bipod"] = "Bipode"
L["autostat.bottomlessclip"] = "Cargador Sin Fondo"
L["autostat.breathholdtime"] = "Tiempo de Enfoque"
L["autostat.bulletguidance"] = "Rondas Guiadas"
L["autostat.bulletguidanceamount"] = "Factor de Guia"
L["autostat.canfireunderwater"] = "Disparar Bajo el Agua"
L["autostat.chambersize"] = "Capacidad de la Cámara"
L["autostat.chestdamage"] = "Daño al Torso"
L["autostat.clipsize"] = "Capacidad del Cargador"
L["autostat.cycletime"] = "Tiempo de Ciclo"
L["autostat.damagemax"] = "Daño a Corta Distancia"
L["autostat.damagemin"] = "Daño a Larga Distancia"
L["autostat.damagerand"] = "Variación de Daños"
L["autostat.deploytime"] = "Tiempo de Desenfundar"
L["autostat.distance"] = "Distancia de la Bala"
L["autostat.entitymuzzlevelocity"] = "Velocidad del Proyectil"
L["autostat.explosiondamage"] = "Daño por Explosión"
L["autostat.explosionradius"] = "Radio de la Explosión"
L["autostat.fixtime"] = "Tiempo de Desatasco"
L["autostat.freeaimradius"] = "Radio de Vista Libre"
L["autostat.headshotdamage"] = "Daño a la Cabeza"
L["autostat.heatcapacity"] = "Capacidad de Calor"
L["autostat.heatdissipation"] = "Disipación del Calor"
L["autostat.heatpershot"] = "Calor por Disparo"
L["autostat.hybridreload"] = "Recarga Individual Hibrida"
L["autostat.infiniteammo"] = "Munición Infinita"
L["autostat.legdamage"] = "Daño a Pierna"
L["autostat.malfunction"] = "Atasco"
L["autostat.malfunctionmeanshotstofail"] = "Media de Disparos para Fallo"
L["autostat.malfunctionwait"] = "Tiempo de Espera por Fallo"
L["autostat.manualaction"] = "Acción Manual"
L["autostat.manualactionchamber"] = "Disparos por Ciclo"
L["autostat.neverphysbullet"] = "Nunca Balas Físicas"
L["autostat.noflash"] = "No Fogonazo"
L["autostat.num"] = "Conteo de Proyectiles"
L["autostat.overheat"] = "Sobrecalentamiento"
L["autostat.overheattime"] = "Tiempo de Reparación por Sobrecalentamiento"
L["autostat.pelletspread"] = "Esparción de perdigones"
L["autostat.penetration"] = "Penetración de Material"
L["autostat.penetrationdelta"] = "Daño Tras Penetracion"
L["autostat.physbulletdrag"] = "Arrastre de Bala"
L["autostat.physbulletgravity"] = "Caída de Bala"
L["autostat.physbulletmuzzlevelocity"] = "Velocidad de Salida de la Bala"
L["autostat.postburstdelay"] = "Tiempo entre Ráfagas"
L["autostat.pushbackforce"] = "Fuerza de Contragolpe"
L["autostat.rangemax"] = "Rango Máximo"
L["autostat.rangemin"] = "Rango Mínimo de Daños"
L["autostat.recoil"] = "Retroceso"
L["autostat.recoilautocontrol"] = "Tiempo de Reseteo del Retroceso"
L["autostat.recoildissipationrate"] = "Tasa de Disipación del Retroceso"
L["autostat.recoilkick"] = "Retroceso Sentido"
L["autostat.recoilmodifiercap"] = "Máximo retroceso acumulado"
L["autostat.recoilpatterndrift"] = "Desviación del Retroceso"
L["autostat.recoilrandomside"] = "Propagacion del Retroceso Horizontal"
L["autostat.recoilrandomup"] = "Propagacion del Retroceso Vertical"
L["autostat.recoilresettime"] = "Recoil Reset Time"
L["autostat.recoilside"] = "Retroceso Horizontal"
L["autostat.recoilup"] = "Retroceso Vertical"
L["autostat.reloadtime"] = "Tiempo de Recarga"
L["autostat.ricochetanglemax"] = "Ángulo de Rebote"
L["autostat.ricochetchance"] = "Probablidad de Rebote"
L["autostat.rpm"] = "Disparos por Minuto"
L["autostat.runawayburst"] = "Ráfaga Incontrolable"
L["autostat.secondarysupplylimit"] = "Municion Secundaria de Reserva"
L["autostat.shootvolume"] = "Volumen de Informe"
L["autostat.shootwhilesprint"] = "Disparar al Esprintar"
L["autostat.shotgunreload"] = "Recarga Individual"
L["autostat.speed"] = "Velocidad de Movimiento"
L["autostat.spread"] = "Precisión"
L["autostat.sprinttofiretime"] = "Tiempo de Sprint Hasta el Disparo"
L["autostat.stomachdamage"] = "Daño al Estomago"
L["autostat.supplylimit"] = "Cargadores de Reserva"
L["autostat.sway"] = "Estabilidad"
L["autostat.triggerdelay"] = "Tiempo de Retraso del Disparo"
L["autostat.triggerdelaytime"] = "Tiempo de Retardo de Gatillo"
L["autostat.visualrecoil"] = "Retroceso Visual"
L["autostat.visualrecoilpunch"] = "Golpe de Retroceso Visual"
L["autostat.visualrecoilroll"] = "Giro de Retroceso Visual"
L["autostat.visualrecoilside"] = "Retroceso Horizontal Visual"
L["autostat.visualrecoilup"] = "Retroceso Vertical Visual"

-- L["autostat.secondary._beforephrase"] = "PLEASE TRANSLATE"
-- if true, secondary stat phrasing comes before the stat
-- L["autostat.secondary._divider"] = "PLEASE TRANSLATE"
-- space between the secondary phrase from the stat phrase. set true to use empty string

L["autostat.secondary.bipod"] = "en Bípode"
-- L["autostat.secondary.blindfire"] = "while Blind-Firing"
L["autostat.secondary.crouch"] = "mientras está agachado"
L["autostat.secondary.empty"] = "en la ultima ronda del cargador"
L["autostat.secondary.evenreload"] = "cada recarga pareja"
L["autostat.secondary.evenshot"] = "cada disparo parejo"
L["autostat.secondary.first"] = "en el primer disparo"
L["autostat.secondary.firstshot"] = "en el primer disparo"
L["autostat.secondary.heated"] = "while Heated"
L["autostat.secondary.hipfire"] = "en Hipfire"
L["autostat.secondary.hot"] = "from Heat"
L["autostat.secondary.last"] = "en la ultima ronda del cargador"
L["autostat.secondary.lastshot"] = "en la ultima ronda del cargador"
L["autostat.secondary.midair"] = "en el aire"
L["autostat.secondary.move"] = "mientras se mueve"
L["autostat.secondary.oddreload"] = "cada recarga rara"
L["autostat.secondary.oddshot"] = "cada disparo raro"
L["autostat.secondary.recoil"] = "del retroceso" --"With Each Shot"
L["autostat.secondary.shooting"] = "mientras dispara"
L["autostat.secondary.sighted"] = "while Sighted"
L["autostat.secondary.sights"] = "en la mira"
L["autostat.secondary.silenced"] = "cuando está silenciado"
L["autostat.secondary.true"] = "cuando Verdaderos Nombres está activo"
L["autostat.secondary.ubgl"] = "en UBGL"

////////////////////// Blacklist menu
L["blacklist.title"] = "ARC9 Lista negra de accesorios"
L["blacklist.desc"] = "Se bloqueará el uso de los accesorios marcados aquí"
L["blacklist.blisted"] = "MARCADO"
L["blacklist.all"] = "TODO"
L["blacklist.id"] = "ID"
L["blacklist.name"] = "NOMBRE"
L["blacklist.filter"] = "FILTRAR"

////////////////////// Incompatible addons
L["incompatible.title"] = "ARC9: ADDONS NO COMPATIBLES"
L["incompatible.line1"] = "Usted tiene algunos addons que se sabe que no funcionan con ARC9."
L["incompatible.line2"] = "Desactívelos o espere un comportamiento defectuoso."
L["incompatible.confirm"] = "Confirmar"
L["incompatible.wait"] = "Esperar {time}s"
L["incompatible.never"] = "No volver a advertirme."
L["incompatible.never.hover"] = "¿Estás completamente seguro de que entiendes las consecuencias?"
L["incompatible.never.confirm"] = "Ha elegido no volver a mostrar advertencias de incompatibilidad. Si encuentras errores o comportamientos rotos, es tu responsabilidad."

////////////////////// Presets
L["customize.presets.atts"] = " Accesorios"
L["customize.presets.back"] = "Atras"
L["customize.presets.cancel"] = "Cancelar"
L["customize.presets.code"] = "Codigo de Preajuste (Copiado a Portapapeles)"
L["customize.presets.default"] = "Por Defecto"
L["customize.presets.default.long"] = "Preajuste Por Defecto"
L["customize.presets.dumb"] = "Eres tonto"
L["customize.presets.import"] = "Importar"
L["customize.presets.invalid"] = "Cadena no valida!"
L["customize.presets.new"] = "Nuevo Nombre de Preajuste"
L["customize.presets.paste"] = "Pega Codigo de Preajuste Aqui"
L["customize.presets.random"] = "Aleatorio"
L["customize.presets.save"] = "Guardar"
L["customize.presets.unnamed"] = "Sin Nombre"

L["customize.presets.deldef"] = "¿Estás seguro de que quieres borrar \"{name}\" preajuste por defecto?"
L["customize.presets.deldef2"] = "Tendrías que resetear arma en ajustes de desarrollador para devolverla."
L["customize.presets.yes"] = "Si"

////////////////////// Tips
L["tips.arc-9"] = "Es ARC9, no ARC-9, no Arc9."
L["tips.blacklist"] = "Puede poner los archivos adjuntos en una lista negra. Consulte la descripción del workshop de ARC9 para obtener más información."
L["tips.bugs"] = "Informa de los errores en el servidor oficial de Discord o, mejor aún, abre una propuesta en Github."
L["tips.custombinds"] = "Las combinaciones de teclas ARC9 se pueden sustituir por vinculaciones personalizadas. Empieza a escribir +arc9_ para encontrar las vinculaciones disponibles."
L["tips.cyberdemon"] = "Para matar al terrorista, dispárale hasta que esté muerto."
L["tips.description"] = "Le aconsejamos que lea las descripciones de los addons antes de hacer comentarios."
L["tips.development"] = "¿Quieres desarrollar contenido para ARC9? El servidor oficial de Discord tiene muchos recursos para ayudarte."
L["tips.discord"] = "¡Únete a Diamond Doves en Discord! El enlace está en la descripción ARC9 y en la parte superior de la configuración."
L["tips.external"] = "Si utiliza la versión Github de ARC9, asegúrese de actualizarla con frecuencia."
L["tips.hints"] = "Mantén encendido el HUD de ARC9 para ver las pistas de controles."
L["tips.lean"] = "Para inclinarse manualmente, vincule las teclas a +alt1 y +alt2."
L["tips.love"] = "No dudes en decir a los desarrolladores que aprecias su trabajo. Nos ayuda mucho a seguir adelante."
L["tips.m9k"] = "¡Hecha un vistazo a las armas M9K!."
L["tips.official"] = "Descargue ARC9 únicamente de fuentes oficiales. Las cargas de terceros pueden ser maliciosas o estar desactualizadas."
L["tips.presets"] = "Comparte tus preajustes favoritos con tus amigos exportándolos."
L["tips.settings"] = "Puede desactivar estos consejos, y muchos más, en los ajustes de ARC9. Haga clic en el botón de la esquina superior izquierda."
-- L["tips.tacrp"] = "Have you tried Tactical RP base yet?"
L["tips.tips"] = "Los consejos tienen un orden fijo. Siga leyendo y acabará viéndolos todos."
L["tips.tolerance"] = "Todas las bases de armas funcionan bien juntas. No hay necesidad de favoritismos."

////////////////////// Other
L["atts.favourites"] = "Favoritos"
L["atts.filter"] = "Filtrar"

/////////////////////////////////////// Settings menu
-- Use this method to localize convars in settings menu:
-- settings.convar.title = "Convar Title"
-- settings.convar.desc = "Convar Description"

L["settings.title"] = "Ajustes ARC9"
L["settings.desc"] = "Descripción"

L["settings.default_convar"] = "Valor predeterminado"

////////////////////// General
L["settings.tabname.general"] = "General"

L["settings.general.client"] = "Cliente"
L["settings.truenames.title"] = "Nombres reales"
L["settings.truenames.desc"] = "Establece si usar los nombres reales de las armas o nombres ficticios hechos por los desarrolladores. No todas las armas lo utilizan.\n\nLa configuración del servidor puede anular esta preferencia."
L["settings.resetsettings.cl.title"] = "Restablecer todos los ajustes del CLIENTE"

L["settings.general.server"] = "Servidor"
L["settings.truenames_default.title"] = "Nombres reales por defecto"
L["settings.truenames_default.desc"] = "Establece el modo de nombres reales por defecto en el servidor. Todos los jugadores que utilicen \"Default\" en preferencia lo utilizarán."
L["settings.truenames_enforced.title"] = "Nombres reales por defecto forcado"
L["settings.truenames_enforced.desc"] = "Establecer para obligar a todos los jugadores a utilizar la configuración del servidor para los nombres verdaderos."

L["settings.resetsettings.sv.title"] = "Restablecer todos los ajustes del SERVIDOR"

L["settings.reset"] = "Restablecer!"

////////////////////// Performance
L["settings.tabname.performance"] = "Rendimiento"

-- L["settings.optics.cheapscopes.title"] = "Cheap Scopes"
-- L["settings.optics.cheapscopes.desc"] = "A cheap RT scope implementation by zooming your whole view to aim, instead of rendering world again in a scope. Significantly increases performance on large maps."

L["settings.performance.important"] = "Importante"
L["settings.cheapscopes.title"] = "Miras Baratas"
L["settings.cheapscopes.desc"] = "Una implementación barata de miras RT mediante el zoom de toda la vista para apuntar, en lugar de renderizar el mundo de nuevo en una mira. Aumenta significativamente el rendimiento en mapas grandes."
L["settings.tpik.title"] = "TPIK"
L["settings.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) es un sistema que permite que la mayoría de las armas se muestren detalladas e igual que en primera persona, posiciones de manos, recarga y animaciones de disparo en tercera persona.\n\nConfigúralo en la pestaña Visuales."
L["settings.allflash.title"] = "Todas las Linternas"
L["settings.allflash.desc"] = "Renderiza completamente todas las linternas de otros jugadores.\n\nMuy caro en los servidores."

L["settings.performance.blur.title"] = "Difuminacion"
L["settings.cust_blur.title"] = "Fondo de personalización"
L["settings.cust_blur.desc"] = "Difumina Fondo de personalización."
L["settings.fx_reloadblur.title"] = "Mientras Recarga"
L["settings.fx_reloadblur.desc"] = "Difumina el Mundo Mientras Recarga."
L["settings.fx_animblur.title"] = "Mientras se Prepara"
L["settings.fx_animblur.desc"] = "Difumina el mundo mientras despliegas un arma por primera vez."
L["settings.fx_rtblur.title"] = "En miras telescópicas"
L["settings.fx_rtblur.desc"] = "Difumina el mundo mientras utilizas un miras telescópicas."
L["settings.fx_adsblur.title"] = "En miras normales"
L["settings.fx_adsblur.desc"] = "Difumina el arma mientras apuntas con miras de hierro u holográficas."

L["settings.performance.shelleject.title"] = "Expulsión del proyectil"
L["settings.eject_fx.title"] = "Efectos de Humo"
L["settings.eject_fx.desc"] = "Producir efectos de humo a partir de los casquillos expulsados, cuando el arma admita esta función."
L["settings.eject_time.title"] = "Tiemp. Vida"
L["settings.eject_time.desc"] = "Permiten que los casquillos permanezcan más tiempo en el mundo. Puede afectar al rendimiento."

L["settings.performance.fx.title"] = "Efectos"
L["settings.muzzle_light.title"] = "Fogonazo"
L["settings.muzzle_light.desc"] = "Habilita la luz emitida por los fogonazos al disparar un arma."
L["settings.muzzle_others.title"] = "Otros efectos de fogonazos"
L["settings.muzzle_others.desc"] = "Activa los efectos de boca de las armas de otros jugadores."

////////////////////// Optics
L["settings.tabname.optics"] = "Miras"

L["settings.optics.control"] = "Control"
L["settings.optics.sensmult.title"] = "Multiplicar sensibilidad ADS"
L["settings.optics.sensmult.desc"] = "Multiplique la sensibilidad de la mirada por esta cantidad al apuntar.\nCuanto menor sea el valor, menor será la sensibilidad.\nÚtil cuando se utilizan mandos, o si el usuario sólo desea una menor sensibilidad de puntería."
L["settings.optics.compensate_sens.title"] = "Compensar Sensibilidad"
L["settings.optics.compensate_sens.desc"] = "Compensar sensibilidad por ampliados."
L["settings.optics.toggleads.title"] = "Alternar ADS"
L["settings.optics.toggleads.desc"] = "Al apuntar se alternará la mira."

L["settings.optics.color"] = "Color"
L["settings.optics.reflex.title"] = "Miras Holográficas"
L["settings.optics.reflex.desc"] = "Color a utilizar para miras holográficas.\n\nNo todas las miras admiten esta función."
L["settings.optics.scope.title"] = "Visores"
L["settings.optics.scope.desc"] = "Color a utilizar para visores ampliados.\n\nNo todas las miras admiten esta función."

////////////////////// Crosshair
L["settings.tabname.crosshair"] = "Punto de Mira"

L["settings.crosshair.crosshair"] = "Punto de Mira"
L["settings.crosshair.cross_enable.title"] = "Habilitar Punto de Mira"
L["settings.crosshair.cross_enable.desc"] = "Habilitar el punto de mira. Algunas armas no permiten utilizar el punto de mira."
L["settings.crosshair.cross.title"] = "Color de Punto de Mira"
L["settings.crosshair.cross.desc"] = "El color de tu punto de mira."
L["settings.crosshair.cross_size_mult.title"] = "Tamaño de Punto de Mira"
L["settings.crosshair.cross_size_mult.desc"] = "Multiplica el tamaño de tu punto de mira"
L["settings.crosshair.cross_size_dot.title"] = "Tamaño de Punto"
L["settings.crosshair.cross_size_dot.desc"] = "Multiplica el tamaño del punto medio"
L["settings.crosshair.cross_size_prong.title"] = "Tamaño de Puntas"
L["settings.crosshair.cross_size_prong.desc"] = "Multiplica el tamaño de las puntas exteriores."
L["settings.crosshair.crosshair_static.title"] = "Punto de Mira Estático"
L["settings.crosshair.crosshair_static.desc"] = "Activa el punto de mira estática, que no se mueve al disparar."
L["settings.crosshair.crosshair_force.title"] = "Forzar Punto de Mira"
L["settings.crosshair.crosshair_force.desc"] = "Fuerza el punto de mira incluso en armas que no quieren que la veas.\n\nConfiguracion del servidor."

////////////////////// Customization
L["settings.tabname.hud_cust"] = "Customización"

L["settings.hud_cust.hud"] = "HUD"
L["settings.hud_cust.hud_scale.title"] = "Tamaño del HUD"
L["settings.hud_cust.hud_scale.desc"] = "Multiplicador de escala para el HUD de ARC9."
L["settings.hud_cust.hud_deadzonex.title"] = "Anchura de zona muerta del HUD"
L["settings.hud_cust.hud_deadzonex.desc"] = "\"Zona Muerta\" Horizontal para el menú de personalización y el panel HUD.\nÚtil para monitores ultrawide."
L["settings.hud_cust.hud_color.title"] = "Color del HUD"
L["settings.hud_cust.hud_color.desc"] = "Color de realce para el HUD.\nEl color de acento."
-- L["settings.hud_cust.language_id.title"] = "Language"
-- L["settings.hud_cust.language_id.desc"] = "Language pack to use for ARC9."
L["settings.hud_cust.hud_darkmode.title"] = "Tema Oscuro"
L["settings.hud_cust.hud_darkmode.desc"] = "Activa los colores oscuros en el HUD en lugar del gris claro y desactiva el efecto viñeta en el fondo."
L["settings.hud_cust.cust_light.title"] = "Habilitar Luz"
L["settings.hud_cust.cust_light.desc"] = "Activa la iluminación del arma en el menú de personalización.\n\nLo mismo que el botón cerca del botón de configuración."
L["settings.hud_cust.cust_light_brightness.title"] = "Brillo de Luz"
L["settings.hud_cust.cust_light_brightness.desc"] = "Cómo de brillante será la luz del panel de personalización.\n\nPero no olvides encenderlo antes!"

L["settings.hud_cust.customization"] = "Customización"
L["settings.hud_cust.cust_hints.title"] = "Pistas"
L["settings.hud_cust.cust_hints.desc"] = "Habilita pistas en el menu de modificacion."
-- L["settings.hud_cust.cust_roll_unlock.title"] = "Unlock Roll" -- NOT USED ANYMORE
-- L["settings.hud_cust.cust_roll_unlock.desc"] = "Allow weapon roll in the customization menu.\n\nMight look and control not the best way." -- NOT USED ANYMORE
L["settings.hud_cust.cust_tips.title"] = "Consejos"
L["settings.hud_cust.cust_tips.desc"] = "Consejos sobre la base ARC9 cerca de pistas."
L["settings.hud_cust.cust_exit_reset_sel.title"] = "Salir Restablece la selección"
L["settings.hud_cust.cust_exit_reset_sel.desc"] = "Al salir del menú de personalización se restablece la selección de ranura activa."

////////////////////// Game HUD
L["settings.tabname.hud_game"] = "HUD"

L["settings.hud_game.lcd"] = "Panel LCD"
L["settings.hud_game.hud_arc9.title"] = "Habilitar HUD"
L["settings.hud_game.hud_arc9.desc"] = "Habilita HUD para armas ARC9."
L["settings.hud_game.hud_always.title"] = "En todas las armas"
L["settings.hud_game.hud_always.desc"] = "Habilita el HUD en todas las armas."
L["settings.hud_game.hud_compact.title"] = "Modo Compacto"
L["settings.hud_game.hud_compact.desc"] = "Aspecto compacto para el panel HUD."
L["settings.hud_game.hud_nohints.title"] = "Deshabilita Pistas"
L["settings.hud_game.hud_nohints.desc"] = "Deshabilita completamente las pistas. No aparecerán en el HUD 3D ni en el HUD 2D."
L["settings.hud_game.hud_keephints.title"] = "Mantener Pistas"
L["settings.hud_game.hud_keephints.desc"] = "Mostrar las pistas de control ARC9 en la parte superior en el panel HUD."

L["settings.hud_game.killfeed"] = "Killfeed"
L["settings.hud_game.killfeed_enable.title"] = "Iconos del Killfeed"
L["settings.hud_game.killfeed_enable.desc"] = "Activar la generación automática de iconos de killfeed para armas ARC9."
L["settings.hud_game.killfeed_dynamic.title"] = "Actualizacion Dinamica"
L["settings.hud_game.killfeed_dynamic.desc"] = "Los iconos de Killfeed se regenerarán después de cada muerte.\n\nDesactívalo si quieres conseguir esos 0,1 fps."
L["settings.hud_game.killfeed_color.title"] = "Iconos a todo color"
L["settings.hud_game.killfeed_color.desc"] = "Los iconos generados dinámicamente están totalmente coloreados."

L["settings.hud_game.breath"] = "Respiración"
L["settings.hud_game.breath_hud.title"] = "HUD de respiración"
L["settings.hud_game.breath_hud.desc"] = "Muestra una barra que indica el aliento que te queda mientras estabilizas el arma en la mira."
L["settings.hud_game.breath_pp.title"] = "Post-procesado de respiración"
L["settings.hud_game.breath_pp.desc"] = "Mantener la respiración también añadirá efectos de post-procesado a tu pantalla."
L["settings.hud_game.breath_sfx.title"] = "SFX de respiración"
L["settings.hud_game.breath_sfx.desc"] = "Si mantienes la respiración, se reproducirán los efectos de sonido asociados."

L["settings.hud_game.centerhint"] = "Consejos"
L["settings.hud_game.centerhint_reload.title"] = "Mostrar Consejo de Recarga"
L["settings.hud_game.centerhint_reload.desc"] = "Muestra un aviso de recarga cuando te quede poca munición."
L["settings.hud_game.centerhint_reload_percent.title"] = "Porcentaje de Cargador"
L["settings.hud_game.centerhint_reload_percent.desc"] = "Muestra un consejo de recarga cuando el cargador actual está en este valor porcentual."
L["settings.hud_game.centerhint_bipod.title"] = "Mostrar Alternar Bípode"
L["settings.hud_game.centerhint_bipod.desc"] = "Mostrar un consejo cuando el bípode se puede conmutar."

////////////////////// NPCs
L["settings.tabname.npc"] = "NPCs"

L["settings.npc.weapons"] = "Armas de NPCs"
L["settings.npc.npc_equality.title"] = "Igualdad de daños"
L["settings.npc.npc_equality.desc"] = "Los NPCs hacen tanto daño como los jugadores.\n\nEsto es una variable del servidor."
L["settings.npc.npc_spread.title"] = "Precisión de NPCs"
L["settings.npc.npc_spread.desc"] = "Multiplicador de la imprecisión de los NPCs al disparar."
L["settings.npc.npc_atts.title"] = "Dar Accesorios"
L["settings.npc.npc_atts.desc"] = "Las armas ARC9 creadas o entregadas reciben un conjunto aleatorio de accesorios.\n\nEsto es una variable del servidor."
L["settings.npc.npc_autoreplace.title"] = "Reemplazar armas de NPCs"
L["settings.npc.npc_autoreplace.desc"] = "Reemplazar armas NPCs con armas ARC9 elegidas al azar.\n\nEsta es una variable del servidor."
L["settings.npc.replace_spawned.title"] = "Sustituir armas terrestres"
L["settings.npc.replace_spawned.desc"] = "Reemplazar armas de HL2 del mapa/generadas con armas ARC9 elegidos al azar.\n\nEsta es una variable de servidor."
L["settings.npc.npc_give_weapons.title"] = "Jugadores pueden dar armas"
L["settings.npc.npc_give_weapons.desc"] = "Los jugadores pueden pulsar E en los NPCs para darles su arma.\n\nEsta es una variable del servidor."

////////////////////// Gameplay
L["settings.tabname.gameplay"] = "Gameplay"

L["settings.gameplay.controls"] = "Controles"
L["settings.gameplay.toggleads.title"] = "Habilitar ADS"
L["settings.gameplay.toggleads.desc"] = "Al apuntar se alternarán las miras."
L["settings.gameplay.autolean.title"] = "Inclinacion Automatica"
L["settings.gameplay.autolean.desc"] = "La puntería intentará inclinarse automáticamente si es posible."
L["settings.gameplay.autoreload.title"] = "Recarga Automatica"
L["settings.gameplay.autoreload.desc"] = "Las armas de ARC9 vacías se recargarán automáticamente."
L["settings.gameplay.togglelean.title"] = "Alternar Inclinación"
L["settings.gameplay.togglelean.desc"] = "Al pulsar las teclas de inclinación se alternará la inclinación en lugar de tener que mantenerlas pulsadas.\n\nFunciona mal en conjunto a autoinclinacion. Si se utiliza la alternacion de inclinación, debe desactivar autoinclinacion"
L["settings.gameplay.togglepeek.title"] = "Alternar Vistazo"
L["settings.gameplay.togglepeek.desc"] = "Al pulsar la tecla de vistazo se activará el vistazo en lugar de tener que mantenerla pulsada."
L["settings.gameplay.togglepeek_reset.title"] = "Restablecer estado de Vistazo después de apuntar"
L["settings.gameplay.togglepeek_reset.desc"] = "(Sólo si Alternar Vistazo está activado)\nEl estado de vistazo no se conservará al salir de las miras de puntería."
L["settings.gameplay.togglebreath.title"] = "Alternar contener la respiración"
L["settings.gameplay.togglebreath.desc"] = "Al pulsar la tecla Contener la respiración se activará Contener la respiración en lugar de tener que mantenerla pulsada."

L["settings.gameplay.mechanics"] = "Mecánicas de Juego"
L["settings.gameplay.infinite_ammo.title"] = "Munición Infinita"
L["settings.gameplay.infinite_ammo.desc"] = "Las armas tienen munición infinita.\n\nEsta es una variable del servidor."
L["settings.gameplay.realrecoil.title"] = "Retroceso Visual Fisico"
L["settings.gameplay.realrecoil.desc"] = "Las armas configuradas para esta función experimentan una elevación física de la boca del cañón, lo que significa que dispararán donde lo muestre su modelo de vista y no en el centro de la pantalla. Esto es muy importante para el equilibrio de algunos paquetes de armas.\n\nEsta es una variable del servidor."
L["settings.gameplay.lean.title"] = "Inclinacion"
L["settings.gameplay.lean.desc"] = "Si los jugadores pueden inclinarse con +alt1 y +alt2, incluyendo inclinación automática.\n\nEsta es una variable del servidor."
L["settings.gameplay.mod_sway.title"] = "Estabilidad"
L["settings.gameplay.mod_sway.desc"] = "Las armas tendrán estabilidad, si están configuradas para usarlo.\n\nEsta es una variable del servidor."
L["settings.gameplay.mod_freeaim.title"] = "Vista Libre"
L["settings.gameplay.mod_freeaim.desc"] = "Las armas tendrán puntería libre, y no siempre dispararán en el centro de la pantalla.\n\nEsta es una variable del servidor."
L["settings.gameplay.mod_bodydamagecancel.title"] = "Cancelación del daño corporal"
L["settings.gameplay.mod_bodydamagecancel.desc"] = "Anula el multiplicador de daño corporal por defecto. Sólo desactivar si se utiliza otro mod que proporciona este tipo de funcionalidad.\ne.g. Mods que cambian los multiplicadores de las extremidades por defecto.\n\nEsta es una variable de servidor."
L["settings.gameplay.breath_slowmo.title"] = "Respiración Slow-Mo"
L["settings.gameplay.breath_slowmo.desc"] = "Contener la respiración ralentiza el tiempo.\n\nNo disponible en multijugador."
L["settings.gameplay.manualbolt.title"] = "Ciclado Manual"
L["settings.gameplay.manualbolt.desc"] = "Las armas de cerrojo o bombeo configuradas para esta función sólo se cerrojarán cuando se pulse R, y no cuando se suelte la tecla de ataque."
L["settings.gameplay.never_ready.title"] = "Anims \"No Preparado\""
L["settings.gameplay.never_ready.desc"] = "Deshabilitar animaciones de preparacion al desplegar arma."
L["settings.gameplay.recoilshake.title"] = "Sacudida FOV de retroceso"
L["settings.gameplay.recoilshake.desc"] = "Sacude el campo de visión al disparar"
L["settings.gameplay.equipment_generate_ammo.title"] = "Tipos de munición únicos para equipamiento"
L["settings.gameplay.equipment_generate_ammo.desc"] = "Hay un límite de 255 tipos de munición, y desactivar esta opción puede ayudar a solucionar algunos problemas si tienes muchos addons.\n\nEsta es una variable del servidor.\n\nRequiere reinicio."

-- ??
L["settings.gameplay.mult_defaultammo.title"] = "Munición de reserva por defecto"
L["settings.gameplay.mult_defaultammo.desc"] = "¿Cuántos cargadores/granadas/equipos se dan al jugador cuando coge el arma por primera vez?\n\nEsta es una variable del servidor."
L["settings.gameplay.nearwall.title"] = "Cerca de la pared"
L["settings.gameplay.nearwall.desc"] = "No permite disparar el arma cuando se está demasiado cerca de la pared o cualquier obstáculo."

////////////////////// Visuals
L["settings.tabname.visuals"] = "Visuales"

L["settings.visuals.viewmodel"] = "Modelo de 1ra Persona"
L["settings.visuals.vm_bobstyle.title"] = "Estilo de Balanceo"
L["settings.visuals.vm_bobstyle.desc"] = "Seleccione diferentes estilos de balanceo, al gusto de los diferentes miembros del equipo ARC9 (y valve software), yendo del estilo más nuevo al más antiguo."
L["settings.visuals.fov.title"] = "FOV"
L["settings.visuals.fov.desc"] = "Añade FOV (CAMPO DE VISION) al modelo de 1ra persona. Aumenta o disminuye el modelo. Uso responsable."
L["settings.visuals.vm_addx.title"] = "Agregar X"
L["settings.visuals.vm_addx.desc"] = "Desplaza el modelo a la derecha o a la izquierda."
L["settings.visuals.vm_addy.title"] = "Agregar Y"
L["settings.visuals.vm_addy.desc"] = "Desplaza el modelo hacia delante y hacia atrás."
L["settings.visuals.vm_addz.title"] = "Agregar Z"
L["settings.visuals.vm_addz.desc"] = "Desplaza el modelo arriba y abajo."

L["settings.visuals.cambob"] = "Balanceo de Vista"
L["settings.visuals.vm_cambob.title"] = "Balanceo al Esprintar"
L["settings.visuals.vm_cambob.desc"] = "Hace que tu cámara se mueva cuando esprintas"
L["settings.visuals.vm_cambobwalk.title"] = "Balanceo de Vista al Caminar"
L["settings.visuals.vm_cambobwalk.desc"] = "Hace que tu cámara se mueva ligeramente cuando caminas (requiere balanceo al esprintar)"
L["settings.visuals.vm_cambobintensity.title"] = "Intensidad"
L["settings.visuals.vm_cambobintensity.desc"] = "Qué tan intenso será el balanceo"

L["settings.visuals.tpik"] = "TPIK"
L["settings.visuals.tpik.title"] = "Habilitar TPIK"
L["settings.visuals.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) es un sistema que permite que la mayoría de las armas se muestren detalladas e igual que en primera persona, posiciones de manos, recarga y animaciones de disparo en tercera persona."
L["settings.visuals.tpik_others.title"] = "TPIK de otros jugadores"
L["settings.visuals.tpik_others.desc"] = "Mostrar TPIK para otros jugadores que no seas tú. Impacta negativamente en el rendimiento."
L["settings.visuals.tpik_framerate.title"] = "TPIK FPS"
L["settings.visuals.tpik_framerate.desc"] = "Velocidad de fotogramas máxima a la que puede funcionar TPIK. Establecer a 0 para ilimitado."

////////////////////// Bullet Physics
L["settings.tabname.bullets"] = "Balas Fisicas"

L["settings.bullets.bullets"] = "Balas Físicas"
L["settings.bullets.bullet_physics.title"] = "Balas Físicas"
L["settings.bullets.bullet_physics.desc"] = "Las armas que admitan esta característica dispararán balas físicas, que tienen caída, tiempo de recorrido y arrastre.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_gravity.title"] = "Gravedad"
L["settings.bullets.bullet_gravity.desc"] = "Multiplicador para la gravedad de la bala.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_drag.title"] = "Arrastre"
L["settings.bullets.bullet_drag.desc"] = "Multiplicador para el arrastre de balas.\n\nEsta es una variable del servidor."
L["settings.bullets.ricochet.title"] = "Rebote"
L["settings.bullets.ricochet.desc"] = "Las balas disparadas con armas seleccionadas a veces pueden rebotar en las superficies y seguir viajando y causando daño.\n\nEsta es una variable del servidor."
L["settings.bullets.mod_penetration.title"] = "Penetracion"
L["settings.bullets.mod_penetration.desc"] = "Las balas disparadas desde armas seleccionadas pueden penetrar superficies e infligir daño a lo que haya al otro lado.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_lifetime.title"] = "Tiempo De Vida"
L["settings.bullets.bullet_lifetime.desc"] = "Tiempo en segundos tras el cual se borrará una bala.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_imaginary.title"] = "Balas Imaginarias"
L["settings.bullets.bullet_imaginary.desc"] = "Las balas parecerán viajar hacia la skybox, más allá de los límites del mapa."

////////////////////// Attachments
L["settings.tabname.attachments"] = "Accesorios"

L["settings.attachments.customization"] = "Customización"
L["settings.attachments.atts_nocustomize.title"] = "Deshabilitar Customización"
L["settings.attachments.atts_nocustomize.desc"] = "Deshabilita toda customización a través del menú.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_max.title"] = "Accesorios Máx."
L["settings.attachments.atts_max.desc"] = "El número máximo de accesorios que se pueden poner en un arma, incluidos los accesorios cosméticos.\n\nEsta es una variable del servidor."
L["settings.attachments.autosave.title"] = "Autoguardado"
L["settings.attachments.autosave.desc"] = "Tus últimas opciones de customización del arma se guardarán y se aplicarán automáticamente la próxima vez que aparezca esa arma."
L["settings.attachments.blacklist.title"] = "Menú Lista negra"
L["settings.attachments.blacklist.open"] = "Abrir"

L["settings.attachments.inventory"] = "Inventario"
L["settings.attachments.free_atts.title"] = "Accesorios Gratis"
L["settings.attachments.free_atts.desc"] = "Los archivos adjuntos se pueden utilizar sin ser recogidos primero.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_lock.title"] = "Uno Para Todos"
L["settings.attachments.atts_lock.desc"] = "Recoger una instancia de un accesorio te permite usarlo infinitas veces en todas tus armas.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_loseondie.title"] = "Perder En Muerte"
L["settings.attachments.atts_loseondie.desc"] = "Tu inventario de accesorios se perderá cuando mueras.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_generateentities.title"] = "Generar Entidades"
L["settings.attachments.atts_generateentities.desc"] = "Genera entidades que pueden ser engendradas, permitiéndote recoger accesorios cuando los accesorios gratis están desactivados.\n\nPuede aumentar el tiempo de carga.\n\nEsta es una variable del servidor."

////////////////////// Modifiers
L["settings.tabname.modifiers"] = "Modificadores"

-- L["settings.modifiers.quick.desc"] = "We are a little sorry but we couldn't finish them to release. You will have to use advanced modifiers in  spawnmenu > Options > ARC9 > Modifiers  for now."

L["settings.modifiers.quick.desc"] = "Lo sentimos pero no hemos podido terminarlos a la fecha de lanzamiento. Tendrás que usar los modificadores avanzados en  spawnmenu > Options > ARC9 > Modifiers por ahora."

L["settings.modifiers.quick.title"] = "Modificadores rápidos de estadísticas"
L["settings.mod_damage.title"] = "Daño"
L["settings.mod_spread.title"] = "Precisión"
L["settings.mod_recoil.title"] = "Retroceso"
L["settings.mod_visualrecoil.title"] = "Retroceso Visual"
L["settings.mod_adstime.title"] = "Tiempo para apuntar con mira"
L["settings.mod_sprinttime.title"] = "Tiempo de Esprint a Disparo"
L["settings.mod_damagerand.title"] = "Variación de daños"
L["settings.mod_muzzlevelocity.title"] = "Velocidad de salida"
L["settings.mod_rpm.title"] = "DPM"
L["settings.mod_headshotdamage.title"] = "Daño por tiro a cabeza"
L["settings.mod_malfunction.title"] = "Probabilidad de fallo"

////////////////////// Controller
L["settings.tabname.controller"] = "Mando"

L["settings.controller.misc"] = "Varios"
L["settings.controller.misc.desc"] = "Debería haber un botón que abra el panel con la configuración avanzada del controlador, pero por ahora está en spawnmenu > Options > ARC9 > Controller."
L["settings.controller.controller.title"] = "Glifos del mando"
L["settings.controller.controller.desc"] = "Habilitar glifos personalizados compatibles con el mando, mostrando los botones del controlador en lugar de las teclas predeterminadas."
-- L["settings.controller.controller_rumble.title"] = "Rumble"
-- L["settings.controller.controller_rumble.desc"] = "Enable controller rumble as long as Fesiug's DLL mod is loaded.\n\ngithub.com/Fesiug/\ngmod-sinput"
L["settings.controller.controller_config.title"] = "Configuracion avanzada"
L["settings.controller.controller_config.content"] = "Abrir panel"
L["settings.controller.controller_config.desc"] = "Abra el panel de configuración avanzada del mando."

////////////////////// Asset Caching
L["settings.tabname.caching"] = "Almac. en caché"
L["settings.caching.title"] = "Almac. en caché"
L["settings.caching.desc"] = "¡Puede almacenar en caché algunos recursos ARC9 (guardarlos en memoria sin cargarlos mientras juega) para evitar tartamudeos y disfrutar de un juego más cómodo!\n\nSeguramente deberías habilitar algunas cosas si tu gmod funciona en HDD."

L["settings.caching.precache_sounds_onfirsttake.title"] = "Al equipar: Almacena los sonidos de arma"
L["settings.caching.precache_sounds_onfirsttake.desc"] = "Almacena todos los sonidos del arma que acabas de recoger (excepto los sonidos de recarga).\n\nNo es nada impactante, más bien ayuda a evitar tartamudeos al disparar."

L["settings.caching.precache_attsmodels_onfirsttake.title"] = "Al equipar: Almacena los accesorios"
L["settings.caching.precache_attsmodels_onfirsttake.desc"] = "Almacena todos los modelos de accesorios ARC9 cuando cualquier arma ARC9 fue equipada por primera vez.\n\nCausa un gran congelamiento, especialmente cuando tienes muchas armas."
L["settings.caching.precache_wepmodels_onfirsttake.title"] = "Al equipar: Almacena los modelos de arma"
L["settings.caching.precache_wepmodels_onfirsttake.desc"] = "Almacena en caché todos los modelos de armas ARC9 cuando cualquier arma ARC9 se equipa por primera vez.\n\nCausa GRAN congelación, especialmente cuando tienes muchas armas."

L["settings.caching.precache_allsounds_onstartup.title"] = "Al inicio: Almacena los sonidos de arma"
L["settings.caching.precache_allsounds_onstartup.desc"] = "Almacena en caché todos los sonidos de todas las armas al iniciar el servidor. (excepto los sonidos de recarga).\n\nNo es tan impactante, pero de todos modos es mejor utilizar la primera opción aquí."
L["settings.caching.precache_attsmodels_onstartup.title"] = "Al inicio: Almacena los accesorios"
L["settings.caching.precache_attsmodels_onstartup.desc"] = "Almacena en caché todos los modelos de accesorios ARC9 al iniciar el servidor.\n\nProvoca un aumento bastante grande del tiempo de carga, especialmente cuando tienes muchas armas."
L["settings.caching.precache_wepmodels_onstartup.title"] = "Al inicio: Almacena los modelos de arma"
L["settings.caching.precache_wepmodels_onstartup.desc"] = "Almacena en caché todos los modelos de armas ARC9 al iniciar el servidor.\n\nProvoca un aumento REALMENTE GRANDE del tiempo de carga, especialmente cuando tienes muchas armas."

L["settings.caching.precache_allsounds.title"] = "Todos los sonidos de armas"
L["settings.caching.precache_wepmodels.title"] = "Todos los modelos de armas"
L["settings.caching.precache_attsmodels.title"] = "Todos los modelos de accesorios"

L["settings.developer.cache"] = "Almacenar Caché"

////////////////////// Developer
L["settings.tabname.developer"] = "Desarollador"

L["settings.developer.developer"] = "Opciones de Desarollador"
L["settings.developer.dev_always_ready.title"] = "Siempre listo"
L["settings.developer.dev_always_ready.desc"] = "Reproduce siempre la animación \"listo\"cuando despliegues un arma.\n\nEsta es una variable del servidor."
L["settings.developer.dev_benchgun.title"] = "Modelo de Arma Estático"
L["settings.developer.dev_benchgun.desc"] = "Mantén el modelo arma donde está actualmente. Utilidad para ayudar a posicionar accesorios correctamente."
L["settings.developer.dev_crosshair.title"] = "Punto de Mira Dev"
L["settings.developer.dev_crosshair.desc"] = "Un punto de mira de aspecto gracioso que muestra el punto exacto de puntería y algunos números útiles.\n\nEsta es una variable del servidor, y sólo funciona para los administradores - ¡no hagas trampas con esto!"
L["settings.developer.dev_show_shield.title"] = "Mostrar Escudo"
L["settings.developer.dev_show_shield.desc"] = "Muestra el modelo del escudo del jugador."
L["settings.developer.dev_greenscreen.title"] = "Pantalla Verde"
L["settings.developer.dev_greenscreen.desc"] = "Mostrar un fondo de pantalla verde en el menú de personalización para capturas de pantalla.\n\nSi estas utilizando HDR, no olvides de ajustar mat_bloom_scalefactor_scalar a 0!"

L["settings.developer.reloadatts.title"] = "Recargar Accesorios"
L["settings.developer.reloadlangs.title"] = "Recargar Idiomas"
L["settings.developer.dev_listmyatts.title"] = "Listar mis accesorios"
L["settings.developer.dev_listanims.title"] = "Lista de Animaciones"
L["settings.developer.dev_listbones.title"] = "Lista de Huesos"
L["settings.developer.dev_listbgs.title"] = "Lista de Bodygroups"
L["settings.developer.dev_listatts.title"] = "Lista de QCAttachments"
L["settings.developer.dev_export.title"] = "Exportar Código"
L["settings.developer.dev_getjson.title"] = "JSON del Arma"

L["settings.developer.presets_clear.title"] = "Limpiar datos de armas"
L["settings.developer.presets_clear.desc"] = "Borrar preajustes, todos los iconos y preajustes por defecto para el arma que actualmente sostiene.\n\nAdvertencia: Si el menú se abre sin un arma de ARC9 en las manos, se borrarán todos los preajustes e iconos de ARC9 existentes!"

L["settings.developer.clear"] = "Limpiar"
L["settings.developer.print"] = "Imprimir en Consola"
L["settings.developer.reload"] = "Recargar"
