
game.AddParticles( "particles/muzzleflashes_test.pcf" )
game.AddParticles( "particles/muzzleflashes_test_b.pcf" )
game.AddParticles( "particles/cs_weapon_fx.pcf" )
game.AddParticles( "particles/fas_explosions.pcf" )

PrecacheParticleSystem( "muzzleflash_m14" )
PrecacheParticleSystem( "muzzleflash_5" )
PrecacheParticleSystem( "muzzleflash_6" )
PrecacheParticleSystem( "muzzleflash_m79" )
PrecacheParticleSystem( "muzzleflash_pistol_deagle"  )
PrecacheParticleSystem( "muzzleflash_slug" )
PrecacheParticleSystem( "muzzleflash_mp5" )
PrecacheParticleSystem( "muzzleflash_g3" )
PrecacheParticleSystem( "muzzleflash_pistol_red"  )
PrecacheParticleSystem( "muzzleflash_M3" )
PrecacheParticleSystem( "muzzleflash_suppressed"  )
PrecacheParticleSystem( "muzzleflash_suppressed_shotgun"  )
PrecacheParticleSystem( "muzzleflash_4" )
PrecacheParticleSystem( "muzzleflash_ak74" )
PrecacheParticleSystem( "muzzleflash_ak47" )
PrecacheParticleSystem( "muzzleflash_3" )
PrecacheParticleSystem( "muzzleflash_1" )
PrecacheParticleSystem( "muzzleflash_M82" )
PrecacheParticleSystem( "muzzleflash_MINIMI"  )
PrecacheParticleSystem( "port_smoke_heavy" )
PrecacheParticleSystem( "port_shellsmoke" )
PrecacheParticleSystem( "port_smoke" )
PrecacheParticleSystem( "muzzleflash_pistol_cleric"  )
PrecacheParticleSystem( "muzzleflash_OTS" )
PrecacheParticleSystem( "muzzleflash_shotgun"  )
PrecacheParticleSystem( "muzzleflash_smg" )
PrecacheParticleSystem( "muzzleflash_lmg" )
PrecacheParticleSystem( "muzzleflash_FAMAS"  )
PrecacheParticleSystem( "party_spark" )
PrecacheParticleSystem( "muzzleflash_pistol"  )
PrecacheParticleSystem( "muzzleflash_slug_flame"  )
PrecacheParticleSystem( "shellsmoke" )
PrecacheParticleSystem( "barrel_smoke" )
PrecacheParticleSystem( "barrel_smoke_2" )
PrecacheParticleSystem( "barrel_smoke_heavy" )
PrecacheParticleSystem( "muzzleflash_svd" )
PrecacheParticleSystem( "muzzleflash_SR25" )
PrecacheParticleSystem( "muzzleflash_pistol_rbull"  )
PrecacheParticleSystem( "muzzleflash_m24" )
PrecacheParticleSystem( "muzzleflash_vollmer"  )
PrecacheParticleSystem( "muzzle_heatwave"  )
PrecacheParticleSystem( "muzzle_heatwave_long"  )

PrecacheParticleSystem("explosion_grenade" )
PrecacheParticleSystem("explosion_HE_claymore" )
PrecacheParticleSystem("water_explosion_splash" )
PrecacheParticleSystem("explosion_mortarb" )
PrecacheParticleSystem("explosion_water" )
PrecacheParticleSystem("explosion_claymore" )
PrecacheParticleSystem("explosion_m79" )
PrecacheParticleSystem("explosion_HE_m79" )
PrecacheParticleSystem("m79_smoke_d" )
PrecacheParticleSystem("explosion_he_grenade" )
PrecacheParticleSystem("grenade_flash_b" )
PrecacheParticleSystem("explosion_m79_body" )
PrecacheParticleSystem("party_fireworks" )
PrecacheParticleSystem("grenade_final" )
PrecacheParticleSystem("grenade_smoke" )
PrecacheParticleSystem("grenade_thick_smoke" )
PrecacheParticleSystem("grenade_smoke_b" )
PrecacheParticleSystem("grenade_flame" )
PrecacheParticleSystem("grenade_flame_b" )
PrecacheParticleSystem("grenade_shrapnel" )
PrecacheParticleSystem("grenade_shockwave" )
PrecacheParticleSystem("grenade_shockwave_b" )
PrecacheParticleSystem("grenade_flash" )
PrecacheParticleSystem("grenade_flash_c" )
PrecacheParticleSystem("grenade_shrapnel_d" )
PrecacheParticleSystem("m79_flash" )
PrecacheParticleSystem("m79_flash_b" )
PrecacheParticleSystem("m79_flash_c" )
PrecacheParticleSystem("claymore_shrapnel" )
-- PrecacheParticleSystem("claymore_shrapnel_b" )
-- PrecacheParticleSystem("claymore_shrapnel_c" )
-- PrecacheParticleSystem("claymore_shrapnel_d" )
-- PrecacheParticleSystem("claymore_shrapnel_e" )
PrecacheParticleSystem("smoke_plume" )
PrecacheParticleSystem("smoke_plume_c" )
PrecacheParticleSystem("smoke_plume_b" )
PrecacheParticleSystem("grenade_shrapnel_c" )
PrecacheParticleSystem("grenade_shrapnel_b" )
PrecacheParticleSystem("explosion_flash" )
PrecacheParticleSystem("explosion_lensflare" )
PrecacheParticleSystem("HE_flares_b" )
PrecacheParticleSystem("claymore_final" )
PrecacheParticleSystem("claymore_dustwave" )
PrecacheParticleSystem("claymore_smoke" )
PrecacheParticleSystem("claymore_smoke_b" )
PrecacheParticleSystem("claymore_shockwave" )
PrecacheParticleSystem("claymore_flames" )
PrecacheParticleSystem("claymore_flash" )
PrecacheParticleSystem("claymore_flash_b" )
PrecacheParticleSystem("claymore_fastsmoke" )
PrecacheParticleSystem("HE_flares" )
-- PrecacheParticleSystem("HE_grenade_flame" )
-- PrecacheParticleSystem("HE_grenade_flash" )
-- PrecacheParticleSystem("HE_grenade_shrapnel" )
-- PrecacheParticleSystem("HE_grenade_shrapnel_b" )
-- PrecacheParticleSystem("HE_shockwave" )
-- PrecacheParticleSystem("water_explosion_smoke_spike" )
-- PrecacheParticleSystem("water_explosion_d" )
-- PrecacheParticleSystem("water_explosion_flash" )
-- PrecacheParticleSystem("water_explosion_b" )
-- PrecacheParticleSystem("water_explosion_smoke_b" )
-- PrecacheParticleSystem("water_explosion" )
-- PrecacheParticleSystem("water_explosion_splashes" )
-- PrecacheParticleSystem("water_explosion_wake" )
-- PrecacheParticleSystem("water_explosion_wake_b" )
-- PrecacheParticleSystem("water_explosion_wake_c" )
-- PrecacheParticleSystem("water_explosion_final" )
-- PrecacheParticleSystem("water_explosion_c" )
-- PrecacheParticleSystem("water_explosion_drops" )
PrecacheParticleSystem("m79_smoke" )
PrecacheParticleSystem("m79_shrapnel_b" )
PrecacheParticleSystem("m79_smokewave" )
PrecacheParticleSystem("m79_shrapnel" )
PrecacheParticleSystem("m79_flame" )
PrecacheParticleSystem("m79_shrapnel_c" )
PrecacheParticleSystem("m79_debris" )
PrecacheParticleSystem("m79_smoke_e" )
PrecacheParticleSystem("m79_trails_c" )
PrecacheParticleSystem("m79_smoke_c" )
PrecacheParticleSystem("m79_debris_c" )
PrecacheParticleSystem("m79_debris_d" )
PrecacheParticleSystem("m79_shockwave" )
PrecacheParticleSystem("m79_shrapnel_d" )
PrecacheParticleSystem("m79_smoke_b" )
PrecacheParticleSystem("m79_trails_b" )
PrecacheParticleSystem("m79_trails" )
-- PrecacheParticleSystem("m79_body_trails" )
-- PrecacheParticleSystem("m79_body_smoke_b" )
-- PrecacheParticleSystem("m79_body_blood" )
-- PrecacheParticleSystem("m79_body_shrapnel" )
-- PrecacheParticleSystem("m78_body_shrapnel_b" )
-- PrecacheParticleSystem("m79_body_shrapnel_c" )
-- PrecacheParticleSystem("m79_body_gibs" )
-- PrecacheParticleSystem("m79_body_gib_trail" )
-- PrecacheParticleSystem("m79_body_gib_trail_b" )
-- PrecacheParticleSystem("m79_body_gib_trail_fire" )
-- PrecacheParticleSystem("party_fireworks_trail" )
-- PrecacheParticleSystem("party_fireworks_trailb" )
-- PrecacheParticleSystem("party_fireworks_flashes" )
-- PrecacheParticleSystem("party_fireworksb" )
-- PrecacheParticleSystem("party_fireworks_flash" )
-- PrecacheParticleSystem("party_fireworks_glow" )