
game.AddParticles( "particles/muzzleflashes_test.pcf" )
--game.AddParticles( "particles/muzzleflashes_test_b.pcf" ) -- Why and What is this?
game.AddParticles( "particles/fas_explosions.pcf" )

PrecacheParticleSystem( "muzzleflash_1" )
PrecacheParticleSystem( "muzzleflash_2" )
PrecacheParticleSystem( "muzzleflash_3" )
PrecacheParticleSystem( "muzzleflash_4" )
PrecacheParticleSystem( "muzzleflash_5" )
PrecacheParticleSystem( "muzzleflash_6" )
---- Muzzle Weapon Specific
PrecacheParticleSystem( "muzzleflash_pistol_cleric"  )
PrecacheParticleSystem( "muzzleflash_pistol_red"  )
PrecacheParticleSystem( "muzzleflash_pistol_deagle"  )
PrecacheParticleSystem( "muzzleflash_pistol_rbull"  )
PrecacheParticleSystem( "muzzleflash_mp5" )
PrecacheParticleSystem( "muzzleflash_M3" )
PrecacheParticleSystem( "muzzleflash_FAMAS"  )
PrecacheParticleSystem( "muzzleflash_g3" )
PrecacheParticleSystem( "muzzleflash_ak74" )
PrecacheParticleSystem( "muzzleflash_ak47" )
PrecacheParticleSystem( "muzzleflash_MINIMI"  )
PrecacheParticleSystem( "muzzleflash_OTS" )
PrecacheParticleSystem( "muzzleflash_svd" )
PrecacheParticleSystem( "muzzleflash_SR25" )
PrecacheParticleSystem( "muzzleflash_m24" )
PrecacheParticleSystem( "muzzleflash_m14" )
PrecacheParticleSystem( "muzzleflash_M82" )
PrecacheParticleSystem( "muzzleflash_vollmer"  )
PrecacheParticleSystem( "muzzleflash_m79" )
---- Muzzle Weapon Types
PrecacheParticleSystem( "muzzleflash_pistol"  )
PrecacheParticleSystem( "muzzleflash_smg" )
PrecacheParticleSystem( "muzzleflash_ar" )
PrecacheParticleSystem( "muzzleflash_shotgun"  )
PrecacheParticleSystem( "muzzleflash_slug" )
PrecacheParticleSystem( "muzzleflash_lmg" )
PrecacheParticleSystem( "muzzleflash_dmr" )
PrecacheParticleSystem( "muzzleflash_suppressed"  )
PrecacheParticleSystem( "muzzleflash_suppressed_shotgun"  )
---- Shell eject
PrecacheParticleSystem( "shellsmoke" )
PrecacheParticleSystem( "port_shellsmoke" )
PrecacheParticleSystem( "port_smoke" )
PrecacheParticleSystem( "port_smoke_heavy" )
---- After Effects
PrecacheParticleSystem( "barrel_smoke" )
PrecacheParticleSystem( "barrel_smoke_2" )
PrecacheParticleSystem( "barrel_smoke_heavy" )

---- Explosion Effects
PrecacheParticleSystem("explosion_grenade" )
PrecacheParticleSystem("explosion_mortarb" )
PrecacheParticleSystem("explosion_water" )
PrecacheParticleSystem("explosion_claymore" )
PrecacheParticleSystem("explosion_m79" )
PrecacheParticleSystem("explosion_m79_body" )
PrecacheParticleSystem("explosion_HE_m79" )
PrecacheParticleSystem("explosion_HE_claymore" )
PrecacheParticleSystem("explosion_he_grenade" )
PrecacheParticleSystem("grenade_final" )
PrecacheParticleSystem("claymore_final" )
PrecacheParticleSystem("party_fireworks" )
PrecacheParticleSystem("grenade_flash" )
PrecacheParticleSystem("explosion_flash" )
PrecacheParticleSystem("smoke_plume" )
